const fs = require('fs');

const filePath = 'c:/dev/gyosei-quest-small/src/questions.js';

try {
    let content = fs.readFileSync(filePath, 'utf8');

    // JSON.parse は export ... があると失敗するため、一度オブジェクト化する
    // (今回は eval で展開して構造的にフィルタリングし、文字列に戻す)
    const scriptContent = content
        .replace('export const SUBJECTS =', 'global.SUBJECTS =')
        .replace(/import .*/g, '// $&');

    eval(scriptContent);

    if (!global.SUBJECTS) throw new Error('Failed to eval SUBJECTS');

    const subjects = global.SUBJECTS;
    let removedCount = 0;
    let keptCount = 0;

    for (const sKey in subjects) {
        for (const subKey in subjects[sKey]) {
            const arr = subjects[sKey][subKey];
            if (Array.isArray(arr)) {
                const originalLen = arr.length;
                subjects[sKey][subKey] = arr.filter(q => {
                    // 必須キー（choices, answer, text）が揃っているか
                    const isQuestion = q.text && q.choices && q.answer;
                    if (!isQuestion) removedCount++;
                    else keptCount++;
                    return isQuestion;
                });
            }
        }
    }

    console.log(`Cleansing Results: Kept ${keptCount}, Removed ${removedCount} non-question items.`);

    // 文字列に戻して保存
    // 巨大なオブジェクトを JSON.stringify すると「"」のエスケープ等が変わる可能性があるが、
    // 今は「動くこと」を最優先する。
    const newContent = `// Generated by cleansing script\nexport const SUBJECTS = ${JSON.stringify(subjects, null, 2)};`;
    fs.writeFileSync(filePath, newContent, 'utf8');
    console.log('src/questions.js has been cleansed and saved.');

} catch (err) {
    console.error('Cleansing Failed:', err);
    process.exit(1);
}
