import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { SUBJECTS } from '../src/questions.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const targetFile = path.join(__dirname, '../src/questions.js');

function stripImages(text) {
    return text.replace(/\[\[image:[^\]]+\]\]\s*/g, '').trim();
}

function getImages(text) {
    const matches = text.match(/\[\[image:[^\]]+\]\]/g);
    return matches || [];
}

const explainGroups = new Map();
let updatesCount = 0;

// 1. Group Identical Explanations
for (const subjectKey in SUBJECTS) {
    const subject = SUBJECTS[subjectKey];
    for (const subKey in subject) {
        const questions = subject[subKey];
        questions.forEach((q, index) => {
            if (!q.explain) return;

            const cleanText = stripImages(q.explain);
            if (!cleanText) return;

            if (!explainGroups.has(cleanText)) {
                explainGroups.set(cleanText, []);
            }
            explainGroups.get(cleanText).push(q);
        });
    }
}

// 2. Sync Images
for (const [text, questions] of explainGroups) {
    if (questions.length < 2) continue;

    // Collect all unique images from this group
    const allImages = new Set();
    questions.forEach(q => {
        getImages(q.explain).forEach(img => allImages.add(img));
    });

    if (allImages.size === 0) continue;

    // Sort to ensure deterministic order
    const sortedImages = Array.from(allImages).sort();
    const imagePrefix = sortedImages.join('\n\n') + '\n\n';

    // The clean text we grouped by is "text", but we need the original text without images to prepend to.
    // Actually, "text" is the cleaned text. 
    // Construct new explain: Images + Clean Text. (Preserving original non-image structure?)
    // "stripImages" removes images and trims.
    // If the original text had specific whitespace formatting between text blocks, it might be preserved in "text" if stripImages only targets images.
    // The "text" key in explainGroups IS the duplicate content signature.

    // Let's reconstruct.
    const newExplain = imagePrefix + text;

    questions.forEach(q => {
        const currentClean = stripImages(q.explain);
        const currentImages = getImages(q.explain);

        // If current images don't match the full set, update.
        // Or if the text structure matches but we just want to ensure consistency.
        // To be safe, let's just update if the generated string is different.

        // Note: Formatting might be slightly different if we blindly construct.
        // But since they are duplicates, using the "cleanText" + images should standardize them too.

        if (q.explain !== newExplain) {
            q.explain = newExplain;
            updatesCount++;
        }
    });
}

console.log(`Updated ${updatesCount} questions.`);

// 3. Write back to file
const fileContent = `// Generated by syncQuiz.js
export const SUBJECTS = ${JSON.stringify(SUBJECTS, null, 2)};
`;

fs.writeFileSync(targetFile, fileContent, 'utf8');
console.log('Saved src/questions.js');
