/**
 * 質問モード論点ガイドのトリガー照合チェック（基礎法学・行政法総論）。
 * 用法: node --experimental-strip-types scripts/checkChatTopicBriefs.mjs
 */
import { GYOSEI_PROC_COMPARISON_BRIEFS } from '../utils/chatTopicBriefsGyoseiComparisons.ts';
import { GYOSEI_FUFUKU_CHAT_BRIEFS } from '../utils/chatTopicBriefsGyoseiFufuku.ts';
import { GYOSEI_GYOSHO_CHAT_BRIEFS } from '../utils/chatTopicBriefsGyoseiGyosho.ts';
import { GYOSEI_SORON_CHAT_BRIEFS } from '../utils/chatTopicBriefsGyoseiSoron.ts';
import { GYOSEI_SORON_NET_CHAT_BRIEFS } from '../utils/chatTopicBriefsGyoseiSoronNet.ts';
import { GYOSEI_TETSUZUKI_CHAT_BRIEFS } from '../utils/chatTopicBriefsGyoseiTetsuzuki.ts';
import { KENPOU_CHAT_BRIEFS } from '../utils/chatTopicBriefsKenpou.ts';
import { KENPOU_DEEP_CHAT_BRIEFS } from '../utils/chatTopicBriefsKenpouDeep.ts';
import { KENPOU_HANREI_CHAT_BRIEFS } from '../utils/chatTopicBriefsKenpouHanrei.ts';
import { KENPOU_HANREI2_CHAT_BRIEFS } from '../utils/chatTopicBriefsKenpouHanrei2.ts';
import { KENPOU_YAMA_CHAT_BRIEFS } from '../utils/chatTopicBriefsKenpouYama.ts';
import { KISO_HOUGAKU_COMPARISON_BRIEFS } from '../utils/chatTopicBriefsKisoComparisons.ts';
import { KISO_HOUGAKU_CHAT_TOPIC_BRIEFS } from '../utils/chatTopicBriefsKisoHougaku.ts';
import { KISO_HOUGAKU_MOSHI_BRIEFS } from '../utils/chatTopicBriefsKisoMoshi.ts';
import { KOKUBAI_CHAT_BRIEFS } from '../utils/chatTopicBriefsKokubai.ts';
import { MINPOU_CHAT_BRIEFS } from '../utils/chatTopicBriefsMinpou.ts';
import { NAKA_GYOSEI_YAMA_CHAT_BRIEFS } from '../utils/chatTopicBriefsNakaGyoseiYama.ts';
import { NAKA_MINPOU_YAMA_CHAT_BRIEFS } from '../utils/chatTopicBriefsNakaMinpouYama.ts';

function norm(s) {
  return (s || '').normalize('NFKC').toLowerCase().replace(/\s+/g, ' ').trim();
}

function stripNoise(s) {
  let t = norm(s)
    .replace(/[?？!！。．、,，･・…]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const tail =
    /(ってなに|って何|ってなん|って誰|ってだれ|とは何|とはなに|とはなん|ってどういう意味|どういう意味|について教えて|を教えて|を説明して|について|とは|って|教えてくれ|教えて|説明して|の違い|違い)$/;
  for (let i = 0; i < 4; i++) {
    const next = t.replace(tail, '').trim();
    if (next === t) break;
    t = next;
  }
  return t;
}

function matchBriefs(query, briefs) {
  const raw = norm(query);
  const core = stripNoise(query);
  const blob = `${raw}\n${core}`;
  return briefs.filter((b) => b.triggers.some((t) => blob.includes(norm(t))));
}

const cases = [
  { q: '実定法と実体法の違いは？', expectTitle: /実定法と実体法/ },
  { q: '法の支配と法治主義の違い', expectTitle: /法の支配と法治主義/ },
  { q: '公布と施行ってなん？', expectTitle: /公布と施行/ },
  { q: '後法優先と特別法優先', expectTitle: /後法優先と特別法優先/ },
  { q: '失効と廃止の違い', expectTitle: /失効と廃止/ },
  { q: '続審と事後審', expectTitle: /続審と事後審/ },
  { q: '控訴と抗告の違いは', expectTitle: /控訴と抗告/ },
  { q: '調停と仲裁', expectTitle: /調停と仲裁/ },
  { q: '少額訴訟と認定司法書士', expectTitle: /少額訴訟.*認定司法書士|認定司法書士/ },
  { q: '法律と法令の違い', expectTitle: /法・法律・法令|法律と法令/ },
  { q: '要件事実と立法事実', expectTitle: /要件事実と立法事実/ },
  { q: '強行法規と任意法規', expectTitle: /強行法規と任意法規/ },
  { q: '行為規範と裁判規範', expectTitle: /行為規範/ },
  { q: '成文法と不文法', expectTitle: /成文法と不文法/ },
  { q: '判決と決定の違い', expectTitle: /判決と決定/ },
  { q: '一般法と特別法', expectTitle: /一般法と特別法/ },
  { q: '公法と私法', expectTitle: /公法.*私法/ },
  { q: '実体法と手続法', expectTitle: /実体法と手続法/ },
  { q: '大陸法と英米法', expectTitle: /大陸法と英米法/ },
  // 模試由来・基礎法学
  { q: '拘禁刑ってなん？', expectTitle: /拘禁刑/ },
  { q: '応報刑論と目的刑論の違い', expectTitle: /応報刑論と目的刑論/ },
  { q: '検察審査会は何人', expectTitle: /検察審査会/ },
  { q: '裁判員裁判の人数', expectTitle: /裁判員/ },
  { q: '検察審査会と裁判員', expectTitle: /検察審査会11人|11人と9人/ },
  { q: '拡張解釈と類推解釈の違い', expectTitle: /拡張解釈と類推解釈/ },
  { q: '反対解釈とは', expectTitle: /法解釈の4類型|反対解釈/ },
  { q: '立法者の意思', expectTitle: /法解釈の4類型/ },
  { q: '工場内の機械は土地の工作物', expectTitle: /法解釈の4類型/ },
  { q: '内縁の財産分与', expectTitle: /法解釈の4類型/ },
  { q: 'オランダ法学', expectTitle: /外国法の継受|明治期の法制史|オランダ/ },
  { q: '外国法の継受', expectTitle: /外国法の継受/ },
  { q: 'ボアソナード民法', expectTitle: /外国法の継受|ボアソナード/ },
  { q: '処分権主義と弁論主義', expectTitle: /処分権|民訴/ },
  { q: 'その他とその他の', expectTitle: /その他/ },
  { q: '過料は科する', expectTitle: /課すると科する|科する/ },
  { q: '直ちに 速やかに 遅滞なく', expectTitle: /直ちに/ },
  { q: '刑が重くなった', expectTitle: /刑の変更|刑法6条/ },
  { q: '先定特別法', expectTitle: /後法優先|特別法/ },
  { q: '法律と命令', expectTitle: /法律と命令|法・法律・法令/ },
  { q: '国外犯に刑法は及ぶ？', expectTitle: /刑法の場所的適用|国外/ },
  { q: '仲裁とあっせんの違い', expectTitle: /仲裁|あっせん|ADR/ },
  { q: '調停委員会', expectTitle: /調停/ },
  { q: '学説は法源', expectTitle: /条理|学説|法源/ },
  { q: '刑事 条理', expectTitle: /条理/ },
  { q: '法令違憲 大法廷', expectTitle: /大法廷|管轄/ },
  { q: '人事訴訟 第一審', expectTitle: /人事訴訟|管轄/ },
  { q: '認定司法書士', expectTitle: /認定司法書士/ },
  { q: 'くじで選任されるのってだれ？', expectTitle: /くじ/ },
  { q: 'くじ引きってなに', expectTitle: /くじ|選任方法/ },
  { q: '検察審査員は誰', expectTitle: /検察審査員/ },
  { q: '裁判員は誰がなる', expectTitle: /裁判員は誰/ },
  { q: 'くじで選ばれないのは', expectTitle: /くじ/ },
  { q: '無作為に選ばれる市民', expectTitle: /くじ/ },
  // 行政法総論・判例クラスタ
  { q: '薬局の距離適正規定って何だったかな', expectTitle: /薬局距離/ },
  { q: '薬局距離制限', expectTitle: /薬局距離|距離規制/ },
  { q: '小売市場の距離制限', expectTitle: /小売市場/ },
  { q: '病院の距離規制', expectTitle: /距離規制|病院開設/ },
  { q: '病院開設中止勧告', expectTitle: /病院開設/ },
  { q: '公衆浴場の距離と原告適格', expectTitle: /公衆浴場|原告適格/ },
  { q: '取消しと撤回の違い', expectTitle: /取消し・撤回|撤回/ },
  { q: '権限の委任と代理', expectTitle: /委任・法定代理|授権代理/ },
  { q: '授権代理', expectTitle: /授権代理|委任/ },
  { q: '専決と代決', expectTitle: /専決|代決/ },
  { q: '法定代理 機関の指定', expectTitle: /法定代理|機関/ },
  { q: '課税処分 無効', expectTitle: /課税処分の当然無効|取消し・撤回・無効/ },
  { q: '重大な瑕疵があればいい', expectTitle: /課税処分の当然無効/ },
  { q: '人工妊娠中絶 指定', expectTitle: /撤回|指定医/ },
  { q: '理由附記 治癒', expectTitle: /理由の提示|治癒/ },
  { q: '代執行ってなん？', expectTitle: /代執行/ },
  { q: '条例 代執行', expectTitle: /代執行/ },
  { q: '戒告 省略', expectTitle: /代執行|強制執行/ },
  { q: '危険切迫 代執行', expectTitle: /代執行/ },
  { q: '国税滞納処分 代執行', expectTitle: /代執行/ },
  { q: '直接強制 条例', expectTitle: /代執行|強制執行|即時強制/ },
  { q: '人工妊娠中絶 期間', expectTitle: /撤回|指定医/ },
  { q: '猿払と堀越の違い', expectTitle: /猿払|堀越/ },
  { q: '公定力と不可争力', expectTitle: /公定力/ },
  { q: '代執行と即時強制', expectTitle: /強制執行|即時強制|代執行/ },
  { q: '行政罰と秩序罰', expectTitle: /行政罰|秩序罰/ },
  { q: '神戸高専剣道', expectTitle: /神戸高専/ },
  { q: '宜野座村事件', expectTitle: /宜野座/ },
  // 行政法総論・X/ネット口語FAQ
  { q: '行政法ってどの法律？', expectTitle: /行政法ってどの法律/ },
  { q: '法律の留保ってなに', expectTitle: /法律による行政の原理|法律の留保/ },
  { q: '侵害留保説と全部留保説', expectTitle: /侵害留保/ },
  { q: '許可と認可と特許の違い', expectTitle: /許可・認可・特許|特許・許可・確認/ },
  { q: '許可は命令的', expectTitle: /特許・許可・確認|許可・認可・特許/ },
  { q: '特許は形成的', expectTitle: /特許・許可・確認|許可・認可・特許/ },
  { q: '黙示的廃止 取得時効', expectTitle: /公物|黙示/ },
  { q: '海没地', expectTitle: /公物|海没/ },
  { q: '道路 通行 妨害排除', expectTitle: /公物|通行/ },
  { q: '道路法4条 登記', expectTitle: /公物|道路/ },
  { q: '国籍離脱 父', expectTitle: /私人の公法行為|国籍離脱/ },
  { q: '公認会計士 登録抹消', expectTitle: /私人の公法行為|会計士/ },
  { q: '退職願 撤回', expectTitle: /私人の公法行為|退職/ },
  { q: '第三者名義 申告', expectTitle: /私人の公法行為|申告/ },
  { q: '確定申告 過誤', expectTitle: /私人の公法行為|過誤/ },
  { q: 'ヨット 鉄杭', expectTitle: /法律による行政|ヨット|留保/ },
  { q: '必要最小限度 制約', expectTitle: /比例原則|平等原則/ },
  { q: '比例原則と平等原則', expectTitle: /比例原則|平等原則/ },
  { q: '内閣府の外局', expectTitle: /内閣府の外局|外局/ },
  { q: '公正取引委員会 外局', expectTitle: /内閣府の外局|外局/ },
  { q: '執行罰 憲法39', expectTitle: /行政罰|秩序罰|執行罰/ },
  { q: '加算税 罰金', expectTitle: /行政罰|秩序罰|執行罰|加算税/ },
  { q: '条例違反 秩序罰', expectTitle: /行政罰|秩序罰|執行罰/ },
  { q: '氏名の公表', expectTitle: /行政罰|秩序罰|執行罰|公表/ },
  { q: '現業公務員 公法', expectTitle: /現業|公法関係|別荘/ },
  { q: '別荘 水道料金', expectTitle: /別荘|水道/ },
  { q: '被爆者援護法 相続', expectTitle: /朝日|堀木|被爆者/ },
  { q: '租税以外の公課', expectTitle: /84条|国保|公課/ },
  { q: '国家公務員法102条 白紙委任', expectTitle: /猿払|堀越|102|白紙委任/ },
  { q: '処分性ってなに', expectTitle: /処分性ってなに|処分性の見方/ },
  { q: '原告適格わからん', expectTitle: /原告適格/ },
  { q: '反射的利益ってなに', expectTitle: /反射的利益|原告適格/ },
  { q: '建築確認は処分？', expectTitle: /建築確認/ },
  { q: '条例に処分性あるの', expectTitle: /条例でも処分性|保育所/ },
  { q: '用途地域と区画整理', expectTitle: /用途地域/ },
  { q: '第二種市街地再開発 処分性', expectTitle: /第二種|区画整理|用途地域/ },
  { q: '検定細則 委任', expectTitle: /委任立法|検定細則|薬事/ },
  { q: '薬事法 ネット販売', expectTitle: /委任立法|薬事ネット|郵便等販売/ },
  { q: '使用禁止 代執行', expectTitle: /代執行/ },
  { q: '附款 準法律行為', expectTitle: /附款|特許・許可・確認/ },
  { q: '事務次官 副大臣', expectTitle: /事務次官|副大臣/ },
  { q: '分限処分 目的', expectTitle: /裁量|分限/ },
  { q: '神戸税関 懲戒', expectTitle: /裁量|神戸税関|懲戒/ },
  { q: '収用委員会 裁量', expectTitle: /裁量|収用/ },
  { q: '建築確認 裁量', expectTitle: /裁量|建築確認|羈束/ },
  { q: '生活保護 裁量', expectTitle: /裁量|朝日|生活保護|生存権/ },
  { q: '代執行 第三者', expectTitle: /代執行/ },
  { q: '国家賠償と損失補償の違い', expectTitle: /国家賠償と損失補償/ },
  { q: '不可変更力ってなに', expectTitle: /不可変更力/ },
  { q: '取消訴訟何から考える', expectTitle: /訴訟要件|順番/ },
  // 行政手続法
  { q: '申請と届出の違いは？', expectTitle: /申請と届出/ },
  { q: '審査基準と処分基準', expectTitle: /審査基準と処分基準/ },
  { q: '聴聞と弁明の違い', expectTitle: /聴聞と弁明/ },
  { q: '口頭意見陳述', expectTitle: /口頭意見陳述|口頭でできる/ },
  { q: '口頭で審査請求', expectTitle: /口頭|審理手続/ },
  { q: '弁明は口頭', expectTitle: /口頭でできる|聴聞と弁明/ },
  { q: '標準処理期間ってなに', expectTitle: /標準処理期間/ },
  { q: '意見公募の対象は', expectTitle: /意見公募/ },
  { q: '行政指導の中止等の求め', expectTitle: /行政指導/ },
  { q: '理由の提示はいつ', expectTitle: /理由の提示/ },
  { q: '申請拒否と不利益処分', expectTitle: /申請拒否.*不利益|不利益処分/ },
  { q: '施設 区間 地域 意見公募', expectTitle: /意見公募/ },
  { q: '特別の設立行為 行手法', expectTitle: /適用除外|特殊法人/ },
  { q: '殊更に遅延', expectTitle: /申請処理|遅延/ },
  { q: '行政上特別の支障', expectTitle: /審査基準と処分基準|特別の支障/ },
  { q: '陳述書 主宰者', expectTitle: /聴聞手続の中身|主宰者/ },
  { q: '聴聞 報告書 速やかに', expectTitle: /聴聞手続の中身|申請処理/ },
  { q: '続行 聴聞 告知', expectTitle: /聴聞手続の中身|続行/ },
  { q: '法令 条例 規則', expectTitle: /適用除外|法令/ },
  { q: '届出 義務付け', expectTitle: /申請と届出/ },
  { q: '行政指導 具体例', expectTitle: /行政指導/ },
  { q: '無灯火 行政指導', expectTitle: /行政指導/ },
  { q: '聴聞 書面 通知', expectTitle: /聴聞手続の中身|聴聞/ },
  { q: '行政指導指針 公表', expectTitle: /行政指導|審査基準/ },
  { q: '弁明 公示送達', expectTitle: /聴聞と弁明/ },
  { q: '弁明 閲覧', expectTitle: /聴聞と弁明/ },
  { q: '弁明 参加人', expectTitle: /聴聞と弁明/ },
  { q: '処分基準 弁明', expectTitle: /聴聞と弁明|審査基準と処分基準/ },
  { q: '委員会 意見公募', expectTitle: /意見公募/ },
  { q: '命令等を定めない', expectTitle: /意見公募/ },
  { q: '結果の公示', expectTitle: /意見公募/ },
  { q: '固有の資格 行手法', expectTitle: /適用除外|固有/ },
  { q: '行政指導 固有の資格', expectTitle: /適用除外|固有|行政指導/ },
  { q: '一部が出頭しない', expectTitle: /聴聞手続の中身/ },
  { q: '閲覧を拒む', expectTitle: /聴聞手続の中身/ },
  { q: '補佐人 聴聞', expectTitle: /聴聞手続の中身|主宰者/ },
  { q: '差し迫った必要 理由', expectTitle: /理由の提示/ },
  { q: '参加人 代理人', expectTitle: /承継・代理人|聴聞手続|参加人/ },
  // 行政不服審査法
  { q: '再調査と審査請求の違い', expectTitle: /再調査/ },
  { q: '執行停止の要件', expectTitle: /執行停止/ },
  { q: '審理員ってなに', expectTitle: /審理員/ },
  { q: '不作為の審査請求', expectTitle: /不作為/ },
  { q: '教示ってなに', expectTitle: /教示/ },
  { q: '行手法と行服法の違い', expectTitle: /行政手続法と行政不服審査法/ },
  { q: '審査請求の期間は', expectTitle: /審査請求の期間/ },
  { q: '不利益変更はできる？', expectTitle: /裁決|不利益変更/ },
  { q: '不当と不等', expectTitle: /不当と不等/ },
  { q: '当事者訴訟 適用除外', expectTitle: /7条適用除外|当事者訴訟/ },
  { q: '審理員 直ちに', expectTitle: /29条1項|直ちに写し/ },
  { q: '職権 鑑定', expectTitle: /33〜36|職権調査/ },
  { q: '却下と棄却', expectTitle: /却下.*棄却|45条1項/ },
  { q: '固有の資格 行服', expectTitle: /固有の資格/ },
  { q: '固有の資格 行手 行服', expectTitle: /固有の資格.*行手法|行手法.*固有/ },
  { q: '一方を被告', expectTitle: /7条適用除外|当事者訴訟/ },
  // 比較学習（違いをまとめて）
  { q: '審理員と主宰者の違いをまとめて', expectTitle: /審理員.*主宰者|主宰者.*審理員/ },
  { q: '努力義務を行手法と行服法で並べて', expectTitle: /努力義務の並列/ },
  { q: '努めるものとする', expectTitle: /努力義務の並列/ },
  { q: '標準処理期間ってなに', expectTitle: /標準処理期間|努力義務の並列/ },
  { q: '意見公募 周知', expectTitle: /意見公募|努力義務の並列/ },
  { q: '弁明は原則書面', expectTitle: /聴聞と弁明/ },
  { q: '意見提出期間 30日', expectTitle: /意見公募/ },
  { q: '30日を下回', expectTitle: /意見公募/ },
  { q: '案の大根', expectTitle: /意見公募/ },
  { q: '命令等の案 根拠', expectTitle: /意見公募/ },
  { q: '公示 総務大臣', expectTitle: /意見公募/ },
  { q: '提出意見 採用', expectTitle: /意見公募/ },
  { q: '弁明って口頭でいいの', expectTitle: /口頭でできる|聴聞と弁明/ },
  { q: '行政庁が認めたとき 弁明', expectTitle: /口頭でできる|聴聞と弁明/ },
  { q: '題名や趣旨、理由を公示', expectTitle: /意見公募/ },
  { q: '一件の工事 総務大臣', expectTitle: /意見公募/ },
  { q: '努力義務8シリーズ', expectTitle: /努力義務の並列/ },
  { q: '行政書士法 努力義務', expectTitle: /努力義務の並列/ },
  { q: '執行停止の違いをまとめて', expectTitle: /執行停止.*行政不服審査法|執行停止（/ },
  { q: '地位承継 許可', expectTitle: /承継・代理人|15条6項|地位承継/ },
  { q: '権利を譲り受け 審査庁', expectTitle: /承継|15条6項|地位承継/ },
  { q: '取下げ 書面 審理員', expectTitle: /取下げ|27条/ },
  { q: '46条 変更 いずれでもない', expectTitle: /46条|変更権/ },
  { q: '執行不停止 時効', expectTitle: /執行不停止|25条1項|18条/ },
  { q: '執行停止取消 行服 行訴', expectTitle: /執行停止の取消|行服26|26条.*行訴/ },
  { q: '公共の福祉 明らか 執行停止', expectTitle: /執行停止の取消|26条/ },
  { q: '不作為 申請内容 19条', expectTitle: /不作為|19条|記載/ },
  { q: '知った年月日 審査請求', expectTitle: /19条|記載|知った/ },
  { q: '不作為 参加人 審理員', expectTitle: /参加|13条|請求人/ },
  { q: '23条 補正命令', expectTitle: /23|補正|不備/ },
  { q: '24条2項 補正不能', expectTitle: /24|補正/ },
  { q: '28条 計画的進行', expectTitle: /28|計画|相互協力/ },
  { q: '補正 行服 行手法 比較', expectTitle: /23|7条|補正/ },
  { q: '事情裁決 主文', expectTitle: /事情裁決|45条/ },
  { q: '宮内庁 審査請求', expectTitle: /4条|審査請求先|庁の長/ },
  { q: '上級 自ら処分', expectTitle: /46条|命ず|自ら/ },
  { q: '相続 届出 15条', expectTitle: /15条|承継|届出/ },
  { q: '譲受 審査庁 許可', expectTitle: /15条|承継|許可/ },
  { q: '条例 審査請求先', expectTitle: /4条|条例|審査請求/ },
  { q: '証拠書類 処分庁 提出', expectTitle: /証拠|32|職権調査/ },
  { q: '留め置き 審理員', expectTitle: /留め置き|33|職権/ },
  { q: '検証 立会 申立', expectTitle: /検証|35|立会/ },
  { q: '審理関係人 質問 36条', expectTitle: /質問|36|職権/ },
  { q: '当事者訴訟 争点訴訟', expectTitle: /当事者|争点/ },
  { q: 'ガクト 額', expectTitle: /当事者|争点|ガクト/ },
  { q: '市長 怠る事実', expectTitle: /民衆|住民|怠る/ },
  { q: '保育所廃止 処分', expectTitle: /保育所|条例|処分/ },
  { q: '水道料金 条例 処分', expectTitle: /水道|条例|処分|高根/ },
  { q: '開発同意拒否 処分', expectTitle: /同意|開発|処分/ },
  { q: '病院開設中止勧告 処分', expectTitle: /病院|勧告|処分|同意/ },
  { q: '選挙無効 被告', expectTitle: /民衆|機関|選挙/ },
  { q: '機関訴訟 被告', expectTitle: /民衆|機関/ },
  { q: '長沼ナイキ 原告適格', expectTitle: /原告適格|長沼/ },
  { q: '場外車券 原告適格', expectTitle: /原告適格|場外/ },
  { q: '風俗 制限区域 原告適格', expectTitle: /原告適格|風俗/ },
  { q: '効力の停止 執行の停止', expectTitle: /執行停止/ },
  { q: '内閣総理大臣の異議', expectTitle: /執行停止|異議/ },
  { q: '31条2項 終局判決前', expectTitle: /事情判決|31/ },
  { q: '棄却判決 拘束力', expectTitle: /取消判決|拘束|第三者/ },
  { q: '裁量の逸脱 濫用', expectTitle: /裁量/ },
  { q: '申請型 重大な損害 不要', expectTitle: /義務付け|申請型/ },
  { q: '廃棄物処理 原告適格', expectTitle: /原告適格|廃棄物|ごみ/ },
  { q: '医師 病院 原告適格', expectTitle: /原告適格|医師|病院/ },
  { q: '著作権72条 被告', expectTitle: /著作権|72条|形式的当事者/ },
  { q: '再免許 訴えの利益', expectTitle: /訴えの利益|再免許|昭43/ },
  { q: '免停 1年 利益', expectTitle: /訴えの利益|免停|昭55/ },
  { q: '棄却 国賠 既判力', expectTitle: /取消.*国賠|国賠.*取消/ },
  { q: '原告 棄却 国家賠償', expectTitle: /取消.*国賠|国賠.*取消/ },
  { q: '違法性相対化', expectTitle: /取消.*国賠|国賠.*取消/ },
  { q: '歴史的・学術的価値 補償', expectTitle: /学術価値|輪中堤|損失補償/ },
  { q: '第二次大戦 損失補償', expectTitle: /戦時|戦争損害|学術価値|損失補償/ },
  { q: '工作物の移転 補償', expectTitle: /工作物|警察法規|学術価値|損失補償/ },
  { q: '輪中堤', expectTitle: /輪中堤|学術価値|損失補償/ },
  { q: '戦争損害 受忍', expectTitle: /戦争損害|戦時|学術価値|損失補償/ },
  { q: '建築制限 補償', expectTitle: /建築制限|斟酌|損失補償/ },
  { q: '都市計画 補償価格', expectTitle: /建築制限|斟酌|損失補償/ },
  { q: '河川附近地制限令', expectTitle: /河川附近地|29条3項|損失補償/ },
  { q: '補償規定がない 違憲', expectTitle: /河川附近地|29条3項|損失補償/ },
  { q: '消火 損失補償', expectTitle: /消火|消防|破壊消防|損失補償/ },
  { q: '消防法29条', expectTitle: /消火|消防|破壊消防|損失補償/ },
  { q: '行政財産 使用許可 補償', expectTitle: /行政財産|使用許可|損失補償/ },
  { q: '損失補償 定番', expectTitle: /損失補償|模試定番|建築制限/ },
  { q: '宅建業者 不正 国賠', expectTitle: /宅建|著しく不合理|監督/ },
  { q: '不正なのになぜ', expectTitle: /宅建|著しく不合理|監督/ },
  { q: '靖国 大嘗祭', expectTitle: /靖国|大嘗祭/ },
  { q: '無罪 起訴 国賠', expectTitle: /起訴|無罪/ },
  { q: 'パトカー 開始 継続 方法', expectTitle: /パトカー|追跡/ },
  { q: '民事仮処分 当事者訴訟', expectTitle: /当事者訴訟|仮処分/ },
  { q: '衆議院 解散 訴えの利益', expectTitle: /訴えの利益|解散/ },
  { q: '訴訟費用 当事者訴訟', expectTitle: /訴訟費用|35/ },
  { q: '仮の義務付け 取り消された', expectTitle: /仮の義務付け|取消|26条|準用/ },
  { q: '申請 不適法 不作為', expectTitle: /不作為|違法確認/ },
  { q: '差止め 重大な損害', expectTitle: /差止め|重大/ },
  { q: '仮の差止め 26条', expectTitle: /差止め|仮|26|準用/ },
  { q: '労災就学援護費 処分', expectTitle: /処分性|労災|就学|続柄|内定/ },
  { q: '続柄記載 処分', expectTitle: /処分性|続柄|労災|内定/ },
  { q: '採用内定取消 処分', expectTitle: /処分性|内定|続柄|労災/ },
  { q: '検査官会議 審査請求', expectTitle: /検査官会議|7条/ },
  { q: '行政不服審査会 総務省', expectTitle: /行政不服審査会|67条|総務省/ },
  { q: '審査会 9人 非常勤', expectTitle: /行政不服審査会|68条|9人|非常勤/ },
  { q: '審査会 何をする', expectTitle: /行政不服審査会|答申|裁決/ },
  { q: '72条 合議体', expectTitle: /合議体|72条|3人/ },
  { q: '審理員と審査会 違い', expectTitle: /審理員.*審査会|審査会.*審理員/ },
  { q: '答申 裁決 違い', expectTitle: /答申|裁決/ },
  { q: '75条 口頭意見', expectTitle: /75条|口頭|審査会/ },
  { q: '再審査 1か月 期間', expectTitle: /再審査|62条|期間/ },
  { q: '審査請求期間 比較', expectTitle: /54条|18条|62条|期間/ },
  { q: '違いをまとめて', expectTitle: /違いをまとめて|メニュー/ },
  // 行政事件訴訟法
  { q: '取消訴訟何から考える', expectTitle: /取消訴訟の訴訟要件|訴訟要件（順番）/ },
  { q: '出訴期間はいつまで', expectTitle: /出訴期間/ },
  { q: '取消訴訟の被告', expectTitle: /被告適格/ },
  { q: '弁護士会 被告', expectTitle: /被告適格/ },
  { q: '土地区画整理組合 被告', expectTitle: /被告適格/ },
  { q: '処分等の求め 誰に', expectTitle: /処分等の求め/ },
  { q: '処分等の求め 義務付け', expectTitle: /処分等の求め|義務付け/ },
  { q: '申請型と非申請型', expectTitle: /申請型|非申請型|義務付け/ },
  { q: '工場 汚染 止めたい', expectTitle: /処分等の求め|義務付け|非申請型/ },
  { q: '令和4年 問44', expectTitle: /義務付け|処分等の求め/ },
  { q: '狸の森', expectTitle: /狸の森/ },
  { q: '安全認定 建築確認', expectTitle: /狸の森|安全認定|違法性の承継/ },
  { q: '行訴10条1項', expectTitle: /10条1項|理由なき/ },
  { q: 'パチンコ 訴えの利益', expectTitle: /狭義の訴えの利益|パチンコ/ },
  { q: '即時強制 感染症', expectTitle: /即時強制/ },
  { q: '代執行 条例', expectTitle: /代執行/ },
  { q: '地位確認 無効確認', expectTitle: /地位確認・無効確認|実質的当事者/ },
  { q: '義務付けと差止めの違い', expectTitle: /義務付け.*差止め|差止めの訴え/ },
  { q: '無効確認の補充性', expectTitle: /無効/ },
  { q: 'もんじゅ 無効確認', expectTitle: /無効/ },
  { q: '非公表 処分基準', expectTitle: /パチンコ|訴えの利益|狭義/ },
  { q: '予防訴訟 滞納', expectTitle: /予防|無効/ },
  { q: '結合して効果', expectTitle: /狸の森|違法性の承継/ },
  { q: '非申請型 原告適格', expectTitle: /非申請|処分等の求め|義務付け/ },
  { q: '所属しない 行政庁 被告', expectTitle: /被告/ },
  { q: '明らかな差し迫った危険', expectTitle: /泉佐野/ },
  { q: '庁舎と一体', expectTitle: /金沢/ },
  { q: '5号 差戻し', expectTitle: /特例法|5号|差戻/ },
  { q: 'デフレ調整 違法', expectTitle: /いのちの砦/ },
  { q: '事情判決ってなに', expectTitle: /事情判決/ },
  { q: '行服法と行訴法の違いをまとめて', expectTitle: /行政不服審査法と行政事件訴訟法/ },
  { q: '訴えの利益が消滅', expectTitle: /訴えの利益/ },
  { q: '仮の差止め', expectTitle: /差止め/ },
  { q: '実質的当事者訴訟ってなに', expectTitle: /当事者訴訟/ },
  { q: '在外邦人 確認訴訟', expectTitle: /当事者訴訟/ },
  { q: '在外邦人国民審査', expectTitle: /在外邦人国民審査|当事者訴訟/ },
  { q: '国民審査法の違法確認', expectTitle: /当事者訴訟|在外邦人国民審査/ },
  { q: '在外邦人 小選挙区', expectTitle: /当事者訴訟|在外邦人選挙/ },
  // 憲法
  { q: '二重の基準ってなに', expectTitle: /二重の基準/ },
  { q: '私人間効力ってなに', expectTitle: /私人間効力/ },
  { q: '政教分離の判断枠組み', expectTitle: /政教分離/ },
  { q: '検閲とは', expectTitle: /検閲/ },
  { q: 'マクリーン判決', expectTitle: /マクリーン|外国人/ },
  { q: 'GPS捜査は令状', expectTitle: /GPS/ },
  { q: '職業選択の自由と薬局距離', expectTitle: /職業選択|薬局/ },
  { q: '朝日訴訟と堀木訴訟', expectTitle: /生存権|朝日|堀木/ },
  { q: '司法権の限界', expectTitle: /司法権の限界/ },
  { q: '損失補償 平等原則', expectTitle: /29条3項|損失補償/ },
  { q: '正当な補償 相当な額', expectTitle: /29条3項|相当補償|正当な補償/ },
  { q: '相当補償と完全補償', expectTitle: /相当補償|完全補償|29条3項|国賠と損失補償/ },
  { q: '河川附近地', expectTitle: /河川附近地/ },
  { q: '特定の個人が受益者 収用', expectTitle: /29条3項|損失補償/ },
  // 憲法・薄い判例パック
  { q: '昭和女子大事件', expectTitle: /昭和女子大/ },
  { q: '学則の細則 論ずる余地はない', expectTitle: /昭和女子大/ },
  { q: '国立大学 学則', expectTitle: /昭和女子大/ },
  { q: '入会権 男女差別', expectTitle: /入会権/ },
  { q: '入会権 世帯主', expectTitle: /入会権/ },
  { q: '裁判官 報酬 減額', expectTitle: /報酬減額|任命・国民審査/ },
  { q: 'その他の裁判官', expectTitle: /その他の裁判官|任命・国民審査/ },
  { q: '下級裁判所 指名した者の名簿', expectTitle: /任命・国民審査|定年と任期/ },
  { q: '三菱樹脂 類推適用', expectTitle: /三菱樹脂|私人間効力/ },
  { q: '統治行動 同一の基準', expectTitle: /三菱樹脂|私人間効力/ },
  { q: '民法1条 90条 憲法', expectTitle: /三菱樹脂|私人間効力/ },
  { q: '直接適用と間接適用と類推適用', expectTitle: /直接適用|間接適用|類推適用|私人間効力/ },
  { q: '15条4項 私人間', expectTitle: /15条|投票の秘密|私人間効力/ },
  { q: '住基ネット', expectTitle: /住基|プライバシー/ },
  { q: '番号利用法 13条', expectTitle: /番号|マイナンバー|プライバシー/ },
  { q: '弁護士会 前科', expectTitle: /前科照会/ },
  { q: '早稲田 警察 名簿', expectTitle: /早稲田/ },
  { q: '石に泳ぐ魚 差止め', expectTitle: /石に泳ぐ魚/ },
  { q: '日産自動車事件', expectTitle: /日産自動車/ },
  { q: '泉佐野市民会館', expectTitle: /泉佐野/ },
  { q: '自衛官合祀', expectTitle: /合祀/ },
  { q: '全農林警職法', expectTitle: /全農林/ },
  { q: '都教組と二重のしぼり', expectTitle: /都教組|二重のしぼり/ },
  { q: '東京中郵と名古屋中郵', expectTitle: /名古屋中郵|東京中郵|争議権判例の流れ/ },
  { q: '一票の較差と事情判決', expectTitle: /投票価値|定数不均衡/ },
  { q: '酒類販売免許制', expectTitle: /酒類販売/ },
  { q: '早稲田大学名簿', expectTitle: /早稲田/ },
  { q: '在外邦人選挙権', expectTitle: /在外邦人選挙/ },
  // 憲法・判例第2波
  { q: '北方ジャーナル事件', expectTitle: /北方ジャーナル/ },
  { q: 'Google事件', expectTitle: /Google検索結果削除/ },
  { q: 'Twitter事件 削除', expectTitle: /Twitter削除/ },
  { q: '人格権 妨害排除', expectTitle: /Google検索結果削除|Twitter削除|人格権/ },
  { q: 'よど号記事抹消', expectTitle: /よど号/ },
  { q: '税関検査は検閲', expectTitle: /税関検査|検閲/ },
  { q: '博多駅事件', expectTitle: /博多駅/ },
  { q: 'レペタ事件', expectTitle: /レペタ/ },
  { q: '筆記行為の自由', expectTitle: /レペタ|筆記/ },
  { q: '悪徳の栄え事件', expectTitle: /悪徳の栄え|わいせつ/ },
  { q: '猿払 目的 関連性 合理性', expectTitle: /猿払/ },
  { q: '成田新法 集会', expectTitle: /成田新法/ },
  { q: '成田 31条 告知', expectTitle: /成田新法/ },
  { q: '徳島市公安条例 明確性', expectTitle: /徳島市公安/ },
  { q: '漠然不明確 一般人', expectTitle: /徳島市公安|明確性/ },
  { q: '交通事故 黙秘権', expectTitle: /交通事故/ },
  { q: '会期不継続 国会法', expectTitle: /会期不継続|同時活動/ },
  { q: '同時活動の原則', expectTitle: /同時活動|会期不継続/ },
  { q: '特別会と臨時会', expectTitle: /特別会|臨時会/ },
  { q: '特別会と常会 合わせて', expectTitle: /特別会|臨時会|常会/ },
  { q: '緊急集会 不逮捕', expectTitle: /緊急集会/ },
  { q: '電話傍受 個別の令状', expectTitle: /GPS|電話傍受/ },
  { q: '北方ジャーナル 事前差止め', expectTitle: /北方ジャーナル/ },
  { q: 'レペタと北方', expectTitle: /審査基準5型|レペタ|北方/ },
  { q: '公衆浴場 薬局', expectTitle: /職業選択|薬局|浴場/ },
  { q: '旅館業法 22条', expectTitle: /職業選択|旅館/ },
  { q: '保険指定拒否 22条', expectTitle: /病院開設|保険指定|職業選択/ },
  { q: '食糧管理法', expectTitle: /生存権|食糧管理|食管/ },
  { q: '解散 40日', expectTitle: /54|国会の数字|緊急集会/ },
  { q: '秘密会', expectTitle: /秘密会|国会の数字|54/ },
  { q: '尊属殺重罰規定', expectTitle: /尊属殺/ },
  { q: '京都府学連', expectTitle: /京都府学連|肖像/ },
  { q: '前科照会事件', expectTitle: /前科照会/ },
  { q: '謝罪広告は憲法違反', expectTitle: /謝罪広告/ },
  { q: '津地鎮祭と愛媛玉串料', expectTitle: /津地鎮祭|愛媛/ },
  { q: '森林法共有林', expectTitle: /森林法/ },
  { q: '旭川学テ事件', expectTitle: /旭川学テ/ },
  { q: '苫米地事件', expectTitle: /苫米地/ },
  { q: '警察予備隊訴訟', expectTitle: /警察予備隊/ },
  { q: '板まんだら事件', expectTitle: /板まんだら/ },
  { q: '大学の単位付与', expectTitle: /富山大学|部分社会|司法権の限界/ },
  { q: '解散は法律上の争訟', expectTitle: /苫米地|司法権の限界|法律上の争訟/ },
  { q: '警察予備隊 維持管理', expectTitle: /警察予備隊/ },
  { q: '百里基地訴訟', expectTitle: /百里/ },
  { q: '東大ポポロ', expectTitle: /ポポロ/ },
  { q: '川崎民商事件', expectTitle: /川崎民商/ },
  { q: '八幡製鉄の政治献金', expectTitle: /八幡/ },
  { q: '南九州税理士会', expectTitle: /南九州|税理士/ },
  { q: '検閲と事前抑制の違い', expectTitle: /検閲.*事前|北方と税関/ },
  // 憲法・深い枠組み
  { q: '目的効果基準ってなに', expectTitle: /目的効果基準/ },
  { q: '総合考慮基準', expectTitle: /総合考慮|総合衡量/ },
  { q: '目的効果と総合考慮の違い', expectTitle: /目的効果.*総合考慮|総合考慮基準/ },
  { q: '国保 84条', expectTitle: /国保|84条/ },
  { q: '予算修正 明文', expectTitle: /予算/ },
  { q: '予備費 承諾', expectTitle: /予備費|予算/ },
  { q: '公の支配に属しない', expectTitle: /89条|予備費|予算/ },
  { q: '毎会計年度 予算', expectTitle: /予算|86条/ },
  { q: 'ともに違憲審査に服する', expectTitle: /司法権の限界|砂川|違憲審査/ },
  { q: '皇室の費用', expectTitle: /皇室|予算/ },
  { q: '決算 次の年度', expectTitle: /決算|予算/ },
  { q: '大嘗祭 知事', expectTitle: /大嘗祭/ },
  { q: '町内会 神社 市有地', expectTitle: /空知太/ },
  { q: '孔子廟 20条3項', expectTitle: /孔子廟/ },
  { q: '津地鎮祭 合憲', expectTitle: /津地鎮祭/ },
  { q: '在外邦人 地位確認 違法確認', expectTitle: /在外邦人|当事者訴訟|国民審査/ },
  { q: '政見放送 法的利益', expectTitle: /政見放送/ },
  { q: '全農林 色川', expectTitle: /全農林/ },
  { q: '国務大臣 議院に出席', expectTitle: /63条|議院出席|閣僚/ },
  { q: '国務大臣 訴追', expectTitle: /75条|訴追/ },
  { q: '国会単独立法と中心立法', expectTitle: /単独|中心立法|署名/ },
  { q: '国家行政組織法11条 署名連署', expectTitle: /署名連署|単独|中心立法/ },
  { q: '省令 罰則', expectTitle: /罰則|省令|73条/ },
  { q: '他の機関が関与 法律', expectTitle: /単独|中心立法/ },
  { q: '政治的美称', expectTitle: /国会の地位|政治的美称|最高機関/ },
  { q: '形式的意義の立法', expectTitle: /国会の地位|形式的/ },
  { q: '立法行為 統治行為 司法行為', expectTitle: /司法権の限界|統治行為/ },
  { q: '規則制定権 下級裁判所', expectTitle: /規則制定/ },
  { q: '裁判官の定年', expectTitle: /定年|任期/ },
  { q: '弾劾裁判所 特別裁判所', expectTitle: /弾劾|特別裁判所/ },
  { q: '損益通算 遡及', expectTitle: /84条|遡及|損益通算/ },
  { q: '憲法に規定されているものはいくつ', expectTitle: /明文|いくつ/ },
  { q: '児童を酷使', expectTitle: /明文|児童|いくつ/ },
  { q: '院外における現行犯', expectTitle: /明文|現行犯|見分け/ },
  { q: '会期は150日', expectTitle: /明文|150|見分け/ },
  { q: '手錠 腰縄', expectTitle: /手錠|腰縄|人格/ },
  { q: '肖像権は人格権', expectTitle: /肖像|人格/ },
  { q: '船橋 伝達', expectTitle: /船橋|伝達|人格/ },
  { q: '人格権 差止め', expectTitle: /人格権|差止|Google/ },
  { q: '戸別訪問 双方向', expectTitle: /戸別訪問/ },
  { q: '伊藤正己 戸別訪問', expectTitle: /戸別訪問|伊藤/ },
  { q: '不信任決議 十日', expectTitle: /69条|不信任/ },
  { q: '総理が欠けたとき', expectTitle: /欠けた|70条/ },
  { q: '一般国務及び外交関係', expectTitle: /72条|財政状況|決算/ },
  { q: '収支決算 報告', expectTitle: /72条|決算|財政/ },
  { q: '82条2項 例外', expectTitle: /32条|82条|対審/ },
  { q: '不処分決定 無罪', expectTitle: /40条|不処分|32条/ },
  { q: '17条 白紙委任', expectTitle: /17条|郵便/ },
  { q: '津と愛媛と空知太', expectTitle: /政教分離判例|津・愛媛/ },
  { q: '政教分離の判断枠組み', expectTitle: /政教分離の答案型|判断枠組み|目的効果/ },
  { q: '規制目的二分論', expectTitle: /規制目的二分/ },
  { q: '明白性の原則ってなに', expectTitle: /明白性の原則/ },
  { q: 'LRAの基準', expectTitle: /LRA|厳格な合理性/ },
  { q: '薬局と小売市場の審査基準', expectTitle: /職業の自由・似た判例|規制目的|薬局/ },
  { q: '事前抑制の例外要件', expectTitle: /事前抑制/ },
  { q: '泉佐野の危険の基準', expectTitle: /泉佐野|差し迫った危険/ },
  { q: '平等の違憲判決を並べて', expectTitle: /平等・家族判例/ },
  { q: '再婚禁止期間は違憲', expectTitle: /再婚禁止期間違憲/ },
  { q: '再婚禁止は廃止された？', expectTitle: /再婚禁止期間違憲/ },
  { q: '無戸籍と嫡出推定', expectTitle: /再婚禁止期間違憲/ },
  { q: '司法権の限界をまとめて', expectTitle: /司法権の限界/ },
  // 国家賠償法
  { q: '国賠1条と2条の違い', expectTitle: /国賠.*1条と2条|全体像/ },
  { q: '職務行為基準説ってなに', expectTitle: /職務行為基準/ },
  { q: '公務員個人を訴えられる？', expectTitle: /公務員個人責任/ },
  { q: 'パトカー追跡事件', expectTitle: /パトカー追跡/ },
  { q: '規制権限不行使ってなに', expectTitle: /規制権限不行使/ },
  { q: '筑豊じん肺', expectTitle: /筑豊じん肺/ },
  { q: 'クロロキン訴訟', expectTitle: /クロロキン/ },
  { q: '建築確認と国賠', expectTitle: /建築確認と国賠/ },
  { q: '高知落石事件', expectTitle: /高知落石/ },
  { q: '予算不足でも国賠免責できない', expectTitle: /高知落石/ },
  { q: '直ちに賠償責任を免れない', expectTitle: /高知落石/ },
  { q: '大東水害訴訟', expectTitle: /大東水害/ },
  { q: '河川の過渡的安全性', expectTitle: /大東水害|過渡的/ },
  { q: '河川 総合考慮', expectTitle: /河川瑕疵|大東|総合考慮/ },
  { q: '一般水準 社会通念 河川', expectTitle: /河川瑕疵|大東|総合考慮/ },
  { q: '堤防工事 予想以上 水害', expectTitle: /河川瑕疵|大東|総合考慮|多摩川/ },
  { q: '予想を超える水害 瑕疵', expectTitle: /河川瑕疵|大東|総合考慮|多摩川/ },
  { q: '多摩川水害', expectTitle: /多摩川水害/ },
  { q: '赤色灯事件', expectTitle: /赤色灯/ },
  { q: '赤色灯 時間的余裕', expectTitle: /赤色灯/ },
  { q: '大阪国際空港の騒音', expectTitle: /大阪国際空港|供用関連/ },
  { q: '供用関連瑕疵', expectTitle: /大阪国際空港|供用関連/ },
  { q: '道路と河川の瑕疵の違い', expectTitle: /道路・河川の瑕疵/ },
  { q: '国賠の前に取消が必要？', expectTitle: /国賠と取消/ },
  { q: '立法不作為で国賠', expectTitle: /立法・立法不作為/ },
  { q: 'テニス審判台', expectTitle: /審判台/ },
  { q: '異常用法の注意は一般市民側', expectTitle: /審判台|防護柵|異常/ },
  { q: 'クロロキン訴訟', expectTitle: /クロロキン/ },
  { q: '医薬品の副作用 権限不行使', expectTitle: /クロロキン|規制権限/ },
  { q: '犯罪被害者 公訴提起による利益', expectTitle: /犯罪被害者|公訴提起/ },
  { q: '町議会 名誉毀損 法律上の争訟', expectTitle: /町議会|名誉|法律上の争訟/ },
  { q: '故障車放置', expectTitle: /故障車/ },
  { q: '赤色灯と故障車の違い', expectTitle: /赤色灯と故障車/ },
  { q: '改修後の河川管理', expectTitle: /河川管理の瑕疵|多摩川/ },
  { q: '線状降水帯 国賠', expectTitle: /予見後|多摩川/ },
  { q: '国賠 715', expectTitle: /715|国賠1条/ },
  { q: '補助金 国賠 責任', expectTitle: /3条|費用負担/ },
  { q: '選任監督者 費用負担者', expectTitle: /3条|費用負担/ },
  { q: '国賠のひっかけ', expectTitle: /混同防止|道路・河川/ },
  { q: '異常な用法で瑕疵', expectTitle: /審判台|防護柵|異常/ },
  { q: '指定確認検査機関 公務員', expectTitle: /指定確認検査機関|指定検査/ },
  { q: '漫然と更正', expectTitle: /更正|漫然/ },
  { q: '在外国民 国民審査', expectTitle: /国民審査|在外/ },
  { q: 'パトカー 不必要又は不相当', expectTitle: /パトカー追跡/ },
  { q: '相互保証 外国人', expectTitle: /相互保証|外国人/ },
  { q: '失火責任法 消防', expectTitle: /失火/ },
  { q: '特別法 国賠 民法', expectTitle: /特別法|国賠4条|国賠5条/ },
  { q: '求償 消滅時効', expectTitle: /求償|公務員個人/ },
  // 民法・錯誤
  { q: '錯誤ってなに', expectTitle: /錯誤/ },
  { q: '基礎事情錯誤', expectTitle: /錯誤|基礎事情/ },
  { q: '動機の錯誤', expectTitle: /錯誤|基礎事情/ },
  { q: '重過失の立証は表意者', expectTitle: /錯誤|重過失/ },
  { q: 'リニア駅 錯誤', expectTitle: /錯誤/ },
  { q: '共通錯誤', expectTitle: /錯誤|共通/ },
  { q: 'フィギュア 錯誤', expectTitle: /錯誤/ },
  { q: 'リサイクルショップ 偽物', expectTitle: /錯誤/ },
  { q: '負担付贈与 同時履行', expectTitle: /負担付贈与/ },
  { q: '連贈与契約', expectTitle: /負担付贈与/ },
  // 民法記述ヤマ（てらしぃ指定タイトル）
  { q: '過失相殺', expectTitle: /過失相殺/ },
  { q: '被害者側の過失', expectTitle: /過失相殺|被害者側/ },
  { q: '事理弁識', expectTitle: /過失相殺|事理弁識|被害者側/ },
  { q: '３歳 過失相殺', expectTitle: /過失相殺|事理弁識|被害者側/ },
  { q: '使用者責任の求償', expectTitle: /使用者責任の求償/ },
  { q: '受領遅滞', expectTitle: /受領遅滞|危険負担/ },
  { q: '受領地帯', expectTitle: /受領遅滞|危険負担/ },
  { q: '３つのできなくなる', expectTitle: /受領遅滞|危険負担/ },
  { q: '落雷 家', expectTitle: /受領遅滞|危険負担/ },
  { q: '支払義務が消滅', expectTitle: /受領遅滞|危険負担/ },
  { q: '債務引き受け', expectTitle: /債務引き受け|債務引受/ },
  { q: '免責 併存', expectTitle: /免責|併存/ },
  { q: '正当防衛と緊急避難', expectTitle: /正当防衛と緊急避難|クマ/ },
  { q: 'クマ', expectTitle: /クマ|正当防衛/ },
  { q: '犬 塀', expectTitle: /正当防衛|緊急避難|クマ|犬/ },
  { q: '所有権留保', expectTitle: /所有権留保|譲渡担保/ },
  { q: '即時取得 占有改定', expectTitle: /所有権留保|譲渡担保|即時取得|占有改定/ },
  { q: '差押え前の原因', expectTitle: /相殺|差押/ },
  { q: '509条', expectTitle: /相殺/ },
  { q: '重過失錯誤', expectTitle: /重過失錯誤|錯誤/ },
  { q: '時効の主観的起算点', expectTitle: /主観的起算|時効/ },
  { q: '時効完成後の債務の承認', expectTitle: /時効|承認/ },
  { q: '契約上の地位の移転', expectTitle: /契約上の地位|賃貸人/ },
  { q: '賃貸人の地位の移転', expectTitle: /賃貸人の地位|契約上の地位/ },
  // 憲法判例ヤマ（てらしぃ指定タイトル）
  { q: '孔子廟違憲判決', expectTitle: /孔子廟/ },
  { q: 'ツイッター事件', expectTitle: /ツイッター事件|Twitter/ },
  { q: 'いのちの砦訴訟', expectTitle: /いのちの砦/ },
  { q: 'いのちのとりで', expectTitle: /いのちの砦/ },
  { q: '性同一性障害特例法違憲判決', expectTitle: /性同一性障害特例法/ },
  { q: '旧警備業法違憲判決', expectTitle: /旧警備業法/ },
  { q: '楽天ダイレクト事件', expectTitle: /楽天ダイレクト/ },
  { q: '要指導医薬品', expectTitle: /楽天ダイレクト|要指導/ },
  { q: '誘導員 被保佐人', expectTitle: /旧警備業法/ },
  { q: '金沢市市庁舎前広場事件', expectTitle: /金沢/ },
  { q: '泉佐野市市民会館事件', expectTitle: /泉佐野/ },
  { q: '大阪市ヘイトスピーチ条令事件', expectTitle: /ヘイトスピーチ/ },
  { q: 'ヘイトスピーチ 住民訴訟', expectTitle: /ヘイトスピーチ|住民訴訟/ },
  { q: '公金支出無効確認', expectTitle: /ヘイトスピーチ|公金支出/ },
  { q: '怠る事実', expectTitle: /怠る事実|住民訴訟/ },
  { q: '住民訴訟 4号', expectTitle: /住民訴訟/ },
  { q: '住民監査請求', expectTitle: /住民監査|住民訴訟/ },
  { q: '在外邦人選挙訴訟', expectTitle: /在外邦人選挙/ },
  { q: '在外邦人国民審査', expectTitle: /在外邦人国民審査/ },
];

const all = [
  ...KISO_HOUGAKU_CHAT_TOPIC_BRIEFS,
  ...KISO_HOUGAKU_COMPARISON_BRIEFS,
  ...KISO_HOUGAKU_MOSHI_BRIEFS,
  ...GYOSEI_SORON_CHAT_BRIEFS,
  ...GYOSEI_SORON_NET_CHAT_BRIEFS,
  ...GYOSEI_TETSUZUKI_CHAT_BRIEFS,
  ...GYOSEI_FUFUKU_CHAT_BRIEFS,
  ...GYOSEI_PROC_COMPARISON_BRIEFS,
  ...GYOSEI_GYOSHO_CHAT_BRIEFS,
  ...KENPOU_CHAT_BRIEFS,
  ...KENPOU_HANREI_CHAT_BRIEFS,
  ...KENPOU_HANREI2_CHAT_BRIEFS,
  ...KENPOU_DEEP_CHAT_BRIEFS,
  ...KOKUBAI_CHAT_BRIEFS,
  ...MINPOU_CHAT_BRIEFS,
  ...NAKA_GYOSEI_YAMA_CHAT_BRIEFS,
  ...NAKA_MINPOU_YAMA_CHAT_BRIEFS,
  ...KENPOU_YAMA_CHAT_BRIEFS,
];
let fail = 0;

console.log(
  `briefs: base=${KISO_HOUGAKU_CHAT_TOPIC_BRIEFS.length} comparison=${KISO_HOUGAKU_COMPARISON_BRIEFS.length} moshi=${KISO_HOUGAKU_MOSHI_BRIEFS.length} gyosei=${GYOSEI_SORON_CHAT_BRIEFS.length} gyoseiNet=${GYOSEI_SORON_NET_CHAT_BRIEFS.length} tetsuzuki=${GYOSEI_TETSUZUKI_CHAT_BRIEFS.length} fufuku=${GYOSEI_FUFUKU_CHAT_BRIEFS.length} procCompare=${GYOSEI_PROC_COMPARISON_BRIEFS.length} gyosho=${GYOSEI_GYOSHO_CHAT_BRIEFS.length} kenpou=${KENPOU_CHAT_BRIEFS.length} kenpouHanrei=${KENPOU_HANREI_CHAT_BRIEFS.length} kenpouHanrei2=${KENPOU_HANREI2_CHAT_BRIEFS.length} kenpouDeep=${KENPOU_DEEP_CHAT_BRIEFS.length} kokubai=${KOKUBAI_CHAT_BRIEFS.length} minpou=${MINPOU_CHAT_BRIEFS.length} nakaGyoseiYama=${NAKA_GYOSEI_YAMA_CHAT_BRIEFS.length} nakaMinpouYama=${NAKA_MINPOU_YAMA_CHAT_BRIEFS.length} kenpouYama=${KENPOU_YAMA_CHAT_BRIEFS.length} total=${all.length}`
);

for (const c of cases) {
  const hits = matchBriefs(c.q, all);
  const passed = hits.some((h) => c.expectTitle.test(h.title));
  if (!passed) {
    fail += 1;
    console.log('FAIL', c.q, '→', hits.map((h) => h.title));
  } else {
    const shown = hits
      .filter((h) => c.expectTitle.test(h.title))
      .map((h) => h.title)
      .slice(0, 2)
      .join(' | ');
    console.log('OK  ', c.q, '→', shown);
  }
}

const pairCases = [
  { q: '標準処理期間ってなに', expectAlso: /努力義務の並列/ },
  { q: '公聴会 努力義務', expectAlso: /努力義務の並列/ },
  { q: '意見公募 周知', expectAlso: /努力義務の並列/ },
  { q: '努めるものとする', expectAlso: /努力義務の並列/ },
];
for (const c of pairCases) {
  const hits = matchBriefs(c.q, all);
  const passed = hits.some((h) => c.expectAlso.test(h.title));
  if (!passed) {
    fail += 1;
    console.log('FAIL pair', c.q, '→', hits.map((h) => h.title));
  } else {
    console.log('OK  pair', c.q, '→ 努力義務の並列も出る');
  }
}

if (fail > 0) {
  console.error(`\n${fail} case(s) failed`);
  process.exit(1);
}
console.log('\nAll comparison trigger checks passed.');
