/**
 * LEC公開第2回・問55 だけ、topics JSON から generated へ書き戻す。
 * 他問の learn / bonus / chat / knowledge MD は触らない。
 */
import fs from 'node:fs';

const TOPIC_ID = 'leckoukai-r2-q55-個人情報保護法の適用除外';
const SOURCE = 'LEC公開模試 第2回 問55';
const { topics } = JSON.parse(fs.readFileSync('data/moshi/lec-koukai-2026-round2-topics.json', 'utf8'));
const t = topics.find((x) => x.id === TOPIC_ID);
if (!t) throw new Error(`missing ${TOPIC_ID}`);

function parseExportedJson(path) {
  const src = fs.readFileSync(path, 'utf8');
  const i = src.indexOf('=');
  const json = src.slice(i + 1).trim().replace(/;\s*$/, '');
  return { src, data: JSON.parse(json) };
}

function writeExported(path, exportName, data) {
  const banner = '// Generated by scripts/buildMoshiTopicLearning.mjs. Edit the JSON source.\n';
  fs.writeFileSync(path, `${banner}export const ${exportName} = ${JSON.stringify(data, null, 2)};\n`);
}

const rule = String(t.rule || '').trim();
const memory = String(t.memory || '').trim();
const card = {
  text: (rule || memory).replace(/^【[^】]+】\s*/, ''),
  deepdive: `■ 結論\n\n${t.rule}\n\n■ なぜそうなる\n\n${t.deepDive}\n\n■ ひっかけ\n\n[[red:${t.trap}]]\n\n■ 暗記\n\n${t.memory}`,
  fExplain: t.aim,
  statuteRef: (t.references || []).join('、'),
  source: SOURCE,
};

const learn = parseExportedJson('src/lec_koukai_moshi_round2_learn_content.js');
const kisochi = learn.data['基礎知識'];
const li = kisochi.findIndex((c) => c.source === SOURCE);
if (li < 0) throw new Error('learn card not found');
kisochi[li] = card;
writeExported('src/lec_koukai_moshi_round2_learn_content.js', 'LEC_KOUKAI_MOSHI_ROUND2_LEARN_BY_SUBJECT', learn.data);

const bonusQ = {
  text: `【ボーナスLEC公開模試第2回・問${t.questionNumber}系】${t.practiceQuestion.prompt}`,
  choices: t.practiceQuestion.choices,
  answer: [t.practiceQuestion.answer],
  explain: t.practiceQuestion.explanation,
  choiceExplanations: t.practiceQuestion.choices.map((_, i) =>
    i === t.practiceQuestion.answer ? `正解肢。${t.practiceQuestion.explanation}` : `誤答肢。${t.trap}`,
  ),
  isBonus: true,
  wordBank: '',
  memo: `LEC公開模試第2回・${t.topic}`,
  slots: [],
};
const bonus = parseExportedJson('src/lec_koukai_moshi_round2_bonus_questions.js');
const bArr = bonus.data['基礎知識']['基礎知識'];
const bi = bArr.findIndex((q) => String(q.text || '').includes('問55系') && String(q.text || '').includes('個人情報保護法'));
if (bi < 0) throw new Error('bonus not found');
bArr[bi] = bonusQ;
writeExported('src/lec_koukai_moshi_round2_bonus_questions.js', 'LEC_KOUKAI_MOSHI_ROUND2_BONUS_QUESTIONS', bonus.data);

const mdPath = 'data/knowledge/creator/prep-school/lec-koukai-2026-round2-topics.md';
let md = fs.readFileSync(mdPath, 'utf8');
const mdStart = md.indexOf('### 問55 基礎知識：個人情報保護法の適用除外');
const mdEnd = md.indexOf('### 問56 基礎知識：');
if (mdStart < 0 || mdEnd < 0) throw new Error('md section not found');
const p = t.practiceQuestion;
const mdBlock = [
  '### 問55 基礎知識：個人情報保護法の適用除外',
  '',
  `- 出題の狙い: ${t.aim}`,
  `- 判断ルール: ${t.rule}`,
  `- ひっかけ: ${t.trap}`,
  `- 暗記: ${t.memory}`,
  `- 根拠: ${(t.references || []).join(' / ')}`,
  '',
  '#### もっと深掘る',
  '',
  t.deepDive,
  '',
  '#### 新作問題',
  '',
  p.prompt,
  '',
  ...p.choices.map((c, i) => `${i + 1}. ${c}`),
  '',
  `正解: ${p.answer + 1}`,
  '',
  p.explanation,
  '',
  '',
].join('\n');
md = md.slice(0, mdStart) + mdBlock + md.slice(mdEnd);
fs.writeFileSync(mdPath, md);

const chatPath = 'utils/chatTopicBriefsLecKoukaiRound2.ts';
let chat = fs.readFileSync(chatPath, 'utf8');
const titleNeedle = 'title: "LEC公開2・問55：個人情報保護法の適用除外"';
const tStart = chat.lastIndexOf('  {', chat.indexOf(titleNeedle));
const tEnd = chat.indexOf('\n  {', tStart + 3);
if (tStart < 0 || tEnd < 0) throw new Error('chat brief not found');

function uniq(arr) {
  return [...new Set(arr.filter(Boolean))];
}
function buildTriggers(n) {
  return uniq([
    `LEC公開２の${n}番`,
    `LEC公開2の${n}番`,
    `LEC公開２の${n}`,
    `LEC公開2の${n}`,
    `LEC公開２ ${n}番`,
    `LEC公開2 ${n}番`,
    `LEC公開模試第２回 問${n}`,
    `LEC公開模試第2回 問${n}`,
    `LEC公開模試第２回の問${n}番`,
    `LEC公開模試第2回の問${n}番`,
    `LEC公開２ 問${n}`,
    `LEC公開2 問${n}`,
    `LEC公開２の${n}番のイ`,
    `LEC公開2の${n}番のイ`,
    `LEC公開２の${n}番 そのイ`,
    `LEC公開2の${n}番 そのイ`,
    `LEC公開２の${n}番 そのア`,
    `LEC公開２ ${n}番 ストーリー`,
    `LEC公開2の${n}番 ストーリー`,
  ]).slice(0, 24);
}
const srcAns = t.sourceTrace?.sourceCorrectAnswer;
const verdicts = t.sourceTrace?.choiceVerdicts || [];
const kana = ['ア', 'イ', 'ウ', 'エ', 'オ'];
const numbered = verdicts.length >= 2 && verdicts.every((v) => /^[1-5]$/.test(String(v.id)));
const whyLines = [];
if (numbered) {
  whyLines.push('この問の記述番号は1〜5。質問の「ア〜オ」は ア＝1、イ＝2、ウ＝3、エ＝4、オ＝5 と読む。');
}
for (const v of verdicts) {
  const mark = v.ok === true ? '○' : v.ok === false ? '×' : '要確認';
  const kIdx = numbered ? Number(v.id) - 1 : kana.indexOf(String(v.id));
  const kLabel = kIdx >= 0 && kIdx < 5 ? `／${kana[kIdx]}` : '';
  whyLines.push(`- **${v.id}${kLabel}（${mark}）** ${v.why}`);
}
const iVerdict = numbered ? verdicts.find((v) => String(v.id) === '2') : verdicts.find((v) => String(v.id) === 'イ');
if (iVerdict) {
  whyLines.push(
    iVerdict.ok
      ? '「そのイはなぜ誤り？」→ イは誤りではない（○）。誤りは別の肢。'
      : '「そのイはなぜ誤り？」→ イは誤り（×）。上記の要点を参照。',
  );
}
const textLines = [
  `## LEC公開2・問${t.questionNumber}：${t.topic}`,
  '',
  '**結論（先に答え）**',
  `元模試の正解は ${srcAns}。`,
  `形式は ${t.askType || '不明'}。`,
  t.rule,
  '',
  '### 事例（要約・転載なし）',
  t.caseFacts || '登場人物なし。',
  '',
  '### 理由',
  t.deepDive,
  '',
  '### そのア〜オ／1〜5が誤り（または正しい）理由',
  ...whyLines,
  '',
  '### 具体例・ストーリー',
  `登場人物と条件は上記の要約。全文は転載しない。${t.trap}`,
  '',
  '### 具体例・切り方',
  `**Q. ひっかけは？** A. ${t.trap}`,
  `**Q. 暗記は？** A. ${t.memory}`,
  '',
  `**出典メモ** 2026 全日本行政書士公開模試 第2回（LEC）問${t.questionNumber}。第1回・LEC市販2と混ぜない。`,
].filter((line, i, arr) => !(line === '' && arr[i - 1] === ''));

function esc(s) {
  return JSON.stringify(s);
}
const briefOut = [
  '  {',
  `    triggers: ${JSON.stringify(buildTriggers(t.questionNumber), null, 6).replace(/\n/g, '\n    ')},`,
  `    title: ${esc(`LEC公開2・問${t.questionNumber}：${t.topic}`)},`,
  '    text: [',
  ...textLines.map((line) => `      ${esc(line)},`),
  "    ].join('\\n'),",
  '  },',
].join('\n');
chat = chat.slice(0, tStart) + briefOut + chat.slice(tEnd);
fs.writeFileSync(chatPath, chat);

console.log('patched Q55 only:', { learn: li, bonus: bi });
