const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '../data/pin/cases');
const OUTPUT_FILE = path.join(__dirname, '../src/pinData.ts');

// Categories to scan
const CATEGORIES = ['kenpo', 'gyosei', 'minpo'];

function parseMarkdown(content) {
    const frontmatterRegex = /^---\s*[\r\n]+([\s\S]*?)[\r\n]+---\s*[\r\n]+([\s\S]*)$/;
    const match = content.match(frontmatterRegex);

    if (!match) {
        return { metadata: {}, content: content.trim() };
    }

    const metadataRaw = match[1];
    const body = match[2].trim();

    const metadata = {};
    metadataRaw.split('\n').forEach(line => {
        const [key, ...valueParts] = line.split(':');
        if (key && valueParts.length > 0) {
            let value = valueParts.join(':').trim();
            // Handle array-like strings e.g. [a, b, c]
            if (value.startsWith('[') && value.endsWith(']')) {
                value = value.slice(1, -1).split(',').map(s => s.trim());
            }
            metadata[key.trim()] = value;
        }
    });

    return { metadata, content: body };
}

function sync() {
    console.log('Syncing Pin/Case Data...');

    if (!fs.existsSync(DATA_DIR)) {
        console.log(`Data directory not found: ${DATA_DIR}`);
        fs.writeFileSync(OUTPUT_FILE, 'export const PIN_CASES = [];');
        return;
    }

    const cases = [];

    // Iterate through each category folder
    CATEGORIES.forEach(category => {
        const categoryDir = path.join(DATA_DIR, category);

        if (!fs.existsSync(categoryDir)) {
            console.log(`Category directory missing (skipping): ${categoryDir}`);
            return;
        }

        const files = fs.readdirSync(categoryDir).filter(file => file.endsWith('.md'));

        files.forEach(file => {
            const filePath = path.join(categoryDir, file);
            const fileContent = fs.readFileSync(filePath, 'utf8');
            const { metadata, content } = parseMarkdown(fileContent);

            cases.push({
                id: metadata.id || path.basename(file, '.md'),
                category: category,
                title: metadata.title || 'Untitled Case',
                youtube: metadata.youtube || '',
                tags: metadata.tags || [],
                content: content,
            });
        });
    });

    const outputContent = `// Auto-generated by scripts/syncPinData.js
export type PinCase = {
  id: string;
  category: string;
  title: string;
  youtube: string;
  tags: string[];
  content: string; // Markdown/HTML content
};

export const PIN_CASES: PinCase[] = ${JSON.stringify(cases, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, outputContent);
    console.log(`Generated ${OUTPUT_FILE} with ${cases.length} cases.`);
}

sync();
