/** 直前期はこれ！ — 比較図ギャラリー。原文・誌面は転載していない。 */

export type ChokkiTrack =
  | '直前期パック'
  | '行政法'
  | '行訴・国賠'
  | '民法'
  | '商法'
  | '憲法'
  | '基礎';

export type ChokkiFigure = {
  id: string;
  track: ChokkiTrack;
  /** 科目画面では、パック図を該当科目にも出す */
  alsoIn?: ChokkiTrack[];
  subject: string;
  title: string;
  axis: string;
  imageKey: string;
};

export const CHOKKI_SUBJECTS: ChokkiTrack[] = [
  '直前期パック',
  '憲法',
  '行政法',
  '行訴・国賠',
  '民法',
  '商法',
  '基礎',
];

export function figuresForChokkiSubject(track: ChokkiTrack): ChokkiFigure[] {
  return CHOKKI_FIGURES.filter((item) => item.track === track || item.alsoIn?.includes(track));
}

export const CHOKKI_FIGURES: ChokkiFigure[] = [
  {
    id: 'chomon-benmei',
    track: '直前期パック',
    subject: '行政手続法',
    title: '聴聞と弁明',
    axis: '口頭・閲覧・参加人・主宰者は聴聞のみ。31条は15条3・4項と16条だけ。',
    imageKey: 'learn/tetsuzuki/chomon-benmei-hikaku',
    alsoIn: ['行政法'],
  },
  {
    id: 'genkoku-ari',
    track: '直前期パック',
    subject: '行政事件訴訟法',
    title: '原告適格・あり側',
    axis: '法律上保護された利益。生命身体の直接の危険など。',
    imageKey: 'learn/gyosho/genkoku-ari',
    alsoIn: ['行訴・国賠'],
  },
  {
    id: 'genkoku-nashi',
    track: '直前期パック',
    subject: '行政事件訴訟法',
    title: '原告適格・なし側',
    axis: '競争者・一般的公益に止まりやすいもの。',
    imageKey: 'learn/gyosho/genkoku-nashi',
    alsoIn: ['行訴・国賠'],
  },
  {
    id: 'genkoku-kikiwake',
    track: '直前期パック',
    subject: '行政事件訴訟法',
    title: '原告適格の聞き分け',
    axis: '同じ処分でも人で分かれる。適格と訴えの利益は別。',
    imageKey: 'learn/gyosho/genkoku-kikiwake',
    alsoIn: ['行訴・国賠'],
  },
  {
    id: 'kansa-3shu',
    track: '直前期パック',
    subject: '地方自治法',
    title: '事務監査・住民監査・住民訴訟',
    axis: '誰が・誰に・対象・期間・次の手続。',
    imageKey: 'learn/jichi/kansa-3shu-hikaku',
    alsoIn: ['行政法'],
  },
  {
    id: 'keizai-1947',
    track: '直前期パック',
    subject: '基礎知識',
    title: '戦後経済 1947–1968',
    axis: '所得倍増は1960年閣議決定。第2位は1968年。',
    imageKey: 'learn/kisochi/keizai-fukkou-kodo-1947-1968',
    alsoIn: ['基礎'],
  },
  {
    id: 'keizai-1971',
    track: '直前期パック',
    subject: '基礎知識',
    title: '戦後経済 1971–1987',
    axis: 'ニクソン、変動相場制、石油危機、プラザ、ルーブル。',
    imageKey: 'learn/kisochi/keizai-kawase-oil-1971-1987',
    alsoIn: ['基礎'],
  },
  {
    id: 'keizai-1989',
    track: '直前期パック',
    subject: '基礎知識',
    title: '戦後経済 1989–2019',
    axis: '消費税3→5→8→10。2019年は軽減8％。',
    imageKey: 'learn/kisochi/keizai-shouhizei-1989-2019',
    alsoIn: ['基礎'],
  },
  {
    id: 'inin-gimu',
    track: '直前期パック',
    subject: '民法',
    title: '委任規定の準用（義務側）',
    axis: '寄託は644条・645条などを準用しない。',
    imageKey: 'learn/minnpou/inin-kitaku-gimu',
    alsoIn: ['民法'],
  },
  {
    id: 'inin-kenri',
    track: '直前期パック',
    subject: '民法',
    title: '委任規定の準用（権利側）',
    axis: '寄託は646〜648、649、650条1・2項。事務管理の費用は702条。',
    imageKey: 'learn/minnpou/inin-kitaku-kenri',
    alsoIn: ['民法'],
  },
  {
    id: 'kabu-4',
    track: '直前期パック',
    subject: '商法・会社法',
    title: '株式の四変化',
    axis: '消却で減るのは発行済。資本金は当然には変わらない。',
    imageKey: 'learn/shouhou/kabushiki-4henka',
    alsoIn: ['商法'],
  },
  {
    id: 'ninyo-shobun',
    track: '直前期パック',
    subject: '行政不服審査法',
    title: '認容裁決・処分と事実上の行為',
    axis: '処分は取消し。事実上は宣言。変更は地位次第。',
    imageKey: 'learn/fufuku/ninyo-shobun-jijitsukoi',
    alsoIn: ['行政法'],
  },
  {
    id: 'ninyo-fusakui',
    track: '直前期パック',
    subject: '行政不服審査法',
    title: '認容裁決・申請拒否と不作為',
    axis: '上級は命じ、処分庁は自ら。第三者審査庁は命令できない。',
    imageKey: 'learn/fufuku/ninyo-shinsei-fusakui',
    alsoIn: ['行政法'],
  },
  {
    id: 'kokkai-4',
    track: '直前期パック',
    subject: '憲法',
    title: '常会・臨時会・特別会・緊急集会',
    axis: '形式の召集は天皇。決定は内閣。緊急集会は国会そのものではない。',
    imageKey: 'learn/kenpou/kokkai-4shu',
    alsoIn: ['憲法'],
  },
  {
    id: 'saibanin',
    track: '直前期パック',
    subject: '基礎法学',
    title: '裁判員制度',
    axis: '原則3人と6人。解釈は裁判官のみ。対象は死刑又は無期の拘禁刑。',
    imageKey: 'learn/kiso/saibanin-seido',
    alsoIn: ['基礎'],
  },

  {
    id: 'kyoka-tokkyo',
    track: '行政法',
    subject: '行政法総論',
    title: '許可・特許・命令・形成',
    axis: '一般的禁止の解除か、権利の設定かで切る。',
    imageKey: 'learn/gyosei/kyoka-tokkyo-meirei-keisei',
  },
  {
    id: 'shin-gai-rei',
    track: '行政法',
    subject: '行政法総論',
    title: '法規命令と行政規則',
    axis: '外部効果があるか。訓令・通達は原則内部。',
    imageKey: 'learn/gyosei/shin-gai-rei',
  },
  {
    id: 'torikeshi-tekkai',
    track: '行政法',
    subject: '行政法総論',
    title: '取消しと撤回',
    axis: '当初の瑕疵か、事後の事情変更か。',
    imageKey: 'learn/gyosei/shin-gai-torikeshi-tekkai',
  },
  {
    id: 'kyoseishikko',
    track: '行政法',
    subject: '行政法総論',
    title: '行政上の強制執行',
    axis: '代執行・執行罰・直接強制・強制徴収。即時強制と混ぜない。',
    imageKey: 'learn/gyosei/kyoseishikko-4plus1',
  },
  {
    id: 'koubun-life',
    track: '行政法',
    subject: '行政法総論',
    title: '公物のライフサイクル',
    axis: '公用開始から廃止まで。目的に応じた制限。',
    imageKey: 'learn/gyosei/koubun-lifecycle',
  },
  {
    id: 'koubun-hikake',
    track: '行政法',
    subject: '行政法総論',
    title: '公物のひっかけ',
    axis: '自由使用と許可使用、慣行を混ぜない。',
    imageKey: 'learn/gyosei/koubun-hikake',
  },
  {
    id: 'kounen-bessou',
    track: '行政法',
    subject: '地方自治法',
    title: '別荘水道料金',
    axis: '高くすること自体は可。過大格差の改定部分だけ無効。',
    imageKey: 'learn/gyosei/kounen-bessou-ryokin',
  },
  {
    id: 'gyosei-keiyaku',
    track: '行政法',
    subject: '行政法総論',
    title: '行政契約',
    axis: '公法契約でも契約の拘束。処分と混ぜない。',
    imageKey: 'learn/gyosei/gyosei-keiyaku',
  },
  {
    id: 'gyosei-keiyaku-zuii',
    track: '行政法',
    subject: '行政法総論',
    title: '随意契約',
    axis: '競争入札が原則。随意は例外の枠。',
    imageKey: 'learn/gyosei/gyosei-keiyaku-zuii',
  },

  {
    id: 'shobunsei-ari',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '処分性・あり側',
    axis: '公権力の行使として国民の権利義務を直接形成・確定。',
    imageKey: 'learn/gyosho/shobunsei-ari',
  },
  {
    id: 'shobunsei-nashi',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '処分性・なし側',
    axis: '内部行為・勧告・一般的規範は原則なし。',
    imageKey: 'learn/gyosho/shobunsei-nashi',
  },
  {
    id: 'shobunsei-kikiwake',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '処分性の聞き分け',
    axis: '条例制定と個別処分、勧告と拒否通知を混ぜない。',
    imageKey: 'learn/gyosho/shobunsei-kikiwake',
  },
  {
    id: 'kyoji-hoshiki',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '教示の方式',
    axis: '行審法と行訴法で誰に・いつが違う。',
    imageKey: 'learn/gyosho/kyoji-hoshiki',
  },
  {
    id: 'kokubai-1-ari',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '1条・あり側',
    axis: '公権力の行使、職務行為基準。',
    imageKey: 'learn/kokubai/1jo-ari',
  },
  {
    id: 'kokubai-1-nashi',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '1条・なし側',
    axis: '立法裁量・職務行為基準を満たす場合。',
    imageKey: 'learn/kokubai/1jo-nashi',
  },
  {
    id: 'kokubai-2-ari',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '2条・あり側',
    axis: '営造物の設置又は管理の瑕疵。',
    imageKey: 'learn/kokubai/2jo-ari',
  },
  {
    id: 'kokubai-2-nashi',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '2条・なし側',
    axis: '通常有すべき安全性を欠かない場合。',
    imageKey: 'learn/kokubai/2jo-nashi',
  },
  {
    id: 'kokubai-kikiwake',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '1条と2条の聞き分け',
    axis: '人の行為か、物の安全性か。',
    imageKey: 'learn/kokubai/kikiwake',
  },
  {
    id: 'daito-tamagawa',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '大東と多摩川',
    axis: '改修の段階で河川管理の瑕疵の見方が変わる。',
    imageKey: 'learn/kokubai/daito-vs-tamagawa',
  },
  {
    id: 'patrol-kikyaku',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: 'パトカー追跡',
    axis: '開始・継続・方法を分けて職務行為基準で見る。',
    imageKey: 'learn/kokubai/patrol-kikyaku',
  },
  {
    id: 'akairo-yoyu',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '赤色灯と故障車',
    axis: '異常用法と通常の道路管理を混ぜない。',
    imageKey: 'learn/kokubai/akairo-yoyu',
  },

  {
    id: 'seigen-saikoku',
    track: '民法',
    subject: '民法総則',
    title: '制限行為能力者と催告',
    axis: '本人催告と法定代理人催告で効果が逆。',
    imageKey: 'learn/minnpou/seigen-saikoku-hikaku',
  },
  {
    id: 'jiko-zaisan',
    track: '民法',
    subject: '債権各論',
    title: '自己の財産における注意',
    axis: '無償寄託・無償委任と善管注意を混ぜない。',
    imageKey: 'learn/minnpou/jiko-zaisan-chui',
  },
  {
    id: 'lec-q27-daisansha',
    track: '民法',
    subject: '民法総則',
    title: '詐欺・相手方と第三者',
    axis: '取消しの可否は相手方。対抗は第三者の主観。',
    imageKey: 'learn/minnpou/lec-q27-aite-daisansha',
  },
  {
    id: 'lec-q28-jutsu',
    track: '民法',
    subject: '民法総則',
    title: '詐術',
    axis: '能力者だと信じさせる詐術。他の言動とあいまって誤信。',
    imageKey: 'learn/minnpou/lec-q28-jutsu',
  },
  {
    id: 'lec-q28-saikoku',
    track: '民法',
    subject: '民法総則',
    title: '催告の期間',
    axis: '確答がなければ取り消したものとみなす場面を取り違えない。',
    imageKey: 'learn/minnpou/lec-q28-saikoku',
  },
  {
    id: 'hotei-naze',
    track: '民法',
    subject: '民法物権',
    title: '法定地上権は誰のため',
    axis: '同一所有者の土地と建物が競売で別人になるとき。',
    imageKey: 'learn/minnpou/hotei-naze-1',
  },
  {
    id: 'hotei-yes',
    track: '民法',
    subject: '民法物権',
    title: '法定地上権がつく',
    axis: '土地又は建物の抵当実行で所有者を異にするに至ったとき。',
    imageKey: 'learn/minnpou/hotei-yes-1',
  },
  {
    id: 'hotei-no',
    track: '民法',
    subject: '民法物権',
    title: '法定地上権がつかない',
    axis: 'もともと別人。土地共有の持分実行は原則つかない。',
    imageKey: 'learn/minnpou/hotei-no-1',
  },
  {
    id: 'third-177',
    track: '民法',
    subject: '民法物権',
    title: '177条の第三者',
    axis: '登記なくして対抗できない第三者の範囲。',
    imageKey: 'bukken/reference/minpo-bukken-third-party-177',
  },
  {
    id: 'sokuji',
    track: '民法',
    subject: '民法物権',
    title: '即時取得',
    axis: '占有改定では192条は動かない。',
    imageKey: 'bukken/reference/minpo-bukken-immediate-acquisition',
  },
  {
    id: 'stolen-lost',
    track: '民法',
    subject: '民法物権',
    title: '盗品・遺失物と占有回収',
    axis: '193条は2年。占有回収は侵奪から1年。詐欺は193条の対象外。',
    imageKey: 'bukken/reference/minpo-bukken-stolen-lost-recovery',
  },
  {
    id: 'delivery',
    track: '民法',
    subject: '民法物権',
    title: '引渡しの4類型',
    axis: '現実・簡易・改定・指図。対抗と即時取得で結論が分かれる。',
    imageKey: 'bukken/reference/minpo-bukken-delivery-patterns',
  },
  {
    id: 'tanpo-map',
    track: '民法',
    subject: '民法物権',
    title: '担保物権の地図',
    axis: '留置・先取特権・質・抵当。占有改定の○×。',
    imageKey: 'bukken/reference/minpo-bukken-security-real-rights-map',
  },
  {
    id: 'joshiki-ie',
    track: '民法',
    subject: '債権各論',
    title: '家が壊れたとき',
    axis: '危険負担・家賃・窓を割って逃げた、を常識で切る。',
    imageKey: 'minpou-joshiki/ie-ga-kowareta',
  },
  {
    id: 'joshiki-tanpo',
    track: '民法',
    subject: '民法物権',
    title: '占有改定の○×',
    axis: '178条・譲渡担保は○。192条・質権は×。',
    imageKey: 'minpou-joshiki/tanpo-senyu',
  },
  {
    id: 'joshiki-chintainin',
    track: '民法',
    subject: '債権各論',
    title: '賃貸人たる地位の移転',
    axis: '対抗要件ありなら承諾不要。請求には登記。',
    imageKey: 'minpou-joshiki/chintainin-chii',
  },
  {
    id: 'rinchi-sumika',
    track: '民法',
    subject: '民法物権',
    title: '隣地使用と住家',
    axis: '承諾なく隣地へ入れる場合と、住家は居住者の承諾。',
    imageKey: 'learn/minnpou/rinchi-sumika',
  },

  {
    id: 'shihainin',
    track: '商法',
    subject: '商法総則',
    title: '支配人の権限',
    axis: '営業に関する一切の裁判上・裁判外の行為。',
    imageKey: 'learn/shouhou/shihainin-kengen',
  },
  {
    id: 'mochibun-3sha',
    track: '商法',
    subject: '会社法',
    title: '持分会社の第三者',
    axis: '業務執行社員・持分の譲渡・責任の切り方。',
    imageKey: 'learn/shouhou/mochibun-3sha',
  },

  {
    id: 'chokusetsu-1',
    track: '憲法',
    subject: '憲法',
    title: '直接適用・間接適用・類推',
    axis: '私人間には直接も類推もせず、間接適用が原則。',
    imageKey: 'learn/kenpou/chokusetsu-kansetsu-ruisui',
  },
  {
    id: 'chokusetsu-2',
    track: '憲法',
    subject: '憲法',
    title: '私人間効力の続き',
    axis: '三菱樹脂と昭和女子大の聞き分け。',
    imageKey: 'learn/kenpou/chokusetsu-kansetsu-ruisui-2',
  },
  {
    id: 'sonshitsu-yogo',
    track: '憲法',
    subject: '憲法',
    title: '損失補償と擁護義務',
    axis: '29条3項と99条。国民に擁護義務はない。',
    imageKey: 'learn/kenpou/sonshitsu-hoshou-yogo',
  },
  {
    id: 'kakyu-ninmei',
    track: '憲法',
    subject: '憲法',
    title: '下級裁判所の裁判官',
    axis: '内閣が名簿で任命。最高裁と混ぜない。',
    imageKey: 'learn/kenpou/kakyu-saibankan-ninmei',
  },

  {
    id: 'kengen-kengen',
    track: '基礎',
    subject: '基礎法学',
    title: '権限と権原',
    axis: 'できる範囲を決めるのが権限。根拠を示すのが権原。',
    imageKey: 'learn/kiso/kengen-ken-gen',
  },
  {
    id: 'kengen-2',
    track: '基礎',
    subject: '基礎法学',
    title: '権限・権原の続き',
    axis: '管理者と占有者で語を分ける。',
    imageKey: 'learn/kiso/kengen-ken-gen-2',
  },
  {
    id: 'kansuru-kakaru',
    track: '基礎',
    subject: '基礎法学',
    title: '関すると係る',
    axis: '関連全般か、直接の結びつきか。',
    imageKey: 'learn/kiso/kansuru-kakaru',
  },
  {
    id: 'matawa',
    track: '基礎',
    subject: '基礎法学',
    title: '又はと若しくは',
    axis: '大きいグループに又は、小さいグループに若しくは。',
    imageKey: 'learn/kiso/matawa-moshikuwa',
  },
  {
    id: 'tadachini',
    track: '基礎',
    subject: '基礎法学',
    title: '直ちに・速やかに・遅滞なく',
    axis: '即時／できるだけ早く／正当な理由があれば遅れ得る。',
    imageKey: 'learn/kiso/tadachini',
  },
  {
    id: 'naranai',
    track: '基礎',
    subject: '基礎法学',
    title: 'ならないとできない',
    axis: '義務の向きが違う。禁止と不能を混ぜない。',
    imageKey: 'learn/kiso/naranai-dekinai',
  },
  {
    id: 'kaishaku',
    track: '基礎',
    subject: '基礎法学',
    title: '解釈の4類型',
    axis: '拡張・縮小・反対・当然。工作物に工場機械は拡張。',
    imageKey: 'learn/kiso/kaishaku-4type',
  },
  {
    id: 'kaishaku-2',
    track: '基礎',
    subject: '基礎法学',
    title: '解釈の続き',
    axis: '類推は文言の枠外。拡張と取り違えない。',
    imageKey: 'learn/kiso/kaishaku-4type-2',
  },
  {
    id: 'kenshin-saibanin',
    track: '基礎',
    subject: '基礎法学',
    title: '検察審査会と裁判員',
    axis: 'くじは一般市民。人数は11と9で切る。',
    imageKey: 'learn/kiso/kenshin-vs-saibanin',
  },
  {
    id: 'horei-keishiki',
    track: '基礎',
    subject: '基礎法学',
    title: '法令の形式',
    axis: '法律・命令・規則。公布と施行を混ぜない。',
    imageKey: 'learn/kiso/horei-keishiki',
  },
  {
    id: 'kanpo',
    track: '基礎',
    subject: '基礎法学',
    title: '官報と告示',
    axis: '公布の方法。周知期間の起算。',
    imageKey: 'learn/kiso/kanpo-kokuji',
  },
  {
    id: 'kokin-ouhou',
    track: '基礎',
    subject: '基礎法学',
    title: '拘禁刑の目的',
    axis: '懲役・禁錮の用語は使わない。改善更生と再犯防止。',
    imageKey: 'learn/kiso/kokin-ouhou-mokuteki',
  },
  {
    id: 'shinakereba',
    track: '基礎',
    subject: '基礎法学',
    title: 'しなければならないとみなす',
    axis: '義務と擬制。努めるものとする（努力）と混ぜない。',
    imageKey: 'learn/kiso/shinakereba-monotosuru',
  },
  {
    id: 'keiju',
    track: '基礎',
    subject: '基礎法学',
    title: '刑の軽重の年表',
    axis: '刑法6条。変更後の軽い刑。',
    imageKey: 'learn/kiso/keiju-timeline',
  },
  {
    id: 'kojin-teigi',
    track: '基礎',
    subject: '個人情報保護法',
    title: '個人情報の定義',
    axis: '生存する個人。識別可能性。',
    imageKey: 'learn/kojinjoho/teigi',
  },
  {
    id: 'juki-vs-koseki',
    track: '基礎',
    subject: '戸籍・住基',
    title: '戸籍と住民票',
    axis: '身分の公証と住所の公証。単位が違う。',
    imageKey: 'learn/juki/vs-koseki',
  },
  {
    id: 'gyoseishoshi-dare',
    track: '基礎',
    subject: '行政書士法',
    title: '行政書士は誰が',
    axis: '他人の依頼を受け報酬を得て書類作成。',
    imageKey: 'learn/gyoseishoshi/dare-ga',
  },

  {
    id: 'r8-shimei',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '行政書士法',
    title: '使命と職責・デジタル',
    axis: '1条は使命。デジタルは努力義務。施行は令和8年1月1日。',
    imageKey: 'learn/gyoseishoshi/r8-shimei',
  },
  {
    id: 'r8-tokutei',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '行政書士法',
    title: '特定行政書士・業務制限・両罰',
    axis: '作成することができる書類。名目を問わず報酬。両罰は23条の3。',
    imageKey: 'learn/gyoseishoshi/r8-tokutei-ryobatsu',
  },
  {
    id: 'kyodo-shinken',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '家族法',
    title: '離婚後の親権',
    axis: '双方又は一方。子の利益。害悪のおそれは一方を定めなければならない。',
    imageKey: 'learn/minnpou/kyodo-shinken',
  },
  {
    id: 'yoiku-koryu',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '家族法',
    title: '養育費と親子交流',
    axis: '766条で監護・交流・費用。定めなしの協議離婚は766条の3。',
    imageKey: 'learn/minnpou/yoiku-koryu',
  },
  {
    id: 'shinsa-shobun-riyu',
    track: '直前期パック',
    alsoIn: ['行政法'],
    subject: '行政手続法',
    title: '審査基準・処分基準・理由提示',
    axis: '5条は定めと公表が義務。12条は努力。14条は理由を示す。',
    imageKey: 'learn/tetsuzuki/shinsa-shobun-riyu',
  },
  {
    id: 'daishikko-tetsuzuki',
    track: '直前期パック',
    alsoIn: ['行政法'],
    subject: '行政法総論',
    title: '代執行の対象と手順',
    axis: '代替的作為。戒告→令書→実施→費用。第三者可。',
    imageKey: 'learn/gyosei/daishikko-tetsuzuki',
  },
  {
    id: 'gimetsuke-shinsei',
    track: '直前期パック',
    alsoIn: ['行訴・国賠'],
    subject: '行政事件訴訟法',
    title: '申請型と非申請型の義務付け',
    axis: '申請型に重大な損害は要らない。非申請型は重大な損害と補充性。',
    imageKey: 'learn/gyosho/gimetsuke-shinsei',
  },
  {
    id: 'kari-kyusai-songai',
    track: '直前期パック',
    alsoIn: ['行訴・国賠'],
    subject: '行政事件訴訟法',
    title: '重大な損害と償うことのできない損害',
    axis: '執行停止・差止めは重大。仮の義務付け・仮の差止めは償えない。',
    imageKey: 'learn/gyosho/kari-kyusai-songai',
  },
  {
    id: 'sonshitsu-hoshou',
    track: '直前期パック',
    alsoIn: ['行訴・国賠'],
    subject: '国家賠償法',
    title: '国賠と損失補償',
    axis: '1条は人。2条は物。補償は適法な特別の犠牲。',
    imageKey: 'learn/kokubai/sonshitsu-hoshou',
  },
  {
    id: 'saigai-yoken',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '債権総論',
    title: '詐害行為取消の要件',
    axis: '被保全は行為前の原因。財産権。受益者善意なら不可。',
    imageKey: 'learn/minnpou/saigai-yoken',
  },
  {
    id: 'saigai-jiko',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '債権総論',
    title: '転得者と金銭の自己請求',
    axis: '転得ごとの悪意。金銭・動産は自己へ求め得る。',
    imageKey: 'learn/minnpou/saigai-jiko',
  },
  {
    id: 'jiho-sosai',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '債権総論',
    title: '時効と相殺',
    axis: '508条は完成前の相殺適状。511条は差押え後取得が原則不可。',
    imageKey: 'learn/minnpou/jiho-sosai',
  },
  {
    id: 'ketsugi-futsukabetsu',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '普通決議と特別決議',
    axis: '定足は過半数出席。可決は過半数か3分の2か。',
    imageKey: 'learn/shouhou/ketsugi-futsukabetsu',
  },
  {
    id: 'setsuritsu-hokki',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '発起設立と募集設立',
    axis: '全部引受けは発起。募るときは創立総会。',
    imageKey: 'learn/shouhou/setsuritsu-hokki-boshu',
  },
  {
    id: 'fuuhyo-bangou',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '戸籍・住基',
    title: '住民票・附票・番号',
    axis: '附票は本籍地。法人番号は法人。公的個人認証は外国人住民も。',
    imageKey: 'learn/juki/fuuhyo-bangou',
  },
  {
    id: 'kamei-tokumei',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '個人情報保護法',
    title: '仮名加工と匿名加工',
    axis: '仮名は照合。匿名は復元できない。履歴はすぐ匿名にしない。',
    imageKey: 'learn/kojinjoho/kamei-tokumei',
  },
  {
    id: 'kenetsu-jizen',
    track: '直前期パック',
    alsoIn: ['憲法'],
    subject: '憲法',
    title: '検閲と事前抑制',
    axis: '検閲は行政の事前禁止。司法の差止めは検閲そのものではない。',
    imageKey: 'learn/kenpou/kenetsu-jizen',
  },
  {
    id: 'kokin-sagyo',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '基礎法学',
    title: '拘禁刑と作業',
    axis: '懲役・禁錮の一本化。作業は必要に応じ行い得る。',
    imageKey: 'learn/kiso/kokin-sagyo',
  },
  {
    id: 'utae-no-rieki',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '訴えの利益',
    axis: '判決時の実益。満了でも直ちに欠けるわけではない。',
    imageKey: 'learn/gyosho/utae-no-rieki',
  },
  {
    id: 'teito-bougai',
    track: '民法',
    subject: '民法物権',
    title: '抵当権の妨害排除',
    axis: '交換価値を害する占有。物上代位は払渡し前の差押え。',
    imageKey: 'learn/minnpou/teito-bougai',
  },
  {
    id: 'shido-nin-i',
    track: '行政法',
    subject: '行政手続法',
    title: '行政指導の任意と求め',
    axis: '32条は任意。中止は相手方。処分等の求めは何人も。',
    imageKey: 'learn/gyosei/shido-nin-i-chushi',
  },
  {
    id: 'ko-no-shisetsu',
    track: '行政法',
    subject: '地方自治法',
    title: '公の施設の利用拒否',
    axis: '正当な理由なく拒めない。不当な差別的取扱い禁止。',
    imageKey: 'learn/jichi/ko-no-shisetsu',
  },
  {
    id: 'shinri-ryuho',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '民法総則',
    title: '心裡留保と虚偽表示',
    axis: '心裡留保は原則有効。無効組は善意の第三者に対抗できない。',
    imageKey: 'learn/minnpou/shinri-ryuho',
  },
  {
    id: 'shihonkin',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '資本金と資本準備金',
    axis: '2分の1以上を資本金。消却では減らない。全額資本金化は異議なし。',
    imageKey: 'learn/shouhou/shihonkin',
  },
  {
    id: 'kujou-shori',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '個人情報保護法',
    title: '苦情処理の義務と努力義務',
    axis: '認定団体は求めなければならない。事業者・地方・行政機関の長等は努力義務。',
    imageKey: 'learn/kojinjoho/kujou-shori',
  },
  {
    id: 'kuni-no-kanyo',
    track: '直前期パック',
    alsoIn: ['行政法'],
    subject: '地方自治法',
    title: '国又は都道府県の関与',
    axis: '法律又は政令によらなければ、関与を受け、又は要しない。',
    imageKey: 'learn/jichi/kuni-no-kanyo',
  },
  {
    id: 'seikyu-saki',
    track: '直前期パック',
    alsoIn: ['行政法'],
    subject: '行政不服審査法',
    title: '審査請求先',
    axis: '4条1号から4号。庁の長は内閣府設置法又は国行組の庁の長。',
    imageKey: 'learn/fufuku/seikyu-saki',
  },
  {
    id: 'sentoku',
    track: '基礎',
    subject: '基礎法学',
    title: '先特後普',
    axis: '先にできた特別法は、後の一般法に優先する。',
    imageKey: 'learn/kiso/sentoku',
  },
  {
    id: 'keihou6',
    track: '基礎',
    subject: '基礎法学',
    title: '刑法6条',
    axis: '刑の変更があったときは、軽い方を適用する。',
    imageKey: 'learn/kiso/keihou6',
  },
  {
    id: 'adr-4',
    track: '基礎',
    subject: '基礎法学',
    title: 'ADRの4類型',
    axis: '調停・和解・仲裁・あっせんを聞き分ける。',
    imageKey: 'learn/kiso/adr-4',
  },
  {
    id: 'hougen',
    track: '基礎',
    subject: '基礎法学',
    title: '法源',
    axis: '制定法が先。判例・条理・学説は後。',
    imageKey: 'learn/kiso/hougen',
  },
  {
    id: 'shinsakai-role',
    track: '行政法',
    subject: '行政不服審査法',
    title: '行政不服審査会',
    axis: '答申は審査会。裁決は審査庁。',
    imageKey: 'fufuku/shinsakai-role',
  },
  {
    id: 'saiketsu-henko-46',
    track: '行政法',
    subject: '行政不服審査法',
    title: '46条の変更権',
    axis: '変更できるのは処分庁又は上級。第三者審査庁は取消しだけ。',
    imageKey: 'fufuku/saiketsu-henko-46',
  },
];
