/** 直前期はこれ！ — 比較図ギャラリー。原文・誌面は転載していない。 */

export type ChokkiTrack =
  | '直前期パック'
  | '行政法'
  | '行訴・国賠'
  | '民法'
  | '商法'
  | '憲法'
  | '基礎';

export type ChokkiFigure = {
  id: string;
  track: ChokkiTrack;
  /** 科目画面では、パック図を該当科目にも出す */
  alsoIn?: ChokkiTrack[];
  subject: string;
  title: string;
  axis: string;
  imageKey: string;
};

export const CHOKKI_SUBJECTS: ChokkiTrack[] = [
  '直前期パック',
  '憲法',
  '行政法',
  '行訴・国賠',
  '民法',
  '商法',
  '基礎',
];

export function figuresForChokkiSubject(track: ChokkiTrack): ChokkiFigure[] {
  return CHOKKI_FIGURES.filter((item) => item.track === track || item.alsoIn?.includes(track));
}

export const CHOKKI_FIGURES: ChokkiFigure[] = [
  {
    id: 'chomon-benmei',
    track: '直前期パック',
    subject: '行政手続法',
    title: '聴聞と弁明',
    axis: '口頭・閲覧・参加人・主宰者は聴聞のみ。31条は15条3・4項と16条だけ。',
    imageKey: 'learn/tetsuzuki/chomon-benmei-hikaku',
    alsoIn: ['行政法'],
  },
  {
    id: 'genkoku-ari',
    track: '直前期パック',
    subject: '行政事件訴訟法',
    title: '原告適格・あり側',
    axis: '法律上保護された利益。生命・身体の直接の危険など。',
    imageKey: 'learn/gyosho/genkoku-ari-v2',
    alsoIn: ['行訴・国賠'],
  },
  {
    id: 'genkoku-nashi',
    track: '直前期パック',
    subject: '行政事件訴訟法',
    title: '原告適格・なし側',
    axis: '競争者・一般的公益に止まりやすいもの。',
    imageKey: 'learn/gyosho/genkoku-nashi',
    alsoIn: ['行訴・国賠'],
  },
  {
    id: 'genkoku-kikiwake',
    track: '直前期パック',
    subject: '行政事件訴訟法',
    title: '原告適格の聞き分け',
    axis: '同じ処分でも人で分かれる。適格と訴えの利益は別。',
    imageKey: 'learn/gyosho/genkoku-kikiwake',
    alsoIn: ['行訴・国賠'],
  },
  {
    id: 'kansa-3shu',
    track: '直前期パック',
    subject: '地方自治法',
    title: '事務監査・住民監査・住民訴訟',
    axis: '誰が・誰に・対象・期間・次の手続。',
    imageKey: 'learn/jichi/kansa-3shu-hikaku',
    alsoIn: ['行政法'],
  },
  {
    id: 'keizai-1947',
    track: '直前期パック',
    subject: '基礎知識',
    title: '戦後経済 1947–1968',
    axis: '所得倍増は1960年閣議決定。第2位は1968年。',
    imageKey: 'learn/kisochi/keizai-fukkou-kodo-1947-1968',
    alsoIn: ['基礎'],
  },
  {
    id: 'keizai-1971',
    track: '直前期パック',
    subject: '基礎知識',
    title: '戦後経済 1971–1987',
    axis: 'ニクソン、変動相場制、石油危機、プラザ、ルーブル。',
    imageKey: 'learn/kisochi/keizai-kawase-oil-1971-1987',
    alsoIn: ['基礎'],
  },
  {
    id: 'keizai-1989',
    track: '直前期パック',
    subject: '基礎知識',
    title: '戦後経済 1989–2019',
    axis: '消費税3→5→8→10。2019年は軽減8％。',
    imageKey: 'learn/kisochi/keizai-shouhizei-1989-2019',
    alsoIn: ['基礎'],
  },
  {
    id: 'inin-gimu',
    track: '直前期パック',
    subject: '民法',
    title: '委任規定の準用（義務側）',
    axis: '寄託は644条・645条などを準用しない。',
    imageKey: 'learn/minnpou/inin-kitaku-gimu',
    alsoIn: ['民法'],
  },
  {
    id: 'inin-kenri',
    track: '直前期パック',
    subject: '民法',
    title: '委任規定の準用（権利側）',
    axis: '寄託は646〜648、649、650条1・2項。事務管理の費用は702条。',
    imageKey: 'learn/minnpou/inin-kitaku-kenri',
    alsoIn: ['民法'],
  },
  {
    id: 'kabu-4',
    track: '直前期パック',
    subject: '商法・会社法',
    title: '株式の四変化',
    axis: '消却で減るのは発行済。資本金は当然には変わらない。',
    imageKey: 'learn/shouhou/kabushiki-4henka',
    alsoIn: ['商法'],
  },
  {
    id: 'ninyo-shobun',
    track: '直前期パック',
    subject: '行政不服審査法',
    title: '認容裁決・処分と事実上の行為',
    axis: '処分は取消し。事実上は宣言。変更は地位次第。',
    imageKey: 'learn/fufuku/ninyo-shobun-jijitsukoi',
    alsoIn: ['行政法'],
  },
  {
    id: 'ninyo-fusakui',
    track: '直前期パック',
    subject: '行政不服審査法',
    title: '認容裁決・申請拒否と不作為',
    axis: '上級は命じ、処分庁は自ら。第三者審査庁は命令できない。',
    imageKey: 'learn/fufuku/ninyo-shinsei-fusakui',
    alsoIn: ['行政法'],
  },
  {
    id: 'kokkai-4',
    track: '直前期パック',
    subject: '憲法',
    title: '常会・臨時会・特別会・緊急集会',
    axis: '形式の召集は天皇。決定は内閣。緊急集会は国会そのものではない。',
    imageKey: 'learn/kenpou/kokkai-4shu',
    alsoIn: ['憲法'],
  },
  {
    id: 'kokkai-giin-kenno',
    track: '直前期パック',
    subject: '憲法',
    title: '国会の権能／議院の権能',
    axis: '弾劾裁判所の設置は国会。国政調査は各議院。',
    imageKey: 'learn/kenpo/kokkai-giin-kenno',
    alsoIn: ['憲法'],
  },
  {
    id: 'saibanin',
    track: '直前期パック',
    subject: '基礎法学',
    title: '裁判員制度',
    axis: '原則3人と6人。解釈は裁判官のみ。対象は死刑又は無期の拘禁刑。',
    imageKey: 'learn/kiso/saibanin-seido',
    alsoIn: ['基礎'],
  },

  {
    id: 'kyoka-tokkyo',
    track: '行政法',
    subject: '行政法総論',
    title: '許可・特許・命令・形成',
    axis: '一般的禁止の解除か、権利の設定かで切る。',
    imageKey: 'learn/gyosei/kyoka-tokkyo-meirei-keisei',
  },
  {
    id: 'shin-gai-rei',
    track: '行政法',
    subject: '行政法総論',
    title: '法規命令と行政規則',
    axis: '外部効果があるか。訓令・通達は原則内部。',
    imageKey: 'learn/gyosei/shin-gai-rei',
  },
  {
    id: 'torikeshi-tekkai',
    track: '行政法',
    subject: '行政法総論',
    title: '取消しと撤回',
    axis: '当初の瑕疵か、事後の事情変更か。',
    imageKey: 'learn/gyosei/shin-gai-torikeshi-tekkai',
  },
  {
    id: 'kyoseishikko',
    track: '行政法',
    subject: '行政法総論',
    title: '行政上の強制執行',
    axis: '代執行・執行罰・直接強制・強制徴収。即時強制と混ぜない。',
    imageKey: 'learn/gyosei/kyoseishikko-4plus1',
  },
  {
    id: 'koubun-life',
    track: '行政法',
    subject: '行政法総論',
    title: '公物のライフサイクル',
    axis: '公用開始から廃止まで。目的に応じた制限。',
    imageKey: 'learn/gyosei/koubun-lifecycle',
  },
  {
    id: 'koubun-hikake',
    track: '行政法',
    subject: '行政法総論',
    title: '公物のひっかけ',
    axis: '自由使用と許可使用、慣行を混ぜない。',
    imageKey: 'learn/gyosei/koubun-hikake',
  },
  {
    id: 'kounen-bessou',
    track: '行政法',
    subject: '地方自治法',
    title: '別荘水道料金',
    axis: '高くすること自体は可。過大格差の改定部分だけ無効。',
    imageKey: 'learn/gyosei/kounen-bessou-ryokin',
  },
  {
    id: 'gyosei-keiyaku',
    track: '行政法',
    subject: '行政法総論',
    title: '行政契約',
    axis: '公法契約でも契約の拘束。処分と混ぜない。',
    imageKey: 'learn/gyosei/gyosei-keiyaku',
  },
  {
    id: 'gyosei-keiyaku-zuii',
    track: '行政法',
    subject: '行政法総論',
    title: '随意契約',
    axis: '競争入札が原則。随意は例外の枠。',
    imageKey: 'learn/gyosei/gyosei-keiyaku-zuii',
  },

  {
    id: 'shobunsei-ari',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '処分性・あり側',
    axis: '公権力の行使として国民の権利義務を直接形成・確定。',
    imageKey: 'learn/gyosho/shobunsei-ari',
  },
  {
    id: 'shobunsei-nashi',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '処分性・なし側',
    axis: '内部行為・勧告・一般的規範は原則なし。',
    imageKey: 'learn/gyosho/shobunsei-nashi',
  },
  {
    id: 'shobunsei-kikiwake',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '処分性の聞き分け',
    axis: '条例制定と個別処分、勧告と拒否通知を混ぜない。',
    imageKey: 'learn/gyosho/shobunsei-kikiwake',
  },
  {
    id: 'kyoji-hoshiki',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '教示の方式',
    axis: '行審法と行訴法で誰に・いつが違う。',
    imageKey: 'learn/gyosho/kyoji-hoshiki',
  },
  {
    id: 'kokubai-1-ari',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '1条・あり側',
    axis: '公権力の行使、職務行為基準。',
    imageKey: 'learn/kokubai/1jo-ari',
  },
  {
    id: 'kokubai-1-nashi',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '1条・なし側',
    axis: '立法裁量・職務行為基準を満たす場合。',
    imageKey: 'learn/kokubai/1jo-nashi',
  },
  {
    id: 'kokubai-2-ari',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '2条・あり側',
    axis: '営造物の設置又は管理の瑕疵。',
    imageKey: 'learn/kokubai/2jo-ari',
  },
  {
    id: 'kokubai-2-nashi',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '2条・なし側',
    axis: '通常有すべき安全性を欠かない場合。',
    imageKey: 'learn/kokubai/2jo-nashi',
  },
  {
    id: 'kokubai-kikiwake',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '1条と2条の聞き分け',
    axis: '人の行為か、物の安全性か。',
    imageKey: 'learn/kokubai/kikiwake',
  },
  {
    id: 'daito-tamagawa',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '大東と多摩川',
    axis: '改修の段階で河川管理の瑕疵の見方が変わる。',
    imageKey: 'learn/kokubai/daito-vs-tamagawa',
  },
  {
    id: 'patrol-kikyaku',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: 'パトカー追跡',
    axis: '開始・継続・方法を分けて職務行為基準で見る。',
    imageKey: 'learn/kokubai/patrol-kikyaku',
  },
  {
    id: 'akairo-yoyu',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '赤色灯と故障車',
    axis: '異常用法と通常の道路管理を混ぜない。',
    imageKey: 'learn/kokubai/akairo-yoyu',
  },

  {
    id: 'seigen-saikoku',
    track: '民法',
    subject: '民法総則',
    title: '制限行為能力者と催告',
    axis: '本人催告と法定代理人催告で効果が逆。',
    imageKey: 'learn/minnpou/seigen-saikoku-hikaku',
  },
  {
    id: 'junko-rock-602',
    track: '民法',
    subject: '民法総則',
    title: '短期賃貸借の期間（純子さんロック）',
    axis: '602条。山林10・土地5・建物3・動産6か月。抵当の旧395と混ぜない。',
    imageKey: 'learn/minnpou/602-junko-rock',
  },
  {
    id: 'jiko-zaisan',
    track: '民法',
    subject: '債権各論',
    title: '自己の財産における注意',
    axis: '無償寄託・無償委任と善管注意を混ぜない。',
    imageKey: 'learn/minnpou/jiko-zaisan-chui',
  },
  {
    id: 'zenkan-chui',
    track: '民法',
    subject: '債権各論',
    title: '善管注意義務',
    axis: '400条は社会通念に照らして定まる善管。商人の営業内寄託は商法595条。',
    imageKey: 'learn/minnpou/zenkan-chui',
  },
  {
    id: 'jukashitsu',
    track: '民法',
    subject: '債権総論',
    title: '重過失要件',
    axis: '誰が知り又は重過失か。3項は履行拒絶。の5と505は特約対抗。566は売主。',
    imageKey: 'learn/minnpou/jukashitsu',
  },
  {
    id: 'lec-q27-daisansha',
    track: '民法',
    subject: '民法総則',
    title: '詐欺・相手方と第三者',
    axis: '取消しの可否は相手方。対抗は第三者の主観。',
    imageKey: 'learn/minnpou/lec-q27-aite-daisansha',
  },
  {
    id: 'lec-q28-jutsu',
    track: '民法',
    subject: '民法総則',
    title: '詐術',
    axis: '能力者だと信じさせる詐術。他の言動とあいまって誤信。',
    imageKey: 'learn/minnpou/lec-q28-jutsu',
  },
  {
    id: 'lec-q28-saikoku',
    track: '民法',
    subject: '民法総則',
    title: '催告の期間',
    axis: '確答がなければ取り消したものとみなす場面を取り違えない。',
    imageKey: 'learn/minnpou/lec-q28-saikoku',
  },
  {
    id: 'hotei-naze',
    track: '民法',
    subject: '民法物権',
    title: '法定地上権は誰のため',
    axis: '同一所有者の土地と建物が競売で別人になるとき。',
    imageKey: 'learn/minnpou/hotei-naze-1',
  },
  {
    id: 'hotei-yes',
    track: '民法',
    subject: '民法物権',
    title: '法定地上権がつく',
    axis: '土地又は建物の抵当実行で所有者を異にするに至ったとき。',
    imageKey: 'learn/minnpou/hotei-yes-1',
  },
  {
    id: 'hotei-no',
    track: '民法',
    subject: '民法物権',
    title: '法定地上権がつかない',
    axis: 'もともと別人。土地共有の持分実行は原則つかない。',
    imageKey: 'learn/minnpou/hotei-no-1',
  },
  {
    id: 'third-177',
    track: '民法',
    subject: '民法物権',
    title: '177条の第三者',
    axis: '登記なくして対抗できない第三者の範囲。',
    imageKey: 'bukken/reference/minpo-bukken-third-party-177',
  },
  {
    id: 'bukken-seikyu-q29',
    track: '民法',
    subject: '民法物権',
    title: '建物収去・土地明渡請求',
    axis: '名義だけの者と、所有後に名義を残した者を区別する。',
    imageKey: 'learn/minpo/bukken-seikyu-q29',
    alsoIn: ['民法物権'],
  },
  {
    id: 'bukken-seikyu-q29-2',
    track: '民法',
    subject: '民法物権',
    title: '物権的請求権を解く判断軸',
    axis: '206条は所有権の内容。平6.2.8は自らの意思による登記。',
    imageKey: 'learn/minpo/bukken-seikyu-q29-2',
    alsoIn: ['民法物権'],
  },
  {
    id: 'sakidori-kihon',
    track: '民法',
    subject: '民法物権',
    title: '先取特権｜優先弁済の範囲と限界',
    axis: '優先弁済の制限は、債権の消滅を意味しない。',
    imageKey: 'learn/minpo/sakidori-kihon',
    alsoIn: ['民法物権'],
  },
  {
    id: 'sakidori-q30',
    track: '民法',
    subject: '民法物権',
    title: '先取特権｜金額・対象財産・第三者',
    axis: '何の債権か、いくらか、どの財産か、第三者への移転かをこの順で見る。',
    imageKey: 'learn/minpo/sakidori-q30',
    alsoIn: ['民法物権'],
  },
  {
    id: 'kaijo-542',
    track: '民法',
    subject: '債権各論',
    title: '催告によらない解除（542条）',
    axis: '催告なし。1項は契約の解除。2項は契約の一部の解除。',
    imageKey: 'learn/minpo/kaijo-542',
    alsoIn: ['債権総論'],
  },
  {
    id: 'sakidori-tenbai-butsujodaii',
    track: '民法',
    subject: '民法物権',
    title: '動産売買の先取特権と物上代位',
    axis: '転売代金債権に物上代位できる。ただし、払渡し前の差押えが必要。',
    imageKey: 'learn/minpo/sakidori-tenbai-butsujodaii',
    alsoIn: ['民法物権'],
  },
  {
    id: 'sakidori-tenbai-joto',
    track: '民法',
    subject: '民法物権',
    title: '転売代金債権の譲渡と先取特権',
    axis: '債権譲渡の第三者対抗要件具備後は、差押えによる物上代位はできない。',
    imageKey: 'learn/minpo/sakidori-tenbai-joto',
    alsoIn: ['民法物権'],
  },
  {
    id: 'ryuchi-seiritsu-shiyou',
    track: '民法',
    subject: '民法物権',
    title: '留置権の成立と使用制限',
    axis: '298条1項は善管注意。2項は承諾（保存に必要な使用は可）。3項は消滅請求。',
    imageKey: 'learn/minpo/ryuchi-seiritsu-shiyou',
    alsoIn: ['民法物権'],
  },
  {
    id: 'jichitai-keiyaku-q24',
    track: '行政法',
    subject: '地方自治法',
    title: '自治体の契約｜一般競争が原則',
    axis: '指名・随意・せり売りは政令所定の場合に限る。',
    imageKey: 'learn/gyoseihou/jichitai-keiyaku-q24',
  },
  {
    id: 'muken-dairi-sozoku-q28',
    track: '民法',
    subject: '民法総則',
    title: '無権代理と相続｜向き・人数・拒絶の時期',
    axis: '共同相続では自己の持分だけ当然有効にはならない。',
    imageKey: 'learn/minpo/muken-dairi-sozoku-q28',
  },
  {
    id: 'fudosan-chintai-sakidori-q30-u',
    track: '民法',
    subject: '民法物権',
    title: '不動産賃貸の先取特権｜対象は賃借人の動産',
    axis: '制度名の不動産と、担保の対象物を混同しない。',
    imageKey: 'learn/minpo/fudosan-chintai-sakidori-q30-u',
    alsoIn: ['民法物権'],
  },
  {
    id: 'shiin-zoyo-izo-q35',
    track: '民法',
    subject: '家族法',
    title: '死因贈与と遺贈｜契約か、遺言か',
    axis: '承諾と方式が分かれ、負担は両方に付けられる。',
    imageKey: 'learn/minpo/shiin-zoyo-izo-q35',
  },
  {
    id: 'kyodo-hosho-kyusho-q31',
    track: '民法',
    subject: '債権総論',
    title: '保証人同士の求償｜負担部分を超えてから',
    axis: '連帯保証と連帯債務では、求償の開始条件が違う。',
    imageKey: 'learn/minpo/kyodo-hosho-kyusho-q31',
  },
  {
    id: 'taxi-kyusho-2houkou',
    track: '民法',
    subject: '債権各論',
    title: '使用者の求償｜相手で基準が違う',
    axis: '共同不法行為者は過失割合。被用者は信義則上相当の限度。',
    imageKey: 'learn/minpo/taxi-kyusho-2houkou',
  },
  {
    id: 'sokuji',
    track: '民法',
    subject: '民法物権',
    title: '即時取得',
    axis: '占有改定では192条は動かない。',
    imageKey: 'bukken/reference/minpo-bukken-immediate-acquisition',
  },
  {
    id: 'stolen-lost',
    track: '民法',
    subject: '民法物権',
    title: '盗品・遺失物と占有回収',
    axis: '193条は2年。占有回収は侵奪から1年。詐欺は193条の対象外。',
    imageKey: 'bukken/reference/minpo-bukken-stolen-lost-recovery',
  },
  {
    id: 'delivery',
    track: '民法',
    subject: '民法物権',
    title: '引渡しの4類型',
    axis: '現実・簡易・改定・指図。対抗と即時取得で結論が分かれる。',
    imageKey: 'bukken/reference/minpo-bukken-delivery-patterns',
  },
  {
    id: 'tanpo-map',
    track: '民法',
    subject: '民法物権',
    title: '担保物権の地図',
    axis: '留置・先取特権・質・抵当。占有改定の○×。',
    imageKey: 'bukken/reference/minpo-bukken-security-real-rights-map',
  },
  {
    id: 'joshiki-ie',
    track: '民法',
    subject: '債権各論',
    title: '家が壊れたとき',
    axis: '危険負担・家賃・窓を割って逃げた、を常識で切る。',
    imageKey: 'minpou-joshiki/ie-ga-kowareta',
  },
  {
    id: 'joshiki-tanpo',
    track: '民法',
    subject: '民法物権',
    title: '占有改定の○×',
    axis: '178条・譲渡担保は○。192条・質権は×。',
    imageKey: 'minpou-joshiki/tanpo-senyu',
  },
  {
    id: 'joshiki-chintainin',
    track: '民法',
    subject: '債権各論',
    title: '賃貸人たる地位の移転',
    axis: '対抗要件ありなら承諾不要。請求には登記。',
    imageKey: 'minpou-joshiki/chintainin-chii',
  },
  {
    id: 'rinchi-sumika',
    track: '民法',
    subject: '民法物権',
    title: '隣地使用と住家',
    axis: '承諾なく隣地へ入れる場合と、住家は居住者の承諾。',
    imageKey: 'learn/minnpou/rinchi-sumika',
  },

  {
    id: 'shihainin',
    track: '商法',
    subject: '商法総則',
    title: '支配人の権限',
    axis: '営業に関する一切の裁判上・裁判外の行為。',
    imageKey: 'learn/shouhou/shihainin-kengen',
  },
  {
    id: 'mochibun-3sha',
    track: '商法',
    subject: '会社法',
    title: '持分会社の第三者',
    axis: '業務執行社員・持分の譲渡・責任の切り方。',
    imageKey: 'learn/shouhou/mochibun-3sha',
  },

  {
    id: 'chokusetsu-1',
    track: '憲法',
    subject: '憲法',
    title: '直接適用・間接適用・類推',
    axis: '私人間には直接も類推もせず、間接適用が原則。',
    imageKey: 'learn/kenpou/chokusetsu-kansetsu-ruisui',
  },
  {
    id: 'chokusetsu-2',
    track: '憲法',
    subject: '憲法',
    title: '私人間効力の続き',
    axis: '三菱樹脂と昭和女子大の聞き分け。',
    imageKey: 'learn/kenpou/chokusetsu-kansetsu-ruisui-2',
  },
  {
    id: 'sonshitsu-yogo',
    track: '憲法',
    subject: '憲法',
    title: '損失補償と擁護義務',
    axis: '29条3項と99条。国民に擁護義務はない。',
    imageKey: 'learn/kenpou/sonshitsu-hoshou-yogo',
  },
  {
    id: 'kakyu-ninmei',
    track: '憲法',
    subject: '憲法',
    title: '下級裁判所の裁判官',
    axis: '内閣が名簿で任命。最高裁と混ぜない。',
    imageKey: 'learn/kenpou/kakyu-saibankan-ninmei',
  },

  {
    id: 'kengen-kengen',
    track: '基礎',
    subject: '基礎法学',
    title: '権限と権原',
    axis: 'できる範囲を決めるのが権限。根拠を示すのが権原。',
    imageKey: 'learn/kiso/kengen-ken-gen',
  },
  {
    id: 'kengen-2',
    track: '基礎',
    subject: '基礎法学',
    title: '権限・権原の続き',
    axis: '管理者と占有者で語を分ける。',
    imageKey: 'learn/kiso/kengen-ken-gen-2',
  },
  {
    id: 'kansuru-kakaru',
    track: '基礎',
    subject: '基礎法学',
    title: '関すると係る',
    axis: '関連全般か、直接の結びつきか。',
    imageKey: 'learn/kiso/kansuru-kakaru',
  },
  {
    id: 'matawa',
    track: '基礎',
    subject: '基礎法学',
    title: '又はと若しくは',
    axis: '大きいグループに又は、小さいグループに若しくは。',
    imageKey: 'learn/kiso/matawa-moshikuwa',
  },
  {
    id: 'tadachini',
    track: '基礎',
    subject: '基礎法学',
    title: '直ちに・速やかに・遅滞なく',
    axis: '即時／できるだけ早く／正当な理由があれば遅れ得る。',
    imageKey: 'learn/kiso/tadachini',
  },
  {
    id: 'naranai',
    track: '基礎',
    subject: '基礎法学',
    title: 'ならないとできない',
    axis: '義務の向きが違う。禁止と不能を混ぜない。',
    imageKey: 'learn/kiso/naranai-dekinai',
  },
  {
    id: 'kaishaku',
    track: '基礎',
    subject: '基礎法学',
    title: '解釈の4類型',
    axis: '拡張・縮小・反対・当然。工作物に工場機械は拡張。',
    imageKey: 'learn/kiso/kaishaku-4type',
  },
  {
    id: 'kaishaku-2',
    track: '基礎',
    subject: '基礎法学',
    title: '解釈の続き',
    axis: '類推は文言の枠外。拡張と取り違えない。',
    imageKey: 'learn/kiso/kaishaku-4type-2',
  },
  {
    id: 'mochiron-kaishaku',
    track: '基礎',
    subject: '基礎法学',
    title: '勿論解釈',
    axis: '雨水禁止の趣旨から、雪解け水も同様に禁止。',
    imageKey: 'learn/kiso/mochiron-kaishaku',
  },
  {
    id: 'kakucho-kaishaku',
    track: '基礎',
    subject: '基礎法学',
    title: '拡張解釈',
    axis: '刑法38条3項の法律を政令・省令・条例・規則まで広く読む。',
    imageKey: 'learn/kiso/kakucho-kaishaku',
  },
  {
    id: 'shukusho-kaishaku',
    track: '基礎',
    subject: '基礎法学',
    title: '縮小解釈',
    axis: '177条の第三者は、正当な利益がある者に限る。',
    imageKey: 'learn/kiso/shukusho-kaishaku',
  },
  {
    id: 'hantai-kaishaku',
    track: '基礎',
    subject: '基礎法学',
    title: '反対解釈',
    axis: '20歳未満は飲酒禁止。20歳以上はその年齢制限を受けない。',
    imageKey: 'learn/kiso/hantai-kaishaku',
  },
  {
    id: 'kenshin-saibanin',
    track: '基礎',
    subject: '基礎法学',
    title: '検察審査会と裁判員',
    axis: 'くじは一般市民。人数は11と9で切る。',
    imageKey: 'learn/kiso/kenshin-vs-saibanin',
  },
  {
    id: 'horei-keishiki',
    track: '基礎',
    subject: '基礎法学',
    title: '法令の形式',
    axis: '法律・命令・規則。公布と施行を混ぜない。',
    imageKey: 'learn/kiso/horei-keishiki',
  },
  {
    id: 'kanpo',
    track: '基礎',
    subject: '基礎法学',
    title: '官報と告示',
    axis: '公布の方法。周知期間の起算。',
    imageKey: 'learn/kiso/kanpo-kokuji',
  },
  {
    id: 'kokin-ouhou',
    track: '基礎',
    subject: '基礎法学',
    title: '拘禁刑の目的',
    axis: '懲役・禁錮の用語は使わない。改善更生と再犯防止。',
    imageKey: 'learn/kiso/kokin-ouhou-mokuteki',
  },
  {
    id: 'shinakereba',
    track: '基礎',
    subject: '基礎法学',
    title: 'しなければならないとみなす',
    axis: '義務と擬制。努めるものとする（努力）と混ぜない。',
    imageKey: 'learn/kiso/shinakereba-monotosuru',
  },
  {
    id: 'keiju',
    track: '基礎',
    subject: '基礎法学',
    title: '刑の軽重の年表',
    axis: '刑法6条。変更後の軽い刑。',
    imageKey: 'learn/kiso/keiju-timeline',
  },
  {
    id: 'kojin-teigi',
    track: '基礎',
    subject: '個人情報保護法',
    title: '個人情報の定義',
    axis: '生存する個人。識別可能性。',
    imageKey: 'learn/kojinjoho/teigi',
  },
  {
    id: 'juki-vs-koseki',
    track: '基礎',
    subject: '戸籍・住基',
    title: '戸籍と住民票',
    axis: '身分の公証と住所の公証。単位が違う。',
    imageKey: 'learn/juki/vs-koseki',
  },
  {
    id: 'gyoseishoshi-dare',
    track: '基礎',
    subject: '行政書士法',
    title: '行政書士は誰が',
    axis: '他人の依頼を受け報酬を得て書類作成。',
    imageKey: 'learn/gyoseishoshi/dare-ga',
  },

  {
    id: 'r8-shimei',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '行政書士法',
    title: '使命と職責・デジタル',
    axis: '1条は使命。デジタルは努力義務。施行は令和8年1月1日。',
    imageKey: 'learn/gyoseishoshi/r8-shimei',
  },
  {
    id: 'r8-tokutei',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '行政書士法',
    title: '特定行政書士・業務制限・両罰',
    axis: '作成することができる書類。名目を問わず報酬。両罰は23条の3。',
    imageKey: 'learn/gyoseishoshi/r8-tokutei-ryobatsu',
  },
  {
    id: 'kyodo-shinken',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '家族法',
    title: '離婚後の親権',
    axis: '双方又は一方。子の利益。害悪のおそれは一方を定めなければならない。',
    imageKey: 'learn/minnpou/kyodo-shinken',
  },
  {
    id: 'yoiku-koryu',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '家族法',
    title: '養育費と親子交流',
    axis: '766条で監護・交流・費用。定めなしの協議離婚は766条の3。',
    imageKey: 'learn/minnpou/yoiku-koryu',
  },
  {
    id: 'shinsa-shobun-riyu',
    track: '直前期パック',
    alsoIn: ['行政法'],
    subject: '行政手続法',
    title: '審査基準・処分基準・理由提示',
    axis: '5条は定めと公表が義務。12条は努力。14条は理由を示す。',
    imageKey: 'learn/tetsuzuki/shinsa-shobun-riyu',
  },
  {
    id: 'daishikko-tetsuzuki',
    track: '直前期パック',
    alsoIn: ['行政法'],
    subject: '行政法総論',
    title: '代執行の対象と手順',
    axis: '代替的作為。戒告→令書→実施→費用。第三者可。',
    imageKey: 'learn/gyosei/daishikko-tetsuzuki',
  },
  {
    id: 'gimetsuke-shinsei',
    track: '直前期パック',
    alsoIn: ['行訴・国賠'],
    subject: '行政事件訴訟法',
    title: '申請型と非申請型の義務付け',
    axis: '申請型に重大な損害は要らない。非申請型は重大な損害と補充性。',
    imageKey: 'learn/gyosho/gimetsuke-shinsei',
  },
  {
    id: 'kari-kyusai-songai',
    track: '直前期パック',
    alsoIn: ['行訴・国賠'],
    subject: '行政事件訴訟法',
    title: '重大な損害と償うことのできない損害',
    axis: '執行停止・差止めは重大。仮の義務付け・仮の差止めは償えない。',
    imageKey: 'learn/gyosho/kari-kyusai-songai',
  },
  {
    id: 'sonshitsu-hoshou',
    track: '直前期パック',
    alsoIn: ['行訴・国賠'],
    subject: '国家賠償法',
    title: '国賠と損失補償',
    axis: '1条は人。2条は物。補償は適法な特別の犠牲。',
    imageKey: 'learn/kokubai/sonshitsu-hoshou',
  },
  {
    id: 'saigai-yoken',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '債権総論',
    title: '詐害行為取消の要件',
    axis: '被保全は行為前の原因。財産権。受益者善意なら不可。',
    imageKey: 'learn/minnpou/saigai-yoken',
  },
  {
    id: 'saigai-jiko',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '債権総論',
    title: '転得者と金銭の自己請求',
    axis: '転得ごとの悪意。金銭・動産は自己へ求め得る。',
    imageKey: 'learn/minnpou/saigai-jiko',
  },
  {
    id: 'jiho-sosai',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '債権総論',
    title: '時効と相殺',
    axis: '508条は完成前の相殺適状。511条は差押え後取得が原則不可。',
    imageKey: 'learn/minnpou/jiho-sosai',
  },
  {
    id: 'ketsugi-futsukabetsu',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '普通決議と特別決議',
    axis: '定足は過半数出席。可決は過半数か3分の2か。',
    imageKey: 'learn/shouhou/ketsugi-futsukabetsu',
  },
  {
    id: 'ketsugi-1-yoken',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '普通決議・341条・特別決議',
    axis: '定足は議決権の過半数出席。賛成は出席議決権。341条は定足を3分の1未満にできない。監査役の解任は特別。',
    imageKey: 'learn/shouhou/ketsugi-1-yoken',
  },
  {
    id: 'ketsugi-futsu-tokubetsu-ichiran',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '普通決議と特別決議の対象',
    axis: '選任・金銭配当・欠損範囲の減資は普通。監査役解任・現物配当・原則の減資・解散は特別。',
    imageKey: 'learn/shouhou/ketsugi-futsu-tokubetsu-ichiran',
  },
  {
    id: 'ketsugi-2-tokushu',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '特殊決議・創立総会・総株主の同意',
    axis: '特殊は頭数と総議決権。創立総会は総議決権の過半数かつ出席の3分の2。全部免除は総株主の同意。',
    imageKey: 'learn/shouhou/ketsugi-2-tokushu',
  },
  {
    id: 'ketsugi-3-kikan-haito',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '選任・配当・資本金の決議',
    axis: '監査役は選任普通・解任特別。資本金減少は原則特別。欠損範囲は普通。447条3項は取締役（会）。',
    imageKey: 'learn/shouhou/ketsugi-3-kikan-haito',
  },
  {
    id: 'setsuritsu-hokki',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '発起設立と募集設立',
    axis: '全部引受けは発起。募るときは創立総会。',
    imageKey: 'learn/shouhou/setsuritsu-hokki-boshu',
  },
  {
    id: 'kaisan-seisan',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '解散・継続と清算',
    axis: '473条は1号から3号。475条2号は設立無効、3号は株式移転無効。合併無効は混ぜない。',
    imageKey: 'learn/shouhou/kaisan-seisan',
  },
  {
    id: 'fuuhyo-bangou',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '戸籍・住基',
    title: '住民票・附票・番号',
    axis: '附票は本籍地。法人番号は法人。公的個人認証は外国人住民も。',
    imageKey: 'learn/juki/fuuhyo-bangou',
  },
  {
    id: 'kamei-tokumei',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '個人情報保護法',
    title: '仮名加工と匿名加工',
    axis: '仮名は照合。匿名は復元できない。履歴はすぐ匿名にしない。',
    imageKey: 'learn/kojinjoho/kamei-tokumei',
  },
  {
    id: 'kenetsu-jizen',
    track: '直前期パック',
    alsoIn: ['憲法'],
    subject: '憲法',
    title: '検閲と事前抑制',
    axis: '検閲は行政の事前禁止。司法の差止めは検閲そのものではない。',
    imageKey: 'learn/kenpou/kenetsu-jizen',
  },
  {
    id: 'kokin-sagyo',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '基礎法学',
    title: '拘禁刑と作業',
    axis: '懲役・禁錮の一本化。作業は必要に応じ行い得る。',
    imageKey: 'learn/kiso/kokin-sagyo',
  },
  {
    id: 'utae-no-rieki',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '訴えの利益',
    axis: '判決時の実益。満了でも直ちに欠けるわけではない。',
    imageKey: 'learn/gyosho/utae-no-rieki',
  },
  {
    id: 'teito-bougai',
    track: '民法',
    subject: '民法物権',
    title: '抵当権の妨害排除',
    axis: '交換価値を害する占有。物上代位は払渡し前の差押え。',
    imageKey: 'learn/minnpou/teito-bougai',
  },
  {
    id: 'shido-nin-i',
    track: '行政法',
    subject: '行政手続法',
    title: '行政指導の任意と求め',
    axis: '32条は任意。中止は相手方。処分等の求めは何人も。',
    imageKey: 'learn/gyosei/shido-nin-i-chushi',
  },
  {
    id: 'gyoseishido-shokibo',
    track: '行政法',
    subject: '行政手続法',
    title: '行政指導の小と大',
    axis: '原則は処分ではない。拒否後の確認留保は特段の事情がなければ違法。病院開設中止勧告は処分に当たる。',
    imageKey: 'learn/gyosei/gyoseishido-shokibo',
  },
  {
    id: 'hourei-todokede',
    track: '行政法',
    subject: '行政手続法',
    title: '法令の定義と届出',
    axis: '定義に条例・規則は入る。届出は形式上適合し、提出先の事務所への到達で履行。',
    imageKey: 'learn/tetsuzuki/hourei-todokede',
  },
  {
    id: 'riyuu-teiji-shushi-teido',
    track: '行政法',
    subject: '行政手続法',
    title: '理由提示の趣旨と程度',
    axis: '趣旨は昭38。当てはめは昭60。公表の有無を含む総合考慮は平23.6.7。',
    imageKey: 'learn/tetsuzuki/riyuu-teiji-shushi-teido',
  },
  {
    id: 'ko-no-shisetsu',
    track: '行政法',
    subject: '地方自治法',
    title: '公の施設の利用拒否',
    axis: '正当な理由なく拒めない。不当な差別的取扱い禁止。',
    imageKey: 'learn/jichi/ko-no-shisetsu',
  },
  {
    id: 'shinri-ryuho',
    track: '直前期パック',
    alsoIn: ['民法'],
    subject: '民法総則',
    title: '心裡留保と虚偽表示',
    axis: '心裡留保は原則有効。無効組は善意の第三者に対抗できない。',
    imageKey: 'learn/minnpou/shinri-ryuho',
  },
  {
    id: 'shihonkin',
    track: '直前期パック',
    alsoIn: ['商法'],
    subject: '会社法',
    title: '資本金と資本準備金',
    axis: '2分の1以上を資本金。消却では減らない。全額資本金化は異議なし。',
    imageKey: 'learn/shouhou/shihonkin',
  },
  {
    id: 'kujou-shori',
    track: '直前期パック',
    alsoIn: ['基礎'],
    subject: '個人情報保護法',
    title: '苦情処理の義務と努力義務',
    axis: '認定団体は求めなければならない。事業者・地方・行政機関の長等は努力義務。',
    imageKey: 'learn/kojinjoho/kujou-shori',
  },
  {
    id: 'kuni-no-kanyo',
    track: '直前期パック',
    alsoIn: ['行政法'],
    subject: '地方自治法',
    title: '国又は都道府県の関与',
    axis: '法律又は政令によらなければ、関与を受け、又は要しない。',
    imageKey: 'learn/jichi/kuni-no-kanyo',
  },
  {
    id: 'seikyu-saki',
    track: '直前期パック',
    alsoIn: ['行政法'],
    subject: '行政不服審査法',
    title: '審査請求先',
    axis: '4条1号から4号。庁の長は内閣府設置法又は国行組の庁の長。',
    imageKey: 'learn/fufuku/seikyu-saki',
  },
  {
    id: 'sentoku',
    track: '基礎',
    subject: '基礎法学',
    title: '先特後普',
    axis: '先にできた特別法は、後の一般法に優先する。',
    imageKey: 'learn/kiso/sentoku',
  },
  {
    id: 'keihou6',
    track: '基礎',
    subject: '基礎法学',
    title: '刑法6条',
    axis: '刑の変更があったときは、軽い方を適用する。',
    imageKey: 'learn/kiso/keihou6',
  },
  {
    id: 'adr-4',
    track: '基礎',
    subject: '基礎法学',
    title: 'ADRの4類型',
    axis: '調停・和解・仲裁・あっせんを聞き分ける。',
    imageKey: 'learn/kiso/adr-4',
  },
  {
    id: 'hougen',
    track: '基礎',
    subject: '基礎法学',
    title: '法源',
    axis: '制定法が先。判例・条理・学説は後。',
    imageKey: 'learn/kiso/hougen',
  },
  {
    id: 'shinsakai-role',
    track: '行政法',
    subject: '行政不服審査法',
    title: '行政不服審査会',
    axis: '答申は審査会。裁決は審査庁。',
    imageKey: 'fufuku/shinsakai-role',
  },
  {
    id: 'shinriin-nagare',
    track: '行政法',
    subject: '行政不服審査法',
    title: '審理員の仕事の流れ',
    axis: '審理員は審理・意見書。審査庁は裁決。弁明書は処分庁等。',
    imageKey: 'learn/gyoseihou/shinriin-nagare',
  },
  {
    id: 'saiketsu-henko-46',
    track: '行政法',
    subject: '行政不服審査法',
    title: '46条の変更権',
    axis: '変更できるのは処分庁又は上級。第三者審査庁は取消しだけ。',
    imageKey: 'fufuku/saiketsu-henko-46',
  },
  {
    id: 'shinsa-kikan-hikaku',
    track: '行政法',
    subject: '行政不服審査法',
    title: '不服申立期間',
    axis: '主観は3か月・3か月・1か月。再審査だけ1か月。不作為の審査請求に期間はない。',
    imageKey: 'fufuku/shinsa-kikan-hikaku',
  },
  {
    id: 'shikko-futeishi-jiko',
    track: '行政法',
    subject: '行政不服審査法',
    title: '執行不停止',
    axis: '審査請求は効力・執行・手続の続行を妨げない。',
    imageKey: 'fufuku/shikko-futeishi-jiko',
  },
  {
    id: '7jo-ippan-kaku',
    track: '行政法',
    subject: '行政不服審査法',
    title: '一般概括主義と7条',
    axis: '特別の定めがなければこの法律。10号は外国人の出入国又は帰化。',
    imageKey: 'fufuku/7jo-ippan-kaku',
  },
  {
    id: 'sankasya-19-23-28',
    track: '行政法',
    subject: '行政不服審査法',
    title: '参加人・記載・補正・審理計画',
    axis: '不作為も参加人。補正は23条。審理計画は28条。',
    imageKey: 'fufuku/sankasya-19-23-28',
  },
  {
    id: 'jijou-saiketsu-4jo-15',
    track: '行政法',
    subject: '行政不服審査法',
    title: '事情裁決と46条・15条',
    axis: '事情裁決は45条3項。上級は自ら処分できない。承継は15条。',
    imageKey: 'fufuku/jijou-saiketsu-4jo-15',
  },
  {
    id: 'shobunsei-jorei-suidou',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '処分性（条例・水道・同意・勧告）',
    axis: '特定保育所の廃止は○。水道料金改定条例と用途地域は×。',
    imageKey: 'gyosho/shobunsei-jorei-suidou',
  },
  {
    id: 'shikko-teishi-shokken',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '執行停止の職権',
    axis: '行服は職権もあり得る。行訴は申立てのみ。総理異議は強制。',
    imageKey: 'gyosho/shikko-teishi-shokken-hikaku',
  },
  {
    id: 'shikko-teishi-3types',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '執行停止の3類型',
    axis: '執行と手続続行で目的を達することができるときは、効力の停止はできない。',
    imageKey: 'gyosho/shikko-teishi-3types',
  },
  {
    id: 'shikko-teishi-torikeshi-26',
    track: '行政法',
    alsoIn: ['行訴・国賠'],
    subject: '行政不服審査法',
    title: '執行停止の取消し',
    axis: '行服26条は職権でできる。行訴26条は確定後の申立て。27条は取り消さなければならない。',
    imageKey: 'fufuku/shikko-teishi-torikeshi-26',
  },
  {
    id: 'kyoji-saichosa-misoshiji',
    track: '行政法',
    alsoIn: ['行訴・国賠'],
    subject: '教示',
    title: '教示と83条のみなし',
    axis: '相手方教示は82条と46条。利害関係人とみなしは行服法だけ。',
    imageKey: 'fufuku/kyoji-saichosa-misoshiji',
  },
  {
    id: 'saibansho',
    track: '基礎',
    subject: '基礎法学',
    title: '第一審と控訴先',
    axis: '罰金以下は簡裁。簡裁民事の控訴は地裁、刑事は高裁。人事は家裁。',
    imageKey: 'learn/kiso/saibansho',
  },
  {
    id: 'daisansha-kou-junyo',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '第三者効と拘束力',
    axis: '32条は取消判決。33条の拘束力は広く準用。棄却に拘束力はない。',
    imageKey: 'gyosho/daisansha-kou-junyo',
  },
  {
    id: 'shikko-kikan-hikaku',
    track: '行政法',
    subject: '地方自治法',
    title: '執行機関の二つの意味',
    axis: '総論は実力で実現する機関。自治法は長と委員会・委員。副知事は補助機関。',
    imageKey: 'learn/jichi/shikko-kikan-hikaku',
  },
  {
    id: 'jichi-keizoku-kurikoshi',
    track: '行政法',
    subject: '地方自治法',
    title: '継続費と繰越明許費',
    axis: '継続費は212条の複数年計画。繰越明許費は213条の翌年度繰越し。',
    imageKey: 'gyouseihou/chihou/jichi-keizoku-kurikoshi',
  },
  {
    id: 'kokubai-osaka-kyoyo',
    track: '行訴・国賠',
    subject: '国家賠償法',
    title: '大阪空港と供用関連瑕疵',
    axis: '瑕疵は物的欠陥だけではない。供用に伴う騒音等も2条の対象になり得る。',
    imageKey: 'gyouseihou/kokubai/kokubai-osaka-kyoyo-kashi',
  },
  {
    id: 'jumin-1-4',
    track: '行政法',
    subject: '地方自治法',
    title: '住民訴訟1号から4号',
    axis: '1号差止め、2号取消し又は無効確認、3号怠る事実、4号は請求を求める。',
    imageKey: 'textbook/gyosei-kijutsu/jumin-1-4',
  },
  {
    id: 'kenpou-seijou',
    track: '憲法',
    subject: '憲法',
    title: 'けんぽうせいじょう',
    axis: '憲法改正・法律・政令・条約を公布する。予算・省令・最高裁判所規則は入らない。',
    imageKey: 'learn/kenpou/kenpou-seijou',
  },
  {
    id: 'naka-kanazawa',
    track: '憲法',
    subject: '憲法',
    title: '金沢庁舎前',
    axis: '庁舎前広場は庁舎と一体。示威禁止は21条1項に違反しない。',
    imageKey: 'naka/kenpou/kanazawa',
  },
  {
    id: 'naka-izumisano',
    track: '憲法',
    subject: '憲法',
    title: '泉佐野市民会館',
    axis: '公の施設は原則貸す。明らかな差し迫った危険が具体的に予見されるときだけ不許可。',
    imageKey: 'naka/kenpou/izumisano',
  },
  {
    id: 'naka-keibi',
    track: '憲法',
    subject: '憲法',
    title: '旧警備業法',
    axis: '能力不足ではない一律排除は必要かつ合理的でない。国賠は認めない。',
    imageKey: 'naka/kenpou/keibi',
  },
  {
    id: 'naka-rakuten',
    track: '憲法',
    subject: '憲法',
    title: '楽天ダイレクト',
    axis: '要指導医薬品の対面義務は態様規制であり、合憲。',
    imageKey: 'naka/kenpou/rakuten',
  },
  {
    id: 'naka-osaka-hate',
    track: '憲法',
    subject: '憲法',
    title: '大阪ヘイトスピーチ条例',
    axis: '入口は住民訴訟4号。条例は21条1項に違反せず棄却。',
    imageKey: 'naka/kenpou/osaka-hate',
  },
  {
    id: 'naka-google-twitter',
    track: '憲法',
    subject: '憲法',
    title: '検索削除とツイート削除',
    axis: '根拠は人格権。Googleは優越が明らかなとき。Twitterは優越する場合。',
    imageKey: 'naka/kenpou/google-twitter',
  },
  {
    id: 'naka-jumin-3',
    track: '行政法',
    subject: '地方自治法',
    title: '住民訴訟の入口と叩き方',
    axis: '入口は住民監査請求から住民訴訟。愛媛と大阪は支出。孔子廟は怠る事実。',
    imageKey: 'naka/gyosei/jumin-3',
  },
  {
    id: 'naka-koto-iken',
    track: '行政法',
    subject: '行政不服審査法',
    title: '口頭にするのは誰か',
    axis: '口頭意見陳述は請求人又は参加人の申立て。弁明は行政庁が認めるとき。',
    imageKey: 'naka/gyosei/koto-iken',
  },
  {
    id: 'naka-inochi-toride',
    track: '憲法',
    subject: '憲法',
    title: 'いのちの砦',
    axis: 'デフレ調整は判断過程の過誤欠落で違法。ゆがみ調整は適法。国賠は認めない。',
    imageKey: 'naka/kenpou/inochi-toride',
  },
  {
    id: 'naka-bougai-ladder',
    track: '憲法',
    subject: '憲法',
    title: '人格権の妨害排除',
    axis: '占有から物権、人格権へ。削除は妨害排除の一種。根拠は13条ではない。',
    imageKey: 'naka/kenpou/bougai-ladder',
  },
  {
    id: 'sonota',
    track: '基礎',
    subject: '基礎法学',
    title: 'その他とその他の',
    axis: 'その他は並列。その他のは例示。国賠2条の道路も営造物に含まれる。',
    imageKey: 'learn/kiso/sonota',
  },
  {
    id: 'kasuru',
    track: '基礎',
    subject: '基礎法学',
    title: '科すると課する',
    axis: '過料は刑罰ではないが科する。税は課する。',
    imageKey: 'learn/kiso/kasuru',
  },
  {
    id: 'chokutini-sokuni',
    track: '行政法',
    subject: '行政不服審査法',
    title: '直ちに・遅滞なく・速やかに',
    axis: '意見書の作成は遅滞なく。提出は速やかに。57条の義務語句は遅滞なく。',
    imageKey: 'fufuku/chokutini-sokuni-chienaku',
  },
  {
    id: 'shoko-32-36',
    track: '行政法',
    subject: '行政不服審査法',
    title: '証拠提出と審理員の調査',
    axis: '32条は三者。立会の機会は申立てによる検証。鑑定は34条。',
    imageKey: 'fufuku/shoko-32-36',
  },
  {
    id: 'tojisha-vs-soten',
    track: '行訴・国賠',
    subject: '行政事件訴訟法',
    title: '当事者訴訟と争点訴訟',
    axis: '額は当事者訴訟。収用後の所有権確認は争点訴訟。被告は起業者。',
    imageKey: 'gyosho/tojisha-vs-soten',
  },
  {
    id: 'kyoji-hikaku',
    track: '行訴・国賠',
    alsoIn: ['行政法'],
    subject: '教示',
    title: '教示の比較',
    axis: '相手方への教示は書面義務。第三者の求めは行審法だけ。',
    imageKey: 'learn/gyosho/kyoji-hikaku',
  },
  {
    id: 'jikou-chitai',
    track: '民法',
    subject: '債権総論',
    title: '時効の起算と履行遅滞',
    axis: '時効は行使できる時。遅滞は412条。不確定期限の遅滞は早い時。',
    imageKey: 'learn/minnpou/jikou-chitai',
  },
  {
    id: 'naka-koushibyou',
    track: '憲法',
    subject: '憲法',
    title: '孔子廟',
    axis: '総合考慮で20条3項に当たり違憲。住民訴訟は怠る事実。',
    imageKey: 'naka/kenpou/koushibyou',
  },
];
