/**
 * 民法・登場人物関係図（自動生成）
 * node scripts/generatePersonFlowImages.js で再生成
 */
export type PersonFlowDiagramItem = {
  source: number;
  caption?: string;
};

export const BY_QUESTION_TEXT_HASH: Record<string, PersonFlowDiagramItem | PersonFlowDiagramItem[]> = {
  '10i6hb': { source: require('@/assets/images/person-flow/minnpou/bukken/10i6hb.png'), caption: "Aの土地をBの時効完成前に、CがAから土地を買い受けて登記を備えた場合、その後時効取得したBは登記なくしてCに対抗できる" },
  '15aesj': { source: require('@/assets/images/person-flow/minnpou/bukken/15aesj.png'), caption: "質権の引渡しに占有改定は含まれない" },
  '15nldt': { source: require('@/assets/images/person-flow/minnpou/bukken/15nldt.png'), caption: "集合物譲渡担保契約が締結され、動産の種類、量的範囲、場所が特定された場合、占有改定が行われ、動産の新たな構成部分が集合物" },
  '1s7dnm': { source: require('@/assets/images/person-flow/minnpou/bukken/1s7dnm.png'), caption: "Bが建物をCに売却し引渡しまでしたが、BはAに二重譲渡し登記まで備えた場合、CはAからの建物引渡し請求に対し、Bに対する" },
  '1v6vhu': { source: require('@/assets/images/person-flow/minnpou/bukken/1v6vhu.png'), caption: "第三者の不法占有により抵当不動産の交換価値の実現が妨げられ、抵当権者の優先弁済県の行使が困難となった場合で、抵当不動産を" },
  '22ibgx': { source: require('@/assets/images/person-flow/minnpou/sousoku/22ibgx.png'), caption: "本人であるJが追認拒絶をした後に亡くなり、無権代理人であるLが単独相続した場合、Jの追認拒絶は相続人のLに及び効力を失わ" },
  '26n4o0': { source: require('@/assets/images/person-flow/minnpou/bukken/26n4o0.png'), caption: "排水地役権を妨害された場合、地役権に基づく損害賠償請求および妨害予防請求が認められるが、占有権能を含まないことから、返還" },
  '2gv45d': { source: require('@/assets/images/person-flow/minnpou/bukken/2gv45d.png'), caption: "Aは債権者Bのため、A所有の甲土地に、被担保債権の範囲をA・B間の継続的売買に係る売掛代金債権とし、その極度額を1億円と" },
  '2my5og': { source: require('@/assets/images/person-flow/minnpou/bukken/2my5og.png'), caption: "留置権に関する次の記述のうち、民法の規定および判例に照らし、妥当でないものはどれか。" },
  '2qju0k': { source: require('@/assets/images/person-flow/minnpou/bukken/2qju0k.png'), caption: "Cがベイベー銀行との抵当権設定登記後に、CはAへ抵当建物を賃貸し、Aが抵当不動産の交換価値を妨げ、優先弁債権の行使が困難" },
  '2sth13': { source: require('@/assets/images/person-flow/minnpou/bukken/2sth13.png'), caption: "留置権に関する次の記述のうち、民法の規定および判例に照らし、妥当なものはどれか。" },
  '2y89gp': { source: require('@/assets/images/person-flow/minnpou/bukken/2y89gp.png'), caption: "問題文 A、BおよびCが甲土地を共有し、甲土地上には乙建物が存在している。この場合に関する次のア〜オの記述のうち、民法の" },
  '2yybum': { source: require('@/assets/images/person-flow/minnpou/sousoku/2yybum.png'), caption: "A社の理事であるNがCと軽自動車の売買契約を結び、本来は理事会の承認が必要でありるが、Nは承認を得なかった。CはNが理事" },
  '2zvxo1': { source: require('@/assets/images/person-flow/minnpou/bukken/2zvxo1.png'), caption: "A所有の甲土地上に権原なくD所有の未登記丁建物が存在し、未登記のままCに譲渡した場合、DはAに対し丁建物の収去および甲土" },
  '35jqzo': { source: require('@/assets/images/person-flow/minnpou/bukken/35jqzo.png'), caption: "根抵当権の元本確定期日は定めることも、変更することもでき、この期日は、定めまたは変更した日から5年以内でなければならず、" },
  '3fjxzb': { source: require('@/assets/images/person-flow/minnpou/bukken/3fjxzb.png'), caption: "先取特権の引渡しに占有改定は含まれる" },
  '3hwd6w': { source: require('@/assets/images/person-flow/minnpou/bukken/3hwd6w.png'), caption: "A所有の甲土地とB所有の乙土地が隣接し、甲土地の上にはC所有の丙建物が存在している。この場合における次のア〜オの記述のう" },
  '3je1v8': { source: require('@/assets/images/person-flow/minnpou/bukken/3je1v8.png'), caption: "即時取得の引渡しに占有改定は含まれない" },
  '3k7hfd': { source: require('@/assets/images/person-flow/minnpou/bukken/3k7hfd.png'), caption: "囲繞地通行権は地上権者にも準用される" },
  '47z53k': { source: require('@/assets/images/person-flow/minnpou/bukken/47z53k.png'), caption: "一筆の土地の一部について、所有権を時効取得することはできる" },
  '48u33t': { source: require('@/assets/images/person-flow/minnpou/bukken/48u33t.png'), caption: "不動産売買の先取特権では、不動産の代価またはその利息の弁済がされていない旨を登記しなければならないが、その優劣は登記の前" },
  '4d75i2': { source: require('@/assets/images/person-flow/minnpou/bukken/4d75i2.png'), caption: "表立った虚偽表示がなくても、それを過失なく信じた者には、94条2項が類推適用され、虚偽表示の当事者は、引渡しを求められな" },
  '4im2gi': { source: require('@/assets/images/person-flow/minnpou/bukken/4im2gi.png'), caption: "他人の土地を２０年以上占有した者が当該土地を時効取得する場合、他主占有事情が証明されたとき、時効取得の事情を排斥される" },
  '4ktbor': { source: require('@/assets/images/person-flow/minnpou/sousoku/4ktbor.png'), caption: "内容証明郵便が不在配達され、受取人が不在配達通知に対応しないまま留置期間が終了し、差出人に還付された場合、留置期間の満了" },
  '4utn8m': { source: require('@/assets/images/person-flow/minnpou/bukken/4utn8m.png'), caption: "AがCの承諾を得てIに転貸借した場合であっても、AがIに対して有する転貸賃料債権を物上代位することはできない" },
  '50obsw': { source: require('@/assets/images/person-flow/minnpou/bukken/50obsw.png'), caption: "留置権者は善管注意義務を負い、善管注意義務は自己の財産に対するのと同一の注意よりも重い" },
  '5f52r2': { source: require('@/assets/images/person-flow/minnpou/bukken/5f52r2.png'), caption: "R、S、Tで共有地甲を分割する際、甲土地上の乙建物の所有者であるCに対し分割に際する通知をする義務はないが、Cは自己の費" },
  '5gmosj': { source: require('@/assets/images/person-flow/minnpou/sousoku/5gmosj.png'), caption: "BはAの代理人と偽って、Aが売主、Cが買主とする契約を締結した。BはCに動産を引き渡したが、当該契約は無権代理行為に当た" },
  '5jkdnl': { source: require('@/assets/images/person-flow/minnpou/bukken/5jkdnl.png'), caption: "Bのスイッチ２をCが保管していたところ、デトウに盗まれた。Cはデトウに対しスイッチ２の返還請求及び損害賠償請求をすること" },
  '5qkpvg': { source: require('@/assets/images/person-flow/minnpou/bukken/5qkpvg.png'), caption: "Cが地上権設定行為に基づき建物を築造し、期間の満了により地上権が消滅した場合で、土地所有者のAが当該建物を買い取る旨を通" },
  '5qod41': { source: require('@/assets/images/person-flow/minnpou/bukken/5qod41.png'), caption: "集合動産の譲渡担保は、種類、場所、量的範囲を指定することによって特定され、占有改定による引渡しも現実の引渡しにあたる" },
  '609gdh': { source: require('@/assets/images/person-flow/minnpou/bukken/609gdh.png'), caption: "A所有の甲土地上に、Bが権原なく丁建物を建設し、自己所有名義で建物保存登記を行い、Cに譲渡したが、登記名義がBのままであ" },
  '6z1p5r': { source: require('@/assets/images/person-flow/minnpou/bukken/6z1p5r.png'), caption: "A所有の甲土地上に権原なくB所有の乙建物が存在し、Bが乙建物をCに譲渡した後もB名義のままとした場合、その登記がBの意思" },
  '78wv0b': { source: require('@/assets/images/person-flow/minnpou/bukken/78wv0b.png'), caption: "CがAに対して有する賃料債権をBに譲渡し、その旨を内容証明郵便によって行い、ベイベー銀行が差し押さえを行った場合、Aがい" },
  '7awekt': { source: require('@/assets/images/person-flow/minnpou/bukken/7awekt.png'), caption: "元本確定後、債務者は、債権者に対し極度額の減額を請求でき、その範囲は、被担保債権額と以後２年間に生ずべき利息その他定期金" },
  '7axwph': { source: require('@/assets/images/person-flow/minnpou/sousoku/7axwph.png'), caption: "債権又は所有権以外の財産権は、権利を行使できる時から２０年間行使しないとき、時効により消滅する" },
  '7n47yv': { source: require('@/assets/images/person-flow/minnpou/bukken/7n47yv.png'), caption: "譲渡担保の目的物の中にメーカーが売却したフードプロセッサーが含まれており、譲渡担保設定者であるカマダ電気が期日までにフー" },
  '83t93l': { source: require('@/assets/images/person-flow/minnpou/bukken/83t93l.png'), caption: "元本確定前に抵当権者から免責的債務引受により被担保債権を譲り受けた者は、根抵当権を行使できず、根抵当権者も引受債務につい" },
  '8nsior': { source: require('@/assets/images/person-flow/minnpou/bukken/8nsior.png'), caption: "Bが他人の共有地甲の上に無断で乙建物を建てて甲を占有している場合、共有者のひとりであるGはBに対し、建物の収去および土地" },
  '8p6oeo': { source: require('@/assets/images/person-flow/minnpou/bukken/8p6oeo.png'), caption: "譲渡担保の引渡しに占有改定は含まれる" },
  '90zkuh': { source: require('@/assets/images/person-flow/minnpou/bukken/90zkuh.png'), caption: "Cが建物をAに賃貸したが、Aに賃料の不払いがあったため賃貸借契約を解除したところ、Aが建物を占有し続け、有益費を支出した" },
  '94bikx': { source: require('@/assets/images/person-flow/minnpou/bukken/94bikx.png'), caption: "元本確定前、債権者は、債務者の承諾を得て、根抵当権を第三者に譲り渡すことができる" },
  '953az3': { source: require('@/assets/images/person-flow/minnpou/bukken/953az3.png'), caption: "留置権者が債務者の承諾を得ずに留置物を使用、賃貸、担保に供した場合、債務者は留置権の消滅を請求できる" },
  '9f5db1': { source: require('@/assets/images/person-flow/minnpou/bukken/9f5db1.png'), caption: "隣地から竹木の枝が境界線を越えて侵入してきた場合、竹木の所有者に催告しなければ、枝を切除することはできない" },
  '9rtk6f': { source: require('@/assets/images/person-flow/minnpou/bukken/9rtk6f.png'), caption: "根抵当権に関する次の記述のうち、民法の規定に照らし、正しいものはどれか。" },
  'ahcnvw': { source: require('@/assets/images/person-flow/minnpou/bukken/ahcnvw.png'), caption: "ベイベイの抵当権が実行され、買受人であるIは、Aに対し直ちに妨害排除請求はできず、Iの買受けの時から6か月を経過するまで" },
  'ajcguc': { source: require('@/assets/images/person-flow/minnpou/sousoku/ajcguc.png'), caption: "１０年間、所有の意思をもって、平穏、かつ、公然と他人の物を占有した者は、占有開始時に善意かつ過失がなかったときは、所有権" },
  'apo2lt': { source: require('@/assets/images/person-flow/minnpou/bukken/apo2lt.png'), caption: "抵当権設定者が抵当不動産を他人に賃貸した場合、競売手続きを妨害する目的が認められ、賃借人の占有により交換価値の実現が妨げ" },
  'arh3s3': { source: require('@/assets/images/person-flow/minnpou/bukken/arh3s3.png'), caption: "樹木を土地と独立して売却することも認められる" },
  'az5pff': { source: require('@/assets/images/person-flow/minnpou/bukken/az5pff.png'), caption: "根抵当権の被担保債権の範囲は、極度額を限度とする" },
  'b6d79c': { source: require('@/assets/images/person-flow/minnpou/sousoku/b6d79c.png'), caption: "虚偽の売買契約を保証した者は、当該契約の錯誤による取消しを主張できる" },
  'bbkpli': { source: require('@/assets/images/person-flow/minnpou/bukken/bbkpli.png'), caption: "借地上の建物に抵当権が設定された場合、その建物の抵当権の効力は、借地権に及ぶ" },
  'befbnv': { source: require('@/assets/images/person-flow/minnpou/sousoku/befbnv.png'), caption: "虚偽表示の無効を対抗できない善意の第三者に関する次の記述のうち、民法の規定および判例に照らし、妥当でないものはどれか。" },
  'c6ri17': { source: require('@/assets/images/person-flow/minnpou/sousoku/c6ri17.png'), caption: "失踪者の所有地を相続したDが甲土地を悪意のBに売却後、失踪者の生存が判明した場合、B、D間の売買契約は無効となる" },
  'cd8yez': { source: require('@/assets/images/person-flow/minnpou/bukken/cd8yez.png'), caption: "Aが登記簿上の所有権名義人である甲土地をBが買い受ける旨の契約（以下「本件売買契約」という。）をA・B間で締結した場合に" },
  'dek93n': { source: require('@/assets/images/person-flow/minnpou/bukken/dek93n.png'), caption: "Aの土地をBが買い、所有権移転の仮登記をし、Aは土地をその事情を知らないCに売却し、所有権移転登記をした場合、Bは本登記" },
  'e6ovye': { source: require('@/assets/images/person-flow/minnpou/sousoku/e6ovye.png'), caption: "仮装債権を善意で譲り受けた者は第三者に当たるため、買主に対し売買代金の支払いを求めることができる" },
  'edp1g5': { source: require('@/assets/images/person-flow/minnpou/bukken/edp1g5.png') },
  'eps8sq': { source: require('@/assets/images/person-flow/minnpou/sousoku/eps8sq.png'), caption: "AとCが売買契約を結び、禁止行為をした場合に違約金を支払う旨の定めがあったが、AはBを介してCに禁止行為を誘発させた場合" },
  'fqsrq1': { source: require('@/assets/images/person-flow/minnpou/bukken/fqsrq1.png'), caption: "地役権は、継続的に行使され、かつ、外形上認識することができるものに限り、時効取得できる" },
  'g04gd9': { source: require('@/assets/images/person-flow/minnpou/bukken/g04gd9.png'), caption: "共同相続土地を、その事情を知らず、かつ、過失のない者が登記を備えた場合であっても、土地の全部について対抗できるわけではな" },
  'g55z9r': { source: require('@/assets/images/person-flow/minnpou/sousoku/g55z9r.png'), caption: "本人であるJが死亡し、無権代理人であるLが母のKと共に共同相続した場合、Kの追認がなければ、Nとの売買契約は有効とはなら" },
  'g5xyuo': { source: require('@/assets/images/person-flow/minnpou/sousoku/g5xyuo.png'), caption: "一般訴債権の債権者は権利を行使できることを知った時から５年間行使しないとき、債権は時効により消滅する" },
  'gd15wg': { source: require('@/assets/images/person-flow/minnpou/bukken/gd15wg.png'), caption: "BがAの所有する不動産をCに売却し引き渡したが、Aから所有権を取得して引き渡すことができなかった場合、CはAからの建物引" },
  'gh51xf': { source: require('@/assets/images/person-flow/minnpou/bukken/gh51xf.png'), caption: "眺望を害されない地役権を設定し登記を備えた後に、建物の築造により眺望を害された場合、地役権に基づき建物の収去を求めること" },
  'h8ki7u': { source: require('@/assets/images/person-flow/minnpou/bukken/h8ki7u.png'), caption: "Cが、R、S、Tの共有する乙建物をRの承諾のもと賃借して居住し、R、S、Tの共有する甲土地を占有した場合、S、Tは当然に" },
  'h9bqjt': { source: require('@/assets/images/person-flow/minnpou/bukken/h9bqjt.png'), caption: "Aの土地をBが時効取得し、その後GがAから土地を買い受けて所有権移転登記を完成したが、Bはさらに取得時効に必要な期間を経" },
  'hai9wq': { source: require('@/assets/images/person-flow/minnpou/sousoku/hai9wq.png'), caption: "組合規約等で業務執行の代理権限を制限しても、善意無過失の第三者には対抗できない" },
  'hbgpom': { source: require('@/assets/images/person-flow/minnpou/bukken/hbgpom.png'), caption: "Aの土地にBが無断で建物を築造し、登記も備えた場合、Aから土地を買い受けたCは、登記の名義人であるBに対し、建物の収去お" },
  'hfb9as': { source: require('@/assets/images/person-flow/minnpou/sousoku/hfb9as.png'), caption: "AとBが通謀し、Aの土地を仮装譲渡し、BはAの土地に家を建て、善意のCに賃貸した場合、Aは虚偽表示の無効をCに対抗できる" },
  'hhayzv': { source: require('@/assets/images/person-flow/minnpou/sousoku/hhayzv.png'), caption: "破産者の保証人は、消滅時効を援用することはできない" },
  'hvbjeb': { source: require('@/assets/images/person-flow/minnpou/bukken/hvbjeb.png'), caption: "占有者が占有を奪われたとき、占有回収の訴えにより、その物の返還請求及び損害賠償請求ができる" },
  'i95ymt': { source: require('@/assets/images/person-flow/minnpou/bukken/i95ymt.png'), caption: "敷金返還請求権を保全するために留置権を行使することはできない" },
  'i9mob0': { source: require('@/assets/images/person-flow/minnpou/bukken/i9mob0.png'), caption: "占有改定等に関する次のア～オの記述のうち、民法の規定および判例に照らし、妥当でないものの組合せはどれか。" },
  'ib73gn': { source: require('@/assets/images/person-flow/minnpou/bukken/ib73gn.png'), caption: "不動産の保存の先取特権を直ちに登記した場合、同一不動産上に登記された既存の抵当権に優先する" },
  'ih7f29': { source: require('@/assets/images/person-flow/minnpou/sousoku/ih7f29.png'), caption: "連帯保証人が他にも連帯保証人がいると誤信した場合でも、それは動機に過ぎないから、他の保証人の存在を特に保証契約とした旨の" },
  'ii06lq': { source: require('@/assets/images/person-flow/minnpou/bukken/ii06lq.png'), caption: "マシニングセンターの引渡しを受けた賃借人Cは、引渡しを受けて使用収益を開始したが、マシニングセンターの持ち主Bは賃貸期間" },
  'imzlaq': { source: require('@/assets/images/person-flow/minnpou/sousoku/imzlaq.png'), caption: "離婚による財産分与について、[[dict:黙示的表示::1. 財産分与での具体的な現れ方 財産分与の協議において、黙示的" },
  'inytyx': { source: require('@/assets/images/person-flow/minnpou/bukken/inytyx.png'), caption: "CがBから建物を買戻特約付売買で購入し、Bの債権者であるAのために抵当権を設定し、登記を備えた。その後、Cは買戻権を行使" },
  'j2pxua': { source: require('@/assets/images/person-flow/minnpou/bukken/j2pxua.png'), caption: "３Dプリンターの引渡しを受けた賃借人Cは、引渡しを受けて使用収益を開始したが、３Dプリンターの持ち主Bは賃貸期間の途中で" },
  'j5m76l': { source: require('@/assets/images/person-flow/minnpou/sousoku/j5m76l.png'), caption: "無権代理人であるLが亡くなり、本人であるJと妻のKが共同相続した後、Jも亡くなりKが相続するに至った場合、KはJの資格で" },
  'j9ymob': { source: require('@/assets/images/person-flow/minnpou/sousoku/j9ymob.png'), caption: "弁護士が債権を譲り受ける行為は、不当な利益の追求を目的として行われたものでない限り、直ちに効力は否定されない" },
  'jc9hu8': { source: require('@/assets/images/person-flow/minnpou/bukken/jc9hu8.png'), caption: "不動産質権者は設定者の承諾を得ずとも、目的不動産の用法に従ってその使用収益をすることができる" },
  'jeqdby': { source: require('@/assets/images/person-flow/minnpou/bukken/jeqdby.png'), caption: "Aが建物をCに売却して引渡しを完了し、Bにも売却し登記を備えた場合、CはAに対する履行不能を理由とする損害賠償請求権を被" },
  'jx92sg': { source: require('@/assets/images/person-flow/minnpou/bukken/jx92sg.png'), caption: "質権は債権などの財産権の上に設定することができる" },
  'jzljmc': { source: require('@/assets/images/person-flow/minnpou/bukken/jzljmc.png'), caption: "根抵当権について元本確定期日が定められていない場合、根抵当権設定者は、根抵当権の設定から３年を経過したときに元本確定を請" },
  'k1hp81': { source: require('@/assets/images/person-flow/minnpou/bukken/k1hp81.png'), caption: "RがR、S、Tが共有する甲土地上に、乙建物を建てて所有、居住する場合で、RがS、Tに甲土地の分割請求をする場合、現物分割" },
  'k8n0ka': { source: require('@/assets/images/person-flow/minnpou/bukken/k8n0ka.png'), caption: "Aが家電製品の販売業者のBに対して有する貸金債権の担保として、Bが営業用動産として所有し、甲R庫内において保管する在庫商" },
  'kgztw': { source: require('@/assets/images/person-flow/minnpou/sousoku/kgztw.png'), caption: "悪意であっても20年間、所有の意思をもって、平穏に、かつ、公然と他人の物を占有すると、所有権を時効取得できる" },
  'kni2x3': { source: require('@/assets/images/person-flow/minnpou/sousoku/kni2x3.png'), caption: "AとBが通謀し、AのBに対する債権をBに仮装譲渡したところ、Bは当該債権を善意のCに譲渡した。Aは虚偽表示の無効をCに対" },
  'ktw0so': { source: require('@/assets/images/person-flow/minnpou/bukken/ktw0so.png'), caption: "元本確定前に被担保債権の範囲を変更する場合、後順位抵当権者の承諾を要しない" },
  'kwr0a2': { source: require('@/assets/images/person-flow/minnpou/bukken/kwr0a2.png'), caption: "Aが所有する甲土地につき、Bの所有権の取得時効が完成し、その後、Bがこれを援用した。この場合に関する次の記述のうち、民法" },
  'l9ze71': { source: require('@/assets/images/person-flow/minnpou/bukken/l9ze71.png'), caption: "Bのスイッチ２を受寄者のCが保管していたところ、BがCに対し、今後Dのためにこれを保管することを命じ、Dが承諾した場合、" },
  'latoun': { source: require('@/assets/images/person-flow/minnpou/bukken/latoun.png'), caption: "譲渡担保の目的物にジェイズ電気が売却した低温調理器が含まれており、譲渡担保設定者が期日までに売買代金をジェイズ電気に支払" },
  'ld2x84': { source: require('@/assets/images/person-flow/minnpou/bukken/ld2x84.png'), caption: "占有権に関する次の記述のうち、民法の規定および判例に照らし、妥当でないものはどれか。" },
  'lot8iz': { source: require('@/assets/images/person-flow/minnpou/sousoku/lot8iz.png'), caption: "Aは、甲不動産をその占有者Bから購入し引渡しを受けていたが、実は甲不動産はC所有の不動産であった。BおよびAの占有の態様" },
  'lqi2ad': { source: require('@/assets/images/person-flow/minnpou/bukken/lqi2ad.png'), caption: "留置権が成立した後、債権者は債務者から留置物を譲り受けた者に対し、留置権を行使することができる" },
  'lxt70': { source: require('@/assets/images/person-flow/minnpou/sousoku/lxt70.png'), caption: "善意で仮装金銭消費貸借の債権を譲り受けた者は、借主に対して貸金の返還を求めることができる" },
  'maejs0': { source: require('@/assets/images/person-flow/minnpou/bukken/maejs0.png'), caption: "債権者が不動産の先取特権者の登記をした場合、第三取得者に対し先取特権を行使できる" },
  'mt4e03': { source: require('@/assets/images/person-flow/minnpou/bukken/mt4e03.png'), caption: "Aの土地をBが時効取得した後、Aが背信的悪意者であるGに土地を売却した場合、BはGに登記なくして対抗できる" },
  'n0rh3m': { source: require('@/assets/images/person-flow/minnpou/bukken/n0rh3m.png'), caption: "抵当権者が、被担保債権につき利息および遅延損害金を請求する権利を有するとき、抵当権者は優先弁債権を行使できるが、その満期" },
  'n5bkwi': { source: require('@/assets/images/person-flow/minnpou/sousoku/n5bkwi.png'), caption: "物上保証人は消滅時効の援用ができる" },
  'n9z431': { source: require('@/assets/images/person-flow/minnpou/bukken/n9z431.png'), caption: "不動産質権者は登記をしなければ第三者に対抗できない" },
  'oay73n': { source: require('@/assets/images/person-flow/minnpou/sousoku/oay73n.png'), caption: "保証人は消滅時効の援用ができる" },
  'oho2qb': { source: require('@/assets/images/person-flow/minnpou/sousoku/oho2qb.png'), caption: "Aの土地をBがCに売却する契約を締結した後、Bは死亡しAがBを相続した。Aに土地の所有権が認められるが、Cに対し損害賠償" },
  'ok108b': { source: require('@/assets/images/person-flow/minnpou/bukken/ok108b.png'), caption: "動産の譲受人は引き渡しを受けなければ第三者にはあたらず、当該動産の差し押さえを行った者に対抗することができない" },
  'onyrv1': { source: require('@/assets/images/person-flow/minnpou/sousoku/onyrv1.png'), caption: "本人であるJが亡くなり、無権代理人であるLが単独相続をした場合、Lは売買契約の相手方であるNに追認拒絶することはできない" },
  'oqhv6': { source: require('@/assets/images/person-flow/minnpou/sousoku/oqhv6.png'), caption: "AのBに対する甲債権につき消滅時効が完成した場合における時効の援用権者に関する次の記述のうち、民法の規定および判例に照ら" },
  'ou77fa': { source: require('@/assets/images/person-flow/minnpou/bukken/ou77fa.png'), caption: "他人の土地の地下、空中にも地上権を設定することはできる" },
  'ovie14': { source: require('@/assets/images/person-flow/minnpou/bukken/ovie14.png'), caption: "CはBに建物を売り、Bは登記を備えたが、Cに代金を支払わないままAに建物を転売し、所有権移転登記まで備えた。CはAから建" },
  'p27cw2': { source: require('@/assets/images/person-flow/minnpou/bukken/p27cw2.png'), caption: "元本が確定し、被担保債権額が極度額を２０００万円を超えた場合、抵当地の地上権を取得した加津は、債権者に極度額を払い渡して" },
  'p6lxaz': { source: require('@/assets/images/person-flow/minnpou/bukken/p6lxaz.png'), caption: "動産の受寄者で、当該動産を一時保管するに過ぎないものは、動産の新所有者から引渡し請求に応じなければならない" },
  'psq8bx': { source: require('@/assets/images/person-flow/minnpou/bukken/psq8bx.png'), caption: "Aが所有する甲建物（以下「甲」という。）につき、Bのために抵当権が設定されて抵当権設定登記が行われた後、Cのために賃借権" },
  'puxb2e': { source: require('@/assets/images/person-flow/minnpou/bukken/puxb2e.png'), caption: "抵当権の効力に関する次の記述のうち、民法の規定および判例に照らし、妥当なものはどれか。" },
  'pvhbzs': { source: require('@/assets/images/person-flow/minnpou/bukken/pvhbzs.png'), caption: "賃貸借契約の解除後の賃借人は有益費償還請求を被担保物件として建物を留置することはできない" },
  'q0vc0x': { source: require('@/assets/images/person-flow/minnpou/sousoku/q0vc0x.png'), caption: "養子縁組は、当事者間に縁組をする意思がないときは無効" },
  'q7l72g': { source: require('@/assets/images/person-flow/minnpou/sousoku/q7l72g.png'), caption: "AとBが通謀し、Aの土地をBに仮装譲渡したところ、Bは善意の債権者Eのために抵当権を設定した。AはEに虚偽表示の無効を対" },
  'q9op4t': { source: require('@/assets/images/person-flow/minnpou/sousoku/q9op4t.png'), caption: "BはAの代理人と偽って、Aが売主、Cが買主とする契約を締結した。Bが無権代理人であることをCは過失により知らなかったが、" },
  'qbaf9r': { source: require('@/assets/images/person-flow/minnpou/bukken/qbaf9r.png'), caption: "甲土地を所有するAとその隣地の乙土地を所有するBとの間の相隣関係に関する記述のうち、民法の規定に照らし、正しいものはどれ" },
  'qngurv': { source: require('@/assets/images/person-flow/minnpou/sousoku/qngurv.png'), caption: "占有の引渡しにより所有権を時効取得する場合、最初の占有者が善意なら計１０年、悪意なら計２０年で時効取得できる" },
  'qt2y86': { source: require('@/assets/images/person-flow/minnpou/bukken/qt2y86.png'), caption: "元本確定前に債権者が債務者に対して有する継続的売買契約に係る売掛金代金債権を第三者に譲渡した場合、その第三者は抵当地に対" },
  'r3iwrb': { source: require('@/assets/images/person-flow/minnpou/sousoku/r3iwrb.png'), caption: "保証人、連帯保証人、物上保証人、抵当不動産の第三取得者は消滅時効を援用することはできる" },
  'r6agyk': { source: require('@/assets/images/person-flow/minnpou/bukken/r6agyk.png'), caption: "集合物譲渡担保権の設定後、通常の営業の範囲で、譲渡担保設定者は在庫の処分をする権利を有する" },
  'rdn92p': { source: require('@/assets/images/person-flow/minnpou/bukken/rdn92p.png'), caption: "Aの土地をBが時効取得し、その後GがAから土地を買い受けて登記を備えた場合、BはGに対し登記なくして対抗することはできず" },
  'rgrg7r': { source: require('@/assets/images/person-flow/minnpou/sousoku/rgrg7r.png'), caption: "Aが所有する甲土地につき、Aの長男BがAに無断で同人の代理人と称してCに売却した（以下「本件売買契約」という。）。この場" },
  'robiwr': { source: require('@/assets/images/person-flow/minnpou/bukken/robiwr.png'), caption: "Bのゲーム機をCが保管していたところ、デトウに盗まれた。Cはデトウに対しゲーム機の返還請求及び損害賠償請求をすることがで" },
  'rvtf1y': { source: require('@/assets/images/person-flow/minnpou/sousoku/rvtf1y.png'), caption: "無権代理人であるLが死亡して、本人であるJが相続した場合、Jの資格として追認拒絶をすることはできるが、無権代理人の責任を" },
  's6avv2': { source: require('@/assets/images/person-flow/minnpou/bukken/s6avv2.png'), caption: "抵当権設定時に土地の所有者と建物の所有者が異なる場合、法定地上権は成立しない" },
  's8j5un': { source: require('@/assets/images/person-flow/minnpou/bukken/s8j5un.png'), caption: "建物とともに抵当権の目的とされた動産が、無断で搬出された場合、第三者が即時取得しない限り、抵当権者は、目的動産をもとの建" },
  'scogsz': { source: require('@/assets/images/person-flow/minnpou/bukken/scogsz.png'), caption: "本人が無権代理人を単独相続した場合、無権代理人の責任を継承し、損害賠償請求権を免れることはない" },
  'srbpw2': { source: require('@/assets/images/person-flow/minnpou/sousoku/srbpw2.png'), caption: "Aの土地をBがCに売却する契約を締結をしたが、Aが当該土地を譲渡する意思はなくとも、当該契約は有効" },
  't0a79c': { source: require('@/assets/images/person-flow/minnpou/bukken/t0a79c.png'), caption: "元本確定前、根抵当権者が根抵当権設定者に対して有する債権の一部をおっさんに譲渡した場合、おっさんは譲渡された債権について" },
  't3cs71': { source: require('@/assets/images/person-flow/minnpou/bukken/t3cs71.png'), caption: "R、S、Tが建物を共有している場合、Rが亡くなり相続人が存在しないときは、Rの持分は、S、Tに帰属する" },
  'texa8f': { source: require('@/assets/images/person-flow/minnpou/bukken/texa8f.png'), caption: "集合物譲渡担保の設定後、集合物としての同一性が損なわれない限り、譲渡担保権の効力は及ぶ" },
  'u1crxg': { source: require('@/assets/images/person-flow/minnpou/bukken/u1crxg.png'), caption: "元本確定前に債権者債務者間で被担保債権の範囲を変更することができ、後順位抵当権者への承諾は不要" },
  'ubrqgi': { source: require('@/assets/images/person-flow/minnpou/sousoku/ubrqgi.png'), caption: "AとBが通謀し、Aの土地をBに仮装譲渡したところ、Bが悪意のDに譲渡し、さらに善意のCにも譲渡した場合、Aは虚偽表示の無" },
  'udxq68': { source: require('@/assets/images/person-flow/minnpou/sousoku/udxq68.png'), caption: "後順位抵当権者は消滅時効の援用ができない" },
  'ujsstm': { source: require('@/assets/images/person-flow/minnpou/bukken/ujsstm.png'), caption: "留置権の引渡しに代理占有は含まれない" },
  'uv2f5g': { source: require('@/assets/images/person-flow/minnpou/bukken/uv2f5g.png'), caption: "Aの土地をBが時効取得し、その後GがAから土地を買い受けて抵当権設定登記を完了した場合、Bはさらに取得時効に必要な期間を" },
  'uy9q62': { source: require('@/assets/images/person-flow/minnpou/bukken/uy9q62.png'), caption: "機械部品の製造販売を行うAは、材料供給者Bと継続的取引関係を結ぶにあたり、A所有の甲土地に、極度額5,000万円、被担保" },
  'uzbrgr': { source: require('@/assets/images/person-flow/minnpou/bukken/uzbrgr.png'), caption: "債務者が他人の動産につき質権設定し、債権者が債務者の所有物であると過失なく信じた場合、質権を即時取得する" },
  'v1x9ki': { source: require('@/assets/images/person-flow/minnpou/sousoku/v1x9ki.png'), caption: "被相続人の占有により取得時効が完成した場合、その共同相続人の一人は、自己の相続分の限度においてのみ取得時効を援用できる" },
  'vgt9ex': { source: require('@/assets/images/person-flow/minnpou/bukken/vgt9ex.png'), caption: "Bのゲーム機を受寄者のCが保管していたところ、BがCに対し、今後Dのためにこれを保管することを命じ、Dが承諾した場合、D" },
  'vhiaaj': { source: require('@/assets/images/person-flow/minnpou/bukken/vhiaaj.png'), caption: "元本確定後、元本の額が極度額に満たない場合、根抵当権者は極度額の範囲内で根抵当権を行使し優先弁済を受けることができ、元本" },
  'vhoumj': { source: require('@/assets/images/person-flow/minnpou/bukken/vhoumj.png'), caption: "抵当権の効力は従物にも及び、従物に個別に対抗要件を具備しなくとも、第三者に対抗できる" },
  'vtwh6g': { source: require('@/assets/images/person-flow/minnpou/bukken/vtwh6g.png'), caption: "抵当不動産が転貸された場合、抵当権者は転貸借権に対しては物上代位を行使できない" },
  'vyvbpn': { source: require('@/assets/images/person-flow/minnpou/bukken/vyvbpn.png'), caption: "本来はAの土地である甲土地を無権利者のBから買ったCが、自分の土地であることを信じて、トウガラシを育てた場合、Aから本権" },
  'w7635q': { source: require('@/assets/images/person-flow/minnpou/bukken/w7635q.png'), caption: "動産質権者が第三者に占有を奪われた場合、占有回収の訴えによってのみ、その質物を回復できる" },
  'w8tau3': { source: require('@/assets/images/person-flow/minnpou/bukken/w8tau3.png'), caption: "A所有の甲土地上に、Bが権原なく乙建物を建設してCに譲渡した。土地の所有権を侵害したのはBだが、Aは現実に土地を占有して" },
  'we29qm': { source: require('@/assets/images/person-flow/minnpou/sousoku/we29qm.png'), caption: "抵当不動産の第三取得者は消滅時効の援用ができる" },
  'wlqlhk': { source: require('@/assets/images/person-flow/minnpou/bukken/wlqlhk.png'), caption: "元本確定前は、根抵当権の担保すべき債権の範囲を変更することができ、後順位抵当権者その他第三者の承諾は要しない" },
  'woqt4l': { source: require('@/assets/images/person-flow/minnpou/bukken/woqt4l.png'), caption: "質権に関する次の記述のうち、民法の規定および判例に照らし、妥当でないものはどれか。" },
  'x0qr8u': { source: require('@/assets/images/person-flow/minnpou/bukken/x0qr8u.png'), caption: "集合動産を一括して譲渡担保の目的とすることもできる" },
  'x1i8fe': { source: require('@/assets/images/person-flow/minnpou/bukken/x1i8fe.png'), caption: "元本確定後、元本の額が極度額に満たない場合、根抵当権設定者は、根抵当権者に対して極度額を法定額の範囲で減額を請求すること" },
  'x3szau': { source: require('@/assets/images/person-flow/minnpou/bukken/x3szau.png'), caption: "元本確定後、根抵当権者は、極度額の減額請求ができ、その範囲は現存債務の額と以後２年間に生ずべき利息、その他の定期金および" },
  'x40l2n': { source: require('@/assets/images/person-flow/minnpou/bukken/x40l2n.png'), caption: "Aが賃借している建物をベイベー銀行の抵当権の実行を妨害する目的が認められ、Aの占有により建物の交換価値の実現が妨げられ、" },
  'y5db3a': { source: require('@/assets/images/person-flow/minnpou/bukken/y5db3a.png'), caption: "即時取得において、占有開始におけるT穏、公然、善意は推定され、無過失は推定されないが外観を有していればよい" },
  'yay2kg': { source: require('@/assets/images/person-flow/minnpou/sousoku/yay2kg.png'), caption: "土地の仮装譲受人と当該土地に建てられた建物の善意の賃借人は第三者の関係にあたらないため、仮装譲受人は土地の明け渡しを求め" },
  'yrfihu': { source: require('@/assets/images/person-flow/minnpou/bukken/yrfihu.png'), caption: "第三者が賃貸不動産を不法占有している場合、賃借人は対抗要件を具備している場合に返還請求ができる" },
  'yz2oez': { source: require('@/assets/images/person-flow/minnpou/sousoku/yz2oez.png'), caption: "AとBは通謀し、Aの土地をBに仮装譲渡したところ、Bの債権者であるFがAの土地を差し押さえたところ、AはFに対し虚偽表示" }
};

export const BY_LEARN_KEY: Record<string, PersonFlowDiagramItem | PersonFlowDiagramItem[]> = {
  'learn|民法総則|15': { source: require('@/assets/images/person-flow/minnpou/sousoku/hai9wq.png'), caption: "組合規約等で業務執行の代理権限を制限しても、善意無過失の第三者には対抗できない" },
  'learn|民法総則|17': { source: require('@/assets/images/person-flow/minnpou/sousoku/j9ymob.png'), caption: "弁護士が債権を譲り受ける行為は、不当な利益の追求を目的として行われたものでない限り、直ちに効力は否定されない" },
  'learn|民法総則|30': { source: require('@/assets/images/person-flow/minnpou/sousoku/c6ri17.png'), caption: "失踪者の所有地を相続したDが甲土地を悪意のBに売却後、失踪者の生存が判明した場合、B、D間の売買契約は無効となる" },
  'learn|民法総則|31': { source: require('@/assets/images/person-flow/minnpou/sousoku/q0vc0x.png'), caption: "養子縁組は、当事者間に縁組をする意思がないときは無効" },
  'learn|民法総則|33': { source: require('@/assets/images/person-flow/minnpou/sousoku/yay2kg.png'), caption: "土地の仮装譲受人と当該土地に建てられた建物の善意の賃借人は第三者の関係にあたらないため、仮装譲受人は土地の明け渡しを求め" },
  'learn|民法総則|34': { source: require('@/assets/images/person-flow/minnpou/sousoku/e6ovye.png'), caption: "仮装債権を善意で譲り受けた者は第三者に当たるため、買主に対し売買代金の支払いを求めることができる" },
  'learn|民法総則|35': { source: require('@/assets/images/person-flow/minnpou/sousoku/lxt70.png'), caption: "善意で仮装金銭消費貸借の債権を譲り受けた者は、借主に対して貸金の返還を求めることができる" },
  'learn|民法総則|36': { source: require('@/assets/images/person-flow/minnpou/sousoku/hfb9as.png'), caption: "AとBが通謀し、Aの土地を仮装譲渡し、BはAの土地に家を建て、善意のCに賃貸した場合、Aは虚偽表示の無効をCに対抗できる" },
  'learn|民法総則|37': { source: require('@/assets/images/person-flow/minnpou/sousoku/ubrqgi.png'), caption: "AとBが通謀し、Aの土地をBに仮装譲渡したところ、Bが悪意のDに譲渡し、さらに善意のCにも譲渡した場合、Aは虚偽表示の無" },
  'learn|民法総則|38': { source: require('@/assets/images/person-flow/minnpou/sousoku/q7l72g.png'), caption: "AとBが通謀し、Aの土地をBに仮装譲渡したところ、Bは善意の債権者Eのために抵当権を設定した。AはEに虚偽表示の無効を対" },
  'learn|民法総則|39': { source: require('@/assets/images/person-flow/minnpou/sousoku/yz2oez.png'), caption: "AとBは通謀し、Aの土地をBに仮装譲渡したところ、Bの債権者であるFがAの土地を差し押さえたところ、AはFに対し虚偽表示" },
  'learn|民法総則|40': { source: require('@/assets/images/person-flow/minnpou/sousoku/kni2x3.png'), caption: "AとBが通謀し、AのBに対する債権をBに仮装譲渡したところ、Bは当該債権を善意のCに譲渡した。Aは虚偽表示の無効をCに対" },
  'learn|民法総則|41': { source: require('@/assets/images/person-flow/minnpou/sousoku/b6d79c.png'), caption: "虚偽の売買契約を保証した者は、当該契約の錯誤による取消しを主張できる" },
  'learn|民法総則|43': { source: require('@/assets/images/person-flow/minnpou/sousoku/ih7f29.png'), caption: "連帯保証人が他にも連帯保証人がいると誤信した場合でも、それは動機に過ぎないから、他の保証人の存在を特に保証契約とした旨の" },
  'learn|民法総則|44': { source: require('@/assets/images/person-flow/minnpou/sousoku/imzlaq.png'), caption: "離婚による財産分与について、[[dict:黙示的表示::1. 財産分与での具体的な現れ方 財産分与の協議において、黙示的" },
  'learn|民法総則|45': { source: require('@/assets/images/person-flow/minnpou/sousoku/4ktbor.png'), caption: "内容証明郵便が不在配達され、受取人が不在配達通知に対応しないまま留置期間が終了し、差出人に還付された場合、留置期間の満了" },
  'learn|民法総則|55': { source: require('@/assets/images/person-flow/minnpou/sousoku/srbpw2.png'), caption: "Aの土地をBがCに売却する契約を締結をしたが、Aが当該土地を譲渡する意思はなくとも、当該契約は有効" },
  'learn|民法総則|56': { source: require('@/assets/images/person-flow/minnpou/sousoku/oho2qb.png'), caption: "Aの土地をBがCに売却する契約を締結した後、Bは死亡しAがBを相続した。Aに土地の所有権が認められるが、Cに対し損害賠償" },
  'learn|民法総則|57': { source: require('@/assets/images/person-flow/minnpou/sousoku/5gmosj.png'), caption: "BはAの代理人と偽って、Aが売主、Cが買主とする契約を締結した。BはCに動産を引き渡したが、当該契約は無権代理行為に当た" },
  'learn|民法総則|58': { source: require('@/assets/images/person-flow/minnpou/sousoku/q9op4t.png'), caption: "BはAの代理人と偽って、Aが売主、Cが買主とする契約を締結した。Bが無権代理人であることをCは過失により知らなかったが、" },
  'learn|民法総則|59': { source: require('@/assets/images/person-flow/minnpou/sousoku/2yybum.png'), caption: "A社の理事であるNがCと軽自動車の売買契約を結び、本来は理事会の承認が必要でありるが、Nは承認を得なかった。CはNが理事" },
  'learn|民法総則|60': { source: require('@/assets/images/person-flow/minnpou/sousoku/onyrv1.png'), caption: "本人であるJが亡くなり、無権代理人であるLが単独相続をした場合、Lは売買契約の相手方であるNに追認拒絶することはできない" },
  'learn|民法総則|61': { source: require('@/assets/images/person-flow/minnpou/sousoku/j5m76l.png'), caption: "無権代理人であるLが亡くなり、本人であるJと妻のKが共同相続した後、Jも亡くなりKが相続するに至った場合、KはJの資格で" },
  'learn|民法総則|62': { source: require('@/assets/images/person-flow/minnpou/sousoku/22ibgx.png'), caption: "本人であるJが追認拒絶をした後に亡くなり、無権代理人であるLが単独相続した場合、Jの追認拒絶は相続人のLに及び効力を失わ" },
  'learn|民法総則|63': { source: require('@/assets/images/person-flow/minnpou/sousoku/rvtf1y.png'), caption: "無権代理人であるLが死亡して、本人であるJが相続した場合、Jの資格として追認拒絶をすることはできるが、無権代理人の責任を" },
  'learn|民法総則|64': { source: require('@/assets/images/person-flow/minnpou/sousoku/g55z9r.png'), caption: "本人であるJが死亡し、無権代理人であるLが母のKと共に共同相続した場合、Kの追認がなければ、Nとの売買契約は有効とはなら" },
  'learn|民法総則|67': { source: require('@/assets/images/person-flow/minnpou/sousoku/eps8sq.png'), caption: "AとCが売買契約を結び、禁止行為をした場合に違約金を支払う旨の定めがあったが、AはBを介してCに禁止行為を誘発させた場合" },
  'learn|民法総則|70': { source: require('@/assets/images/person-flow/minnpou/sousoku/kgztw.png'), caption: "悪意であっても20年間、所有の意思をもって、平穏に、かつ、公然と他人の物を占有すると、所有権を時効取得できる" },
  'learn|民法総則|71': { source: require('@/assets/images/person-flow/minnpou/sousoku/ajcguc.png'), caption: "１０年間、所有の意思をもって、平穏、かつ、公然と他人の物を占有した者は、占有開始時に善意かつ過失がなかったときは、所有権" },
  'learn|民法総則|72': { source: require('@/assets/images/person-flow/minnpou/sousoku/qngurv.png'), caption: "占有の引渡しにより所有権を時効取得する場合、最初の占有者が善意なら計１０年、悪意なら計２０年で時効取得できる" },
  'learn|民法総則|73': { source: require('@/assets/images/person-flow/minnpou/sousoku/g5xyuo.png'), caption: "一般訴債権の債権者は権利を行使できることを知った時から５年間行使しないとき、債権は時効により消滅する" },
  'learn|民法総則|77': { source: require('@/assets/images/person-flow/minnpou/sousoku/7axwph.png'), caption: "債権又は所有権以外の財産権は、権利を行使できる時から２０年間行使しないとき、時効により消滅する" },
  'learn|民法総則|80': { source: require('@/assets/images/person-flow/minnpou/sousoku/v1x9ki.png'), caption: "被相続人の占有により取得時効が完成した場合、その共同相続人の一人は、自己の相続分の限度においてのみ取得時効を援用できる" },
  'learn|民法総則|81': { source: require('@/assets/images/person-flow/minnpou/sousoku/r3iwrb.png'), caption: "保証人、連帯保証人、物上保証人、抵当不動産の第三取得者は消滅時効を援用することはできる" },
  'learn|民法総則|82': { source: require('@/assets/images/person-flow/minnpou/sousoku/hhayzv.png'), caption: "破産者の保証人は、消滅時効を援用することはできない" },
  'learn|民法総則|83': { source: require('@/assets/images/person-flow/minnpou/sousoku/n5bkwi.png'), caption: "物上保証人は消滅時効の援用ができる" },
  'learn|民法総則|84': { source: require('@/assets/images/person-flow/minnpou/sousoku/oay73n.png'), caption: "保証人は消滅時効の援用ができる" },
  'learn|民法総則|86': { source: require('@/assets/images/person-flow/minnpou/sousoku/udxq68.png'), caption: "後順位抵当権者は消滅時効の援用ができない" },
  'learn|民法総則|87': { source: require('@/assets/images/person-flow/minnpou/sousoku/we29qm.png'), caption: "抵当不動産の第三取得者は消滅時効の援用ができる" },
  'learn|民法物権|1': { source: require('@/assets/images/person-flow/minnpou/bukken/ou77fa.png'), caption: "他人の土地の地下、空中にも地上権を設定することはできる" },
  'learn|民法物権|100': { source: require('@/assets/images/person-flow/minnpou/bukken/t0a79c.png'), caption: "元本確定前、根抵当権者が根抵当権設定者に対して有する債権の一部をおっさんに譲渡した場合、おっさんは譲渡された債権について" },
  'learn|民法物権|101': { source: require('@/assets/images/person-flow/minnpou/bukken/5qod41.png'), caption: "集合動産の譲渡担保は、種類、場所、量的範囲を指定することによって特定され、占有改定による引渡しも現実の引渡しにあたる" },
  'learn|民法物権|102': { source: require('@/assets/images/person-flow/minnpou/bukken/texa8f.png'), caption: "集合物譲渡担保の設定後、集合物としての同一性が損なわれない限り、譲渡担保権の効力は及ぶ" },
  'learn|民法物権|103': { source: require('@/assets/images/person-flow/minnpou/bukken/r6agyk.png'), caption: "集合物譲渡担保権の設定後、通常の営業の範囲で、譲渡担保設定者は在庫の処分をする権利を有する" },
  'learn|民法物権|104': { source: require('@/assets/images/person-flow/minnpou/bukken/7n47yv.png'), caption: "譲渡担保の目的物の中にメーカーが売却したフードプロセッサーが含まれており、譲渡担保設定者であるカマダ電気が期日までにフー" },
  'learn|民法物権|105': { source: require('@/assets/images/person-flow/minnpou/bukken/latoun.png'), caption: "譲渡担保の目的物にジェイズ電気が売却した低温調理器が含まれており、譲渡担保設定者が期日までに売買代金をジェイズ電気に支払" },
  'learn|民法物権|11': { source: require('@/assets/images/person-flow/minnpou/bukken/w8tau3.png'), caption: "A所有の甲土地上に、Bが権原なく乙建物を建設してCに譲渡した。土地の所有権を侵害したのはBだが、Aは現実に土地を占有して" },
  'learn|民法物権|12': { source: require('@/assets/images/person-flow/minnpou/bukken/1v6vhu.png'), caption: "第三者の不法占有により抵当不動産の交換価値の実現が妨げられ、抵当権者の優先弁済県の行使が困難となった場合で、抵当不動産を" },
  'learn|民法物権|13': { source: require('@/assets/images/person-flow/minnpou/bukken/hvbjeb.png'), caption: "占有者が占有を奪われたとき、占有回収の訴えにより、その物の返還請求及び損害賠償請求ができる" },
  'learn|民法物権|14': { source: require('@/assets/images/person-flow/minnpou/bukken/yrfihu.png'), caption: "第三者が賃貸不動産を不法占有している場合、賃借人は対抗要件を具備している場合に返還請求ができる" },
  'learn|民法物権|15': { source: require('@/assets/images/person-flow/minnpou/bukken/609gdh.png'), caption: "A所有の甲土地上に、Bが権原なく丁建物を建設し、自己所有名義で建物保存登記を行い、Cに譲渡したが、登記名義がBのままであ" },
  'learn|民法物権|16': { source: require('@/assets/images/person-flow/minnpou/bukken/4d75i2.png'), caption: "表立った虚偽表示がなくても、それを過失なく信じた者には、94条2項が類推適用され、虚偽表示の当事者は、引渡しを求められな" },
  'learn|民法物権|17': { source: require('@/assets/images/person-flow/minnpou/bukken/scogsz.png'), caption: "本人が無権代理人を単独相続した場合、無権代理人の責任を継承し、損害賠償請求権を免れることはない" },
  'learn|民法物権|18': { source: require('@/assets/images/person-flow/minnpou/bukken/g04gd9.png'), caption: "共同相続土地を、その事情を知らず、かつ、過失のない者が登記を備えた場合であっても、土地の全部について対抗できるわけではな" },
  'learn|民法物権|19': { source: require('@/assets/images/person-flow/minnpou/bukken/dek93n.png'), caption: "Aの土地をBが買い、所有権移転の仮登記をし、Aは土地をその事情を知らないCに売却し、所有権移転登記をした場合、Bは本登記" },
  'learn|民法物権|2': { source: require('@/assets/images/person-flow/minnpou/bukken/47z53k.png'), caption: "一筆の土地の一部について、所有権を時効取得することはできる" },
  'learn|民法物権|20': { source: require('@/assets/images/person-flow/minnpou/bukken/hbgpom.png'), caption: "Aの土地にBが無断で建物を築造し、登記も備えた場合、Aから土地を買い受けたCは、登記の名義人であるBに対し、建物の収去お" },
  'learn|民法物権|21': { source: require('@/assets/images/person-flow/minnpou/bukken/10i6hb.png'), caption: "Aの土地をBの時効完成前に、CがAから土地を買い受けて登記を備えた場合、その後時効取得したBは登記なくしてCに対抗できる" },
  'learn|民法物権|22': { source: require('@/assets/images/person-flow/minnpou/bukken/mt4e03.png'), caption: "Aの土地をBが時効取得した後、Aが背信的悪意者であるGに土地を売却した場合、BはGに登記なくして対抗できる" },
  'learn|民法物権|23': { source: require('@/assets/images/person-flow/minnpou/bukken/h9bqjt.png'), caption: "Aの土地をBが時効取得し、その後GがAから土地を買い受けて所有権移転登記を完成したが、Bはさらに取得時効に必要な期間を経" },
  'learn|民法物権|24': { source: require('@/assets/images/person-flow/minnpou/bukken/uv2f5g.png'), caption: "Aの土地をBが時効取得し、その後GがAから土地を買い受けて抵当権設定登記を完了した場合、Bはさらに取得時効に必要な期間を" },
  'learn|民法物権|25': { source: require('@/assets/images/person-flow/minnpou/bukken/rdn92p.png'), caption: "Aの土地をBが時効取得し、その後GがAから土地を買い受けて登記を備えた場合、BはGに対し登記なくして対抗することはできず" },
  'learn|民法物権|26': { source: require('@/assets/images/person-flow/minnpou/bukken/ok108b.png'), caption: "動産の譲受人は引き渡しを受けなければ第三者にはあたらず、当該動産の差し押さえを行った者に対抗することができない" },
  'learn|民法物権|27': { source: require('@/assets/images/person-flow/minnpou/bukken/j2pxua.png'), caption: "３Dプリンターの引渡しを受けた賃借人Cは、引渡しを受けて使用収益を開始したが、３Dプリンターの持ち主Bは賃貸期間の途中で" },
  'learn|民法物権|28': { source: require('@/assets/images/person-flow/minnpou/bukken/p6lxaz.png'), caption: "動産の受寄者で、当該動産を一時保管するに過ぎないものは、動産の新所有者から引渡し請求に応じなければならない" },
  'learn|民法物権|29': { source: require('@/assets/images/person-flow/minnpou/bukken/8p6oeo.png'), caption: "譲渡担保の引渡しに占有改定は含まれる" },
  'learn|民法物権|3': { source: require('@/assets/images/person-flow/minnpou/bukken/x0qr8u.png'), caption: "集合動産を一括して譲渡担保の目的とすることもできる" },
  'learn|民法物権|30': { source: require('@/assets/images/person-flow/minnpou/bukken/15nldt.png'), caption: "集合物譲渡担保契約が締結され、動産の種類、量的範囲、場所が特定された場合、占有改定が行われ、動産の新たな構成部分が集合物" },
  'learn|民法物権|31': { source: require('@/assets/images/person-flow/minnpou/bukken/3je1v8.png'), caption: "即時取得の引渡しに占有改定は含まれない" },
  'learn|民法物権|32': { source: require('@/assets/images/person-flow/minnpou/bukken/ujsstm.png'), caption: "留置権の引渡しに代理占有は含まれない" },
  'learn|民法物権|33': { source: require('@/assets/images/person-flow/minnpou/bukken/3fjxzb.png'), caption: "先取特権の引渡しに占有改定は含まれる" },
  'learn|民法物権|34': { source: require('@/assets/images/person-flow/minnpou/bukken/15aesj.png'), caption: "質権の引渡しに占有改定は含まれない" },
  'learn|民法物権|36': { source: require('@/assets/images/person-flow/minnpou/bukken/y5db3a.png'), caption: "即時取得において、占有開始におけるT穏、公然、善意は推定され、無過失は推定されないが外観を有していればよい" },
  'learn|民法物権|37': { source: require('@/assets/images/person-flow/minnpou/bukken/4im2gi.png'), caption: "他人の土地を２０年以上占有した者が当該土地を時効取得する場合、他主占有事情が証明されたとき、時効取得の事情を排斥される" },
  'learn|民法物権|38': { source: require('@/assets/images/person-flow/minnpou/bukken/vyvbpn.png'), caption: "本来はAの土地である甲土地を無権利者のBから買ったCが、自分の土地であることを信じて、トウガラシを育てた場合、Aから本権" },
  'learn|民法物権|39': { source: require('@/assets/images/person-flow/minnpou/bukken/robiwr.png'), caption: "Bのゲーム機をCが保管していたところ、デトウに盗まれた。Cはデトウに対しゲーム機の返還請求及び損害賠償請求をすることがで" },
  'learn|民法物権|4': { source: require('@/assets/images/person-flow/minnpou/bukken/arh3s3.png'), caption: "樹木を土地と独立して売却することも認められる" },
  'learn|民法物権|40': { source: require('@/assets/images/person-flow/minnpou/bukken/vgt9ex.png'), caption: "Bのゲーム機を受寄者のCが保管していたところ、BがCに対し、今後Dのためにこれを保管することを命じ、Dが承諾した場合、D" },
  'learn|民法物権|42': { source: require('@/assets/images/person-flow/minnpou/bukken/9f5db1.png'), caption: "隣地から竹木の枝が境界線を越えて侵入してきた場合、竹木の所有者に催告しなければ、枝を切除することはできない" },
  'learn|民法物権|46': { source: require('@/assets/images/person-flow/minnpou/bukken/8nsior.png'), caption: "Bが他人の共有地甲の上に無断で乙建物を建てて甲を占有している場合、共有者のひとりであるGはBに対し、建物の収去および土地" },
  'learn|民法物権|47': { source: require('@/assets/images/person-flow/minnpou/bukken/h8ki7u.png'), caption: "Cが、R、S、Tの共有する乙建物をRの承諾のもと賃借して居住し、R、S、Tの共有する甲土地を占有した場合、S、Tは当然に" },
  'learn|民法物権|48': { source: require('@/assets/images/person-flow/minnpou/bukken/5f52r2.png'), caption: "R、S、Tで共有地甲を分割する際、甲土地上の乙建物の所有者であるCに対し分割に際する通知をする義務はないが、Cは自己の費" },
  'learn|民法物権|49': { source: require('@/assets/images/person-flow/minnpou/bukken/k1hp81.png'), caption: "RがR、S、Tが共有する甲土地上に、乙建物を建てて所有、居住する場合で、RがS、Tに甲土地の分割請求をする場合、現物分割" },
  'learn|民法物権|5': { source: require('@/assets/images/person-flow/minnpou/bukken/fqsrq1.png'), caption: "地役権は、継続的に行使され、かつ、外形上認識することができるものに限り、時効取得できる" },
  'learn|民法物権|50': { source: require('@/assets/images/person-flow/minnpou/bukken/t3cs71.png'), caption: "R、S、Tが建物を共有している場合、Rが亡くなり相続人が存在しないときは、Rの持分は、S、Tに帰属する" },
  'learn|民法物権|51': { source: require('@/assets/images/person-flow/minnpou/bukken/26n4o0.png'), caption: "排水地役権を妨害された場合、地役権に基づく損害賠償請求および妨害予防請求が認められるが、占有権能を含まないことから、返還" },
  'learn|民法物権|52': { source: require('@/assets/images/person-flow/minnpou/bukken/gh51xf.png'), caption: "眺望を害されない地役権を設定し登記を備えた後に、建物の築造により眺望を害された場合、地役権に基づき建物の収去を求めること" },
  'learn|民法物権|53': { source: require('@/assets/images/person-flow/minnpou/bukken/3k7hfd.png'), caption: "囲繞地通行権は地上権者にも準用される" },
  'learn|民法物権|54': { source: require('@/assets/images/person-flow/minnpou/bukken/s6avv2.png'), caption: "抵当権設定時に土地の所有者と建物の所有者が異なる場合、法定地上権は成立しない" },
  'learn|民法物権|55': { source: require('@/assets/images/person-flow/minnpou/bukken/5qkpvg.png'), caption: "Cが地上権設定行為に基づき建物を築造し、期間の満了により地上権が消滅した場合で、土地所有者のAが当該建物を買い取る旨を通" },
  'learn|民法物権|56': { source: require('@/assets/images/person-flow/minnpou/bukken/50obsw.png'), caption: "留置権者は善管注意義務を負い、善管注意義務は自己の財産に対するのと同一の注意よりも重い" },
  'learn|民法物権|57': { source: require('@/assets/images/person-flow/minnpou/bukken/953az3.png'), caption: "留置権者が債務者の承諾を得ずに留置物を使用、賃貸、担保に供した場合、債務者は留置権の消滅を請求できる" },
  'learn|民法物権|58': { source: require('@/assets/images/person-flow/minnpou/bukken/pvhbzs.png'), caption: "賃貸借契約の解除後の賃借人は有益費償還請求を被担保物件として建物を留置することはできない" },
  'learn|民法物権|59': { source: require('@/assets/images/person-flow/minnpou/bukken/lqi2ad.png'), caption: "留置権が成立した後、債権者は債務者から留置物を譲り受けた者に対し、留置権を行使することができる" },
  'learn|民法物権|6': { source: require('@/assets/images/person-flow/minnpou/bukken/6z1p5r.png'), caption: "A所有の甲土地上に権原なくB所有の乙建物が存在し、Bが乙建物をCに譲渡した後もB名義のままとした場合、その登記がBの意思" },
  'learn|民法物権|60': { source: require('@/assets/images/person-flow/minnpou/bukken/jeqdby.png'), caption: "Aが建物をCに売却して引渡しを完了し、Bにも売却し登記を備えた場合、CはAに対する履行不能を理由とする損害賠償請求権を被" },
  'learn|民法物権|61': { source: require('@/assets/images/person-flow/minnpou/bukken/ovie14.png'), caption: "CはBに建物を売り、Bは登記を備えたが、Cに代金を支払わないままAに建物を転売し、所有権移転登記まで備えた。CはAから建" },
  'learn|民法物権|62': { source: require('@/assets/images/person-flow/minnpou/bukken/1s7dnm.png'), caption: "Bが建物をCに売却し引渡しまでしたが、BはAに二重譲渡し登記まで備えた場合、CはAからの建物引渡し請求に対し、Bに対する" },
  'learn|民法物権|63': { source: require('@/assets/images/person-flow/minnpou/bukken/gd15wg.png'), caption: "BがAの所有する不動産をCに売却し引き渡したが、Aから所有権を取得して引き渡すことができなかった場合、CはAからの建物引" },
  'learn|民法物権|64': { source: require('@/assets/images/person-flow/minnpou/bukken/90zkuh.png'), caption: "Cが建物をAに賃貸したが、Aに賃料の不払いがあったため賃貸借契約を解除したところ、Aが建物を占有し続け、有益費を支出した" },
  'learn|民法物権|65': { source: require('@/assets/images/person-flow/minnpou/bukken/i95ymt.png'), caption: "敷金返還請求権を保全するために留置権を行使することはできない" },
  'learn|民法物権|66': { source: require('@/assets/images/person-flow/minnpou/bukken/ib73gn.png'), caption: "不動産の保存の先取特権を直ちに登記した場合、同一不動産上に登記された既存の抵当権に優先する" },
  'learn|民法物権|68': { source: require('@/assets/images/person-flow/minnpou/bukken/48u33t.png'), caption: "不動産売買の先取特権では、不動産の代価またはその利息の弁済がされていない旨を登記しなければならないが、その優劣は登記の前" },
  'learn|民法物権|69': { source: require('@/assets/images/person-flow/minnpou/bukken/maejs0.png'), caption: "債権者が不動産の先取特権者の登記をした場合、第三取得者に対し先取特権を行使できる" },
  'learn|民法物権|7': { source: require('@/assets/images/person-flow/minnpou/bukken/2zvxo1.png'), caption: "A所有の甲土地上に権原なくD所有の未登記丁建物が存在し、未登記のままCに譲渡した場合、DはAに対し丁建物の収去および甲土" },
  'learn|民法物権|71': { source: require('@/assets/images/person-flow/minnpou/bukken/w7635q.png'), caption: "動産質権者が第三者に占有を奪われた場合、占有回収の訴えによってのみ、その質物を回復できる" },
  'learn|民法物権|72': { source: require('@/assets/images/person-flow/minnpou/bukken/n9z431.png'), caption: "不動産質権者は登記をしなければ第三者に対抗できない" },
  'learn|民法物権|73': { source: require('@/assets/images/person-flow/minnpou/bukken/uzbrgr.png'), caption: "債務者が他人の動産につき質権設定し、債権者が債務者の所有物であると過失なく信じた場合、質権を即時取得する" },
  'learn|民法物権|74': { source: require('@/assets/images/person-flow/minnpou/bukken/jc9hu8.png'), caption: "不動産質権者は設定者の承諾を得ずとも、目的不動産の用法に従ってその使用収益をすることができる" },
  'learn|民法物権|75': { source: require('@/assets/images/person-flow/minnpou/bukken/jx92sg.png'), caption: "質権は債権などの財産権の上に設定することができる" },
  'learn|民法物権|76': { source: require('@/assets/images/person-flow/minnpou/bukken/vhoumj.png'), caption: "抵当権の効力は従物にも及び、従物に個別に対抗要件を具備しなくとも、第三者に対抗できる" },
  'learn|民法物権|77': { source: require('@/assets/images/person-flow/minnpou/bukken/bbkpli.png'), caption: "借地上の建物に抵当権が設定された場合、その建物の抵当権の効力は、借地権に及ぶ" },
  'learn|民法物権|78': { source: require('@/assets/images/person-flow/minnpou/bukken/inytyx.png'), caption: "CがBから建物を買戻特約付売買で購入し、Bの債権者であるAのために抵当権を設定し、登記を備えた。その後、Cは買戻権を行使" },
  'learn|民法物権|79': { source: require('@/assets/images/person-flow/minnpou/bukken/vtwh6g.png'), caption: "抵当不動産が転貸された場合、抵当権者は転貸借権に対しては物上代位を行使できない" },
  'learn|民法物権|8': { source: require('@/assets/images/person-flow/minnpou/bukken/s8j5un.png'), caption: "建物とともに抵当権の目的とされた動産が、無断で搬出された場合、第三者が即時取得しない限り、抵当権者は、目的動産をもとの建" },
  'learn|民法物権|80': { source: require('@/assets/images/person-flow/minnpou/bukken/n0rh3m.png'), caption: "抵当権者が、被担保債権につき利息および遅延損害金を請求する権利を有するとき、抵当権者は優先弁債権を行使できるが、その満期" },
  'learn|民法物権|81': { source: require('@/assets/images/person-flow/minnpou/bukken/2qju0k.png'), caption: "Cがベイベー銀行との抵当権設定登記後に、CはAへ抵当建物を賃貸し、Aが抵当不動産の交換価値を妨げ、優先弁債権の行使が困難" },
  'learn|民法物権|82': { source: require('@/assets/images/person-flow/minnpou/bukken/ahcnvw.png'), caption: "ベイベイの抵当権が実行され、買受人であるIは、Aに対し直ちに妨害排除請求はできず、Iの買受けの時から6か月を経過するまで" },
  'learn|民法物権|83': { source: require('@/assets/images/person-flow/minnpou/bukken/78wv0b.png'), caption: "CがAに対して有する賃料債権をBに譲渡し、その旨を内容証明郵便によって行い、ベイベー銀行が差し押さえを行った場合、Aがい" },
  'learn|民法物権|84': { source: require('@/assets/images/person-flow/minnpou/bukken/x40l2n.png'), caption: "Aが賃借している建物をベイベー銀行の抵当権の実行を妨害する目的が認められ、Aの占有により建物の交換価値の実現が妨げられ、" },
  'learn|民法物権|85': { source: require('@/assets/images/person-flow/minnpou/bukken/4utn8m.png'), caption: "AがCの承諾を得てIに転貸借した場合であっても、AがIに対して有する転貸賃料債権を物上代位することはできない" },
  'learn|民法物権|86': { source: require('@/assets/images/person-flow/minnpou/bukken/az5pff.png'), caption: "根抵当権の被担保債権の範囲は、極度額を限度とする" },
  'learn|民法物権|87': { source: require('@/assets/images/person-flow/minnpou/bukken/wlqlhk.png'), caption: "元本確定前は、根抵当権の担保すべき債権の範囲を変更することができ、後順位抵当権者その他第三者の承諾は要しない" },
  'learn|民法物権|88': { source: require('@/assets/images/person-flow/minnpou/bukken/35jqzo.png'), caption: "根抵当権の元本確定期日は定めることも、変更することもでき、この期日は、定めまたは変更した日から5年以内でなければならず、" },
  'learn|民法物権|89': { source: require('@/assets/images/person-flow/minnpou/bukken/83t93l.png'), caption: "元本確定前に抵当権者から免責的債務引受により被担保債権を譲り受けた者は、根抵当権を行使できず、根抵当権者も引受債務につい" },
  'learn|民法物権|9': { source: require('@/assets/images/person-flow/minnpou/bukken/apo2lt.png'), caption: "抵当権設定者が抵当不動産を他人に賃貸した場合、競売手続きを妨害する目的が認められ、賃借人の占有により交換価値の実現が妨げ" },
  'learn|民法物権|90': { source: require('@/assets/images/person-flow/minnpou/bukken/x3szau.png'), caption: "元本確定後、根抵当権者は、極度額の減額請求ができ、その範囲は現存債務の額と以後２年間に生ずべき利息、その他の定期金および" },
  'learn|民法物権|91': { source: require('@/assets/images/person-flow/minnpou/bukken/u1crxg.png'), caption: "元本確定前に債権者債務者間で被担保債権の範囲を変更することができ、後順位抵当権者への承諾は不要" },
  'learn|民法物権|92': { source: require('@/assets/images/person-flow/minnpou/bukken/qt2y86.png'), caption: "元本確定前に債権者が債務者に対して有する継続的売買契約に係る売掛金代金債権を第三者に譲渡した場合、その第三者は抵当地に対" },
  'learn|民法物権|93': { source: require('@/assets/images/person-flow/minnpou/bukken/94bikx.png'), caption: "元本確定前、債権者は、債務者の承諾を得て、根抵当権を第三者に譲り渡すことができる" },
  'learn|民法物権|94': { source: require('@/assets/images/person-flow/minnpou/bukken/7awekt.png'), caption: "元本確定後、債務者は、債権者に対し極度額の減額を請求でき、その範囲は、被担保債権額と以後２年間に生ずべき利息その他定期金" },
  'learn|民法物権|95': { source: require('@/assets/images/person-flow/minnpou/bukken/p27cw2.png'), caption: "元本が確定し、被担保債権額が極度額を２０００万円を超えた場合、抵当地の地上権を取得した加津は、債権者に極度額を払い渡して" },
  'learn|民法物権|96': { source: require('@/assets/images/person-flow/minnpou/bukken/jzljmc.png'), caption: "根抵当権について元本確定期日が定められていない場合、根抵当権設定者は、根抵当権の設定から３年を経過したときに元本確定を請" },
  'learn|民法物権|97': { source: require('@/assets/images/person-flow/minnpou/bukken/ktw0so.png'), caption: "元本確定前に被担保債権の範囲を変更する場合、後順位抵当権者の承諾を要しない" },
  'learn|民法物権|98': { source: require('@/assets/images/person-flow/minnpou/bukken/x1i8fe.png'), caption: "元本確定後、元本の額が極度額に満たない場合、根抵当権設定者は、根抵当権者に対して極度額を法定額の範囲で減額を請求すること" },
  'learn|民法物権|99': { source: require('@/assets/images/person-flow/minnpou/bukken/vhiaaj.png'), caption: "元本確定後、元本の額が極度額に満たない場合、根抵当権者は極度額の範囲内で根抵当権を行使し優先弁済を受けることができ、元本" }
};

export const BY_QUIZ_KEY: Record<string, PersonFlowDiagramItem | PersonFlowDiagramItem[]> = {
  'quiz|民法総則|13': { source: require('@/assets/images/person-flow/minnpou/sousoku/rgrg7r.png'), caption: "Aが所有する甲土地につき、Aの長男BがAに無断で同人の代理人と称してCに売却した（以下「本件売買契約」という。）。この場" },
  'quiz|民法総則|15': { source: require('@/assets/images/person-flow/minnpou/sousoku/lot8iz.png'), caption: "Aは、甲不動産をその占有者Bから購入し引渡しを受けていたが、実は甲不動産はC所有の不動産であった。BおよびAの占有の態様" },
  'quiz|民法総則|18': { source: require('@/assets/images/person-flow/minnpou/sousoku/oqhv6.png'), caption: "AのBに対する甲債権につき消滅時効が完成した場合における時効の援用権者に関する次の記述のうち、民法の規定および判例に照ら" },
  'quiz|民法総則|8': { source: require('@/assets/images/person-flow/minnpou/sousoku/befbnv.png'), caption: "虚偽表示の無効を対抗できない善意の第三者に関する次の記述のうち、民法の規定および判例に照らし、妥当でないものはどれか。" },
  'quiz|民法物権|10': { source: require('@/assets/images/person-flow/minnpou/bukken/2y89gp.png'), caption: "問題文 A、BおよびCが甲土地を共有し、甲土地上には乙建物が存在している。この場合に関する次のア〜オの記述のうち、民法の" },
  'quiz|民法物権|11': { source: require('@/assets/images/person-flow/minnpou/bukken/3hwd6w.png'), caption: "A所有の甲土地とB所有の乙土地が隣接し、甲土地の上にはC所有の丙建物が存在している。この場合における次のア〜オの記述のう" },
  'quiz|民法物権|12': { source: require('@/assets/images/person-flow/minnpou/bukken/2sth13.png'), caption: "留置権に関する次の記述のうち、民法の規定および判例に照らし、妥当なものはどれか。" },
  'quiz|民法物権|13': { source: require('@/assets/images/person-flow/minnpou/bukken/2my5og.png'), caption: "留置権に関する次の記述のうち、民法の規定および判例に照らし、妥当でないものはどれか。" },
  'quiz|民法物権|15': { source: require('@/assets/images/person-flow/minnpou/bukken/woqt4l.png'), caption: "質権に関する次の記述のうち、民法の規定および判例に照らし、妥当でないものはどれか。" },
  'quiz|民法物権|16': { source: require('@/assets/images/person-flow/minnpou/bukken/puxb2e.png'), caption: "抵当権の効力に関する次の記述のうち、民法の規定および判例に照らし、妥当なものはどれか。" },
  'quiz|民法物権|17': { source: require('@/assets/images/person-flow/minnpou/bukken/psq8bx.png'), caption: "Aが所有する甲建物（以下「甲」という。）につき、Bのために抵当権が設定されて抵当権設定登記が行われた後、Cのために賃借権" },
  'quiz|民法物権|18': { source: require('@/assets/images/person-flow/minnpou/bukken/9rtk6f.png'), caption: "根抵当権に関する次の記述のうち、民法の規定に照らし、正しいものはどれか。" },
  'quiz|民法物権|19': { source: require('@/assets/images/person-flow/minnpou/bukken/2gv45d.png'), caption: "Aは債権者Bのため、A所有の甲土地に、被担保債権の範囲をA・B間の継続的売買に係る売掛代金債権とし、その極度額を1億円と" },
  'quiz|民法物権|20': { source: require('@/assets/images/person-flow/minnpou/bukken/uy9q62.png'), caption: "機械部品の製造販売を行うAは、材料供給者Bと継続的取引関係を結ぶにあたり、A所有の甲土地に、極度額5,000万円、被担保" },
  'quiz|民法物権|21': { source: require('@/assets/images/person-flow/minnpou/bukken/k8n0ka.png'), caption: "Aが家電製品の販売業者のBに対して有する貸金債権の担保として、Bが営業用動産として所有し、甲R庫内において保管する在庫商" },
  'quiz|民法物権|4': { source: require('@/assets/images/person-flow/minnpou/bukken/cd8yez.png'), caption: "Aが登記簿上の所有権名義人である甲土地をBが買い受ける旨の契約（以下「本件売買契約」という。）をA・B間で締結した場合に" },
  'quiz|民法物権|5': { source: require('@/assets/images/person-flow/minnpou/bukken/kwr0a2.png'), caption: "Aが所有する甲土地につき、Bの所有権の取得時効が完成し、その後、Bがこれを援用した。この場合に関する次の記述のうち、民法" },
  'quiz|民法物権|7': { source: require('@/assets/images/person-flow/minnpou/bukken/i9mob0.png'), caption: "占有改定等に関する次のア～オの記述のうち、民法の規定および判例に照らし、妥当でないものの組合せはどれか。" },
  'quiz|民法物権|8': { source: require('@/assets/images/person-flow/minnpou/bukken/ld2x84.png'), caption: "占有権に関する次の記述のうち、民法の規定および判例に照らし、妥当でないものはどれか。" },
  'quiz|民法物権|9': { source: require('@/assets/images/person-flow/minnpou/bukken/qbaf9r.png'), caption: "甲土地を所有するAとその隣地の乙土地を所有するBとの間の相隣関係に関する記述のうち、民法の規定に照らし、正しいものはどれ" }
};

export function getPersonFlowImageSource(key: string): number | undefined {
  if (!key) return undefined;
  const normalized = key.replace(/\.(png|jpg|jpeg|webp)$/i, '');
  const allMaps = [BY_QUESTION_TEXT_HASH, BY_LEARN_KEY, BY_QUIZ_KEY];
  for (const map of allMaps) {
    const v = map[normalized] ?? map[key];
    if (!v) continue;
    const item = Array.isArray(v) ? v[0] : v;
    if (item?.source) return item.source;
  }
  return undefined;
}
